### ISSUE TITLE
Deflection Bug

### ISSUE THREAD

**Issue by Nastras** [SeydX/homebridge-fritz-platform#1]
Good morning, I have tested version 2.6.2. It works all but deflection and it still can not be turned on or off. In the log it is displayed but nothing happens on the Fritzbox.

The new function refresh wifi canal also works, but maybe the name refresh wifi channel would be better here .-)?

Greeting Nastra

**Comment by Krocko** [comment]
Deflection works for me with v2.6.2. 
Only thing that doesn‘t work is Device Lock. 
Fritzbox 7590 with latest Labor Firmware.

**Comment by Nastras** [comment]
That's funny, I have the 7590 without labor firmware, me device lock works without problems. Have already made a reboot, but has not solved the problem.

@Krocko  Why are you no longer with us in the Smart Apple Forum :-(?
