### ISSUE TITLE
WARNING: there is no master router defined

### ISSUE THREAD

**Issue by abbanatic** [SeydX/homebridge-fritz-platform#100]
Hi,

first let me say a big thank you for your work!

I tried to update to version 5.0.3 and started with a minimal configuration:

        {
            "name": "FritzPlatform",
            "debug": true,
            "devices": [
                {
                    "name": "FritzBox 7590",
                    "username": "abbanatic",
                    "password": "xxxxx",
                    "ssl": true,
                    "tr064": true,
                    "igd": true,
                    "readOnly": false,
                    "hide": false,
                    "model": "7590",
                    "serialNumber": "xxxxx",
                    "master": true,
                    "connection": "dsl",
                    "options": {
                        "wifi_2ghz": "switch",
                        "wifi_5ghz": "characteristic",
                        "wifi_guest": "switch",
                        "wps": "switch",
                        "dect": "switch",
                        "aw": "switch",
                        "deflection": "switch",
                        "led": "switch",
                        "lock": "switch"
                    }
                }
            ],
            "presence": [
                {
                    "ping": false
                }
            ],
            "smarthome": [
                {
                    "accType": "false"
                }
            ],
            "callmonitor": {
                "active": false,
                "port": 1012
            },
            "extras": {
                "alarm": {
                    "active": false
                },
                "wakeup": {
                    "active": false
                },
                "ringlock": {
                    "active": false
                },
                "phoneBook": {
                    "active": true,
                    "accType": "switch"
                }
            },
            "options": {
                "polling": {
                    "timer": 10
                }
            },
            "telegram": {
                "active": false
            },
            "platform": "FritzPlatform"
        }

Unfortunately, the box and the switches don't appear in Homekit. 

The log says:
Nov 10 15:27:25 abbapie01 homebridge[28075]: [11/10/2020, 3:27:25 PM] [FritzPlatform] Initializing FritzPlatform platform...
Nov 10 15:27:28 abbapie01 homebridge[28075]: [11/10/2020, 3:27:28 PM] [FritzPlatform] WARNING: There is no master router defined!
Nov 10 15:27:28 abbapie01 homebridge[28075]: [11/10/2020, 3:27:28 PM] [FritzPlatform] WARNING: Please define ONE master router to proceed!

But I defined the FritzBox to be the master router.

Please be so kind to tell me, what I'm doing wrong!

Thanks,
Thomas

**Comment by SeydX** [comment]
@abbanatic 

You forgot ``host`` for your device

https://github.com/SeydX/homebridge-fritz-platform/blob/3eff5e91ce9ae9f45b9d7a6fd0c74a68ad06e000/example/example-config.json#L18

**Comment by abbanatic** [comment]
Sorry, I saw it 3 minutes ago. 😩
There's a host field in config-ui-x, but not in the config.json.

Sorry again for bothering you, this issue can be closed.

Thomas

**Comment by SeydX** [comment]
@abbanatic 

no problem, I am glad that I could be helpful
