### ISSUE TITLE
Anmeldung an FritzBox nicht möglich

### ISSUE THREAD

**Issue by BKrnk1337** [SeydX/homebridge-fritz-platform#101]
Guten Abend, 

nach dem Update (vorherige Deinstallation des alten Plugins und Löschung der Konfiguration) bekomme ich nun folgende Fehlermeldung. Könnte es sein, dass die Auth. mittels 2FA nicht (mehr) unterstützt wird oder es hier andere Probleme gibt? Die Konfiguration habe ich überprüft und keine Fehler feststellen können.

Hier noch die Fehlermeldung:

[11/10/2020, 16:33:59] [FritzPlatform] FRITZ!Box 7490: An error occured during polling state (router)
[11/10/2020, 16:33:59] [FritzPlatform] Error: Invalid response: 401:Unauthorized
    at Request._callback (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/src/lib/request.ts:30:13)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[11/10/2020, 16:33:59] [FritzPlatform] FRITZ!Box 7490 Wifi guest: Polling

**Comment by SeydX** [comment]
@BKrnk1337 

Sind Sonderzeichen im Namen/Passwort enthalten?

**Comment by BKrnk1337** [comment]
Jup. Name und Passwort wurden jedoch nicht verändert.

**Comment by SeydX** [comment]
Das Plugin unterstützt zurzeit keine Sonderzeichen im Namen/Passwort

Versuch mal bitte ohne Sonderzeichen

**Comment by BKrnk1337** [comment]
Das ist schade. Dann muss ich jetzt erstmal Name und Passwort verändert? Etwas schade, dass dies vorher nicht kommuniziert wurde.

**Comment by BKrnk1337** [comment]
Sind Unterstriche für dich Sonderzeichen?

**Comment by SeydX** [comment]
@BKrnk1337 

Das war für die v5 nicht so geplant und kam NACH dem release raus und bereits in meiner TODO liste als bug gekennzeichnet

Arbeite bereits daran. Aber JETZT ist es leider nur ohne Sonderzeichen möglich, sprich nur Buchstaben und Zahlen sind erlaubt

Lg

**Comment by BKrnk1337** [comment]
Danke für die Information. Die FritzBox bekommt jedenfalls "unbekannte Anmeldeversuche" im Ereignismonitor mit.
Wirst du in einer zukünftigen Version die autom. Übernahme der Konfiguration von <5 unterstützen?

Ich muss jetzt nämlich gleich los und kann daher nicht weiter testen. Würde jetzt erstmal auf <5 zurückrollen und dann nochmal Versuchen, wenn es Bugfixes gibt.

Bleib gesund und mache weiter deine gute Arbeit. Kann man dich über PayPal unterstützen?

**Comment by Vati80** [comment]
Hallo SeydX,
auch von mir ein großes Dankeschön für deine tolle Arbeit! Ich teste auch schon seit Tagen fleißig mit und freue mich über das neue komplett überarbeitete Plugin. Ein Kaffee ist unterwegs.

Gruß Vati

**Comment by BKrnk1337** [comment]
> @BKrnk1337
> 
> Das war für die v5 nicht so geplant und kam NACH dem release raus und bereits in meiner TODO liste als bug gekennzeichnet
> 
> Arbeite bereits daran. Aber JETZT ist es leider nur ohne Sonderzeichen möglich, sprich nur Buchstaben und Zahlen sind erlaubt
> 
> Lg


@SeydX

So ich habe mir jetzt doch etwas Zeit freigeschaufelt und mal den Loginnamen und das Passwort um Sonderzeichen erleichtert. Jetzt scheint es wieder zu funktionieren.

Kannst du mir eventuell noch erklären was genau in den Einstellungen der FritzBox unter "Switch or Characteristic" bspw. beim WiFi meinst. Switch ist selbsterklärend, aber "Characteristic" sind dann nur Info-Werte ohne On/Off Funktion?

**Comment by SeydX** [comment]
@BKrnk1337 

Mit „Characteristic“ ist gemeint das der Schalter nur dem Hauptschalter zu sehen ist. Es wird kein zusätzliche Schalter erzeugt. Und dieser ist nur über Deittanbieter Apps wie EVE sehbar. Siehe hier

![3082C9B9-39C6-4CAE-AA51-953DA8E9A812](https://user-images.githubusercontent.com/34152761/98712136-32cfc880-2386-11eb-8469-898ecbbfe0da.png)

**Comment by BKrnk1337** [comment]
@SeydX Vielen Dank für die Antwort. Home+ zeig dies ebenfalls an. Eine weitere Frage: "ReadOnly" im Master-Bereich bedeutet, dass ich die FritzBox nicht aus Versehen ausschalten kann, richtig? Aber die anderen Schalter, wenn konfiguriert sind weiterhin steuerbar?

<img width="680" alt="image" src="https://user-images.githubusercontent.com/27677748/98712860-25ffa480-2387-11eb-8bbc-fd1a37968b86.png">

**Comment by SeydX** [comment]
@BKrnk1337 

Genau so ist es

**Comment by SeydX** [comment]
Fixed in v5.0.4
