### ISSUE TITLE
Expose DECT 440 as temperature sensor only

### ISSUE THREAD

**Issue by MrWGT** [SeydX/homebridge-fritz-platform#102]
Updated to 5.0.3 and converted my old config into new one. With some guesses all is working ok. But would like to expose the temperature sensor of a DECT 440 as "stand alone" but not as switch and temperature sensor. Is there a way to realize it?

Current config for DECT 440:
    {
        "name": "Fritzschalter WZ",
        "ain": "123456123456",
        "active": false,
        "accType": "switch",
        "battery": true,
        "temperature": true
    },

This way i've a switch "Fritzschalter WZ" and a temperature sensor. But i want to expose only temperature to homekit.

Thanks Gerd

**Comment by SeydX** [comment]
This is not possible atm, will add it to my todo list

**Comment by SeydX** [comment]
Added in v5.0.7
