### ISSUE TITLE
Wrong settings text in incoming calls / telegram

### ISSUE THREAD

**Issue by BKrnk1337** [SeydX/homebridge-fritz-platform#103]
I think there is a small mistake in the description. In the settings for Telegram> Callmonitor it says “User not Detected”, but I think the option should be called “Outgoing Call”. "Anyone Detected" is also not entirely correct, right?

<img width="594" alt="image" src="https://user-images.githubusercontent.com/27677748/98717162-053a4d80-238d-11eb-8718-889a077e8dc5.png">

**Comment by SeydX** [comment]
Thx @BKrnk1337 you re right

Copy paste issue :D 

Will fix it

**Comment by SeydX** [comment]
Fixed in v5.0.4
