### ISSUE TITLE
Password Fritzbox with special characters

### ISSUE THREAD

**Issue by giannimp** [SeydX/homebridge-fritz-platform#104]
Can you add Password Fritzbox with special characters type @ # etc. ???
thank you

**Comment by BKrnk1337** [comment]
Hello @giannimp the problem is already known and will be fixed by @SeydX in an upcoming update.

https://github.com/SeydX/homebridge-fritz-platform/issues/101#issuecomment-724785020

**Comment by SeydX** [comment]
@giannimp 

fixed in v5.0.4
