### ISSUE TITLE
Characteristics not updated in eve

### ISSUE THREAD

**Issue by Phoenix-DH** [SeydX/homebridge-fritz-platform#105]
I just moved from another fritz plugin back to this one.
I have a FritzBox 6490 from Vodafone Germany with lates FW 7.12.
I get all managed, except the characteristics which are only visible in the eve app are all set to off and will have no effect when changing the state.

Is there any recommendation for the settings?

And one additional question:
"readOnly": true - Does this onyl mean that there is no chance to power off the FritzBox only?
Because for my DECT200 I wan't to have this feature available too. Or will this then work for all exposed devices?
Because on this DECT200 my whole rack is powered, means powering off by accident will kill everything :)

**Comment by SeydX** [comment]
Log wit enabled debug would be nice

**Comment by Phoenix-DH** [comment]
Will deliver it....
But what I can say actually, the switch is working the way arround:
When showing off and switching to on, as example AW will turned off, same like DECT.

**Comment by Phoenix-DH** [comment]
<img width="642" alt="Screenshot 2020-11-10 at 22 00 52" src="https://user-images.githubusercontent.com/44058592/98736198-ce703180-23a4-11eb-8651-3886a9ce9ff2.png">

More will not happen like this which is visible in the screenshot.
But at the point when I click on ON, the AW was already ON and will get OFF.
Clicking after that on OFF will NOT turn it ON.

**Comment by SeydX** [comment]
can u post ur config pls

**Comment by Phoenix-DH** [comment]
Okay, dann deutsch :)

Meine Config:
```
      {
            "name": "FritzPlatform",
            "debug": false,
            "devices": [
                {
                    "name": "FritzBox",
                    "host": "192.168.XXX.1",
                    "username": "XXX",
                    "password": "XXX",
                    "ssl": true,
                    "tr064": true,
                    "igd": true,
                    "manufacturer": "AVM",
                    "model": "FRITZ!Box 6490 Cable (kdg)",
                    "serialNumber": "XXX",
                    "oldFW": false,
                    "master": true,
                    "readOnly": true,
                    "connection": "cable",
                    "options": {
                        "wifi_2ghz": "characteristic",
                        "wifi_5ghz": "characteristic",
                        "wifi_guest": "characteristic",
                        "wps": "characteristic",
                        "dect": "characteristic",
                        "aw": "characteristic",
                        "deflection": "characteristic",
                        "led": "characteristic",
                        "lock": "characteristic"
                    }
                }
            ],
            "presence": [
                {
                    "ping": false
                }
            ],
            "smarthome": [
                {
                    "name": "Rack",
                    "ain": "XXX",
                    "energy": true,
                    "temperature": true,
                    "accType": "switch"
                }
            ],
            "callmonitor": {
                "active": false,
                "port": 1012
            },
            "extras": {
                "alarm": {
                    "active": false
                },
                "wakeup": {
                    "active": false
                },
                "ringlock": {
                    "active": false
                },
                "phoneBook": {
                    "active": false
                }
            },
            "options": {
                "polling": {
                    "timer": 10
                }
            },
            "telegram": {
                "active": false
            },
            "platform": "FritzPlatform"
        }
```

Ist Version 7.12, ist eine gemietete Box ... Keine Updates vorhanden.

**Comment by SeydX** [comment]
@Phoenix-DH 

Du könntest mal die Box neustarten, und bei den options mal nach und nach die characteristics einschalten... evtl finden wir so den Fehler

**Comment by Phoenix-DH** [comment]
Box ist neu gesdtartet, aber die einzigen Switches die richtig funktionieren sind WLAN 2.4 und 5.
Die funktionieren zuverlässig.

Der Rest gar nicht.... es ändert sich auch kein Status wenn ich in der UI was ändere.

Guest Wifi tut sich gar nix.
Genauso wie bei LED.
WPS ist normal an, ist es in EVE aus und ich mache es aus, dann geht es aus, aber nicht mehr an.

Anrufbeantworter geht bei demn Switch von aus auf an ... aus ... aber auch nir mehr an, ebenso keine Statusänderungen nach Wechsel in der UI.

Was genau ist denn Deflection und Device Lock?

**Comment by SeydX** [comment]
@Phoenix-DH 

Device Lock ist Tastensperre und Deflection ist Rufumleitung

Höchstwahrscheinlich liegt es daran weil deine Version nicht ganz unterstützt wird :/

Sachen wie Bandbreite, AW, LED fragen nicht die TR064 API ab, sie holen sich die Daten direkt von der Fritzbox Oberläche. Und die Endpunkte zu diesen Daten sind bei deiner Version entweder nicht vorhanden oder sind anders benannt

**Comment by Phoenix-DH** [comment]
Danke für die Info.

Hmm, dsnnnlss ich das einfach so laufen.
Bekomme eh bald ne eigene.

**Comment by SeydX** [comment]
Ich schließe das hier mal, da der Grund des Problems die veraltete FW ist. 
Entwickle das Plugin für FW >= 7.2

PR zum supporten einer alten FW würde ich mir aber angucken bzw annehmen

lg

**Comment by Phoenix-DH** [comment]
Dank dir für deine Arbeit und Mühe!
Mit der Entwicklung kenne ich mich leider nicht aus.
