### ISSUE TITLE
AVM Thermostat - Window Sensor not working (?)

### ISSUE THREAD

**Issue by BKrnk1337** [SeydX/homebridge-fritz-platform#106]
I noticed two little things when configuring the thermostats with the "Window Sensor" option. I have activated this option for each thermostat and although the thermostat itself does not recognize an open window (this can be set on the Fritz.Box GUI) the sensor is shown as active or contact recognized in my home app. Is that correct or do I not understand the sensor and the display correctly?

![image](https://user-images.githubusercontent.com/27677748/98736936-ca90df00-23a5-11eb-985d-12ec3430eaa0.jpeg)

![image](https://user-images.githubusercontent.com/27677748/98736922-c664c180-23a5-11eb-9284-00cd32e19bff.jpeg)

**Comment by SeydX** [comment]
@BKrnk1337 

the default state is contact detected. If the thermostat itself doesnt recognize window opening, it will not change

**Comment by BKrnk1337** [comment]
Guten Abend. Das Problem besteht quasi weiterhin. Das Thermostat bemerkt, dass das Fenster offen ist (Frostsymbol im Bildschirm auf dem Thermostat), aber es erfolgt keine Benachrichtigung im Homebridge Log oder in HomeKit.
