### ISSUE TITLE
Mistake in example-config.json

### ISSUE THREAD

**Issue by b-seite** [SeydX/homebridge-fritz-platform#109]
Hi Hello, 
as i tried to install fritz-platform yesterday i found an error in the config exsample on line 62. 
There is a misplaces trailed comma on that line

Thank you for that great Plugin, it works great even with Hoods

https://github.com/SeydX/homebridge-fritz-platform/blob/1c2705a1cddc3a4d25bfcea4860d1f935c01fd93/example/example-config.json#L62

**Comment by SeydX** [comment]
Thanks, fixed :)
