### ISSUE TITLE
Uninstallation and clear device list

### ISSUE THREAD

**Issue by BerkTam** [SeydX/homebridge-fritz-platform#11]
**Describe the bug**
When removing the Fritz-Platform details from the config.json file it shows still after a restart 
all the devices from the previous config.json. It is not possible to clear all the devices which had been added to config.json even not after a full uninstall of Fritz-Platform. 

**To Reproduce**
1. Go to –>  remove all details in "FritzPlatform' in the config.json file and after a restart of the homebridge it will show you all the FritzPlatform devices/sensors again which should not happen actually. 

**Expected behavior**
1. a way to clear the FritzPlatform sensors totaly if want to refresh all the sensors in FritzPlatform
2. recognition of the "devices" does not work when there are more than 2 devices (smartphones)
3. Uninstallation of the full FritzPlatform

**Comment by BerkTam** [comment]
any feedback here?

**Comment by SeydX** [comment]
Should be fixed with v3
