### ISSUE TITLE
Small query: Node.js dependency

### ISSUE THREAD

**Issue by BKrnk1337** [SeydX/homebridge-fritz-platform#112]
Is it necessary to depend on a specific Node.js version? Apparently this is set to at least 12.18.3 (if I'm not mistaken) However, according to Node.js Git> = 12 is sufficient and supported until 2020.

**Comment by SeydX** [comment]
I set it to 12.18.3 because its the current LTS and also my dev environment. In the future maybe i will bump it to v14 if it go live as LTS.

But you can use this plugin also on another Version of Node. On Node < 12 it will cause maybe some issues because of the function that i am using
