### ISSUE TITLE
no master router defined

### ISSUE THREAD

**Issue by tmgraeter** [SeydX/homebridge-fritz-platform#113]
Hello, i have a warning: 

WARNING: There is no master router defined! 

on the status line and the Fritz!Box is not shown on "Devices"

Do you have an idea what i have to change in the config file.
"master = true" is set.

Best regards
Thomas

**Comment by SeydX** [comment]
Can u post ur config pls

**Comment by tmgraeter** [comment]
Here it is:

{
            "name": "FritzPlatform",
            "devices": [
                {
                    "name": "Firitz!6360",
                    "username": "",
                    "password": "",
                    "ssl": true,
                    "tr064": true,
                    "igd": true,
                    "master": true,
                    "connection": "cable",
                    "options": {
                        "wps": "switch",
                        "led": "characteristic"
                    }
                }
            ],
            "presence": [
                {
                    "ping": false
                }
            ],
            "smarthome": [
                {
                    "accType": "false"
                }
            ],
            "callmonitor": {
                "active": false,
                "port": 1012
            },
            "extras": {
                "alarm": {
                    "active": false
                },
                "wakeup": {
                    "active": false
                },
                "ringlock": {
                    "active": false
                },
                "phoneBook": {
                    "active": true,
                    "accType": "switch"
                }
            },
            "options": {
                "polling": {
                    "timer": 10
                }
            },
            "telegram": {
                "active": false
            },
            "platform": "FritzPlatform"
        }

**Comment by SeydX** [comment]
@tmgraeter 

You have no host defined for the router

**Comment by tmgraeter** [comment]
I have filled out the field in the UI config but as you say it is not in the config.

can you tell me the setting for this "host": 192.168.178.28 for example or something in addition ?

**Comment by SeydX** [comment]
@tmgraeter 

Oh it seems i have forgotten to add it into config ui x

Yes something like 192.168.178.1

**Comment by tmgraeter** [comment]
Ok thank you ... now it connects ... haveing still some changes to do ..
have a nice evening

**Comment by SeydX** [comment]
Thx, also :)
