### ISSUE TITLE
Phonebook feature not clear/not working

### ISSUE THREAD

**Issue by tooh** [SeydX/homebridge-fritz-platform#117]
**Describe the bug**
No phonebook switch in Home and Eve.
No resolution of caller id's in callmonitor.

**To Reproduce**

**Expected behavior**

From the docs I understand that I can use an option Phonebook.
I choose this in the config, but don.t know where to look for the switch that is supposed to be generated.
I see call monitor incoming and outgoing in Eve. I can confirm that an incoming call is registered, but I expected caller details.
I suppose the Phonebook option is needed for this ?.

**Screenshots**

Screen in Eve.

![afbeelding](https://user-images.githubusercontent.com/429386/98945896-7136c600-24f3-11eb-851c-08b34964151c.png)

**Desktop (please complete the following information):**
 - OS: Rpi
 - Version homebridge-fritz-platform v5.0.8 

**Smartphone (please complete the following information):**
 - Device: max XS
 - OS: [e.g. iOS14

**Additional context**

**Comment by SeydX** [comment]
If you choose phonebook accessory type as „characteristic“, then u need to look into your master device via third party app.

Accessory type „switch“ means that it will be exposed a a switch.

**Comment by tooh** [comment]
Thanks for your reply.
Still it is not clear to me what is the use case of Phonebook option.

I'm aware of the Phonebook in Fritz. Ut hiw can I use it in your plugin?

I assumed it was used for lookup of callers in the monitor?

As the screendump shows this does not work.

**Comment by SeydX** [comment]
The phonebook option creates a phonebook.json file with all of your phonebook entries which will be used for callmonitor to get information about the caller

**Comment by tooh** [comment]
OK

I've found phonebook.json in /usr/lib/homebridge/fritzbox on my raspberry.

File however is empty.

**Comment by SeydX** [comment]
You need to turn on the phonebook switch to generate the file

**Comment by tooh** [comment]
I receive folllowing error
``
[FritzPlatform] FritzBox PhoneBook: An error occured during setting state (phoneBook)
[11/13/2020, 5:04:32 PM] [FritzPlatform] Error: action X_AVM-DE_GetVoIPCommonCountryCode of urn:dslforum-org:service:X_VoIP:1 not known
    at Service.<anonymous> (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/src/lib/service.ts:182:13)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/dist/lib/service.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

``

**Comment by SeydX** [comment]
@tooh 

Which fritzbox router and firmware ?

**Comment by tooh** [comment]
Fon WLAN 7390
Fritz!OS : 06.86

**Comment by SeydX** [comment]
@tooh 

You need at least v7 to use this plugin. Otherwise u will get errors.

Your FritzBox doesn’t support VOIP, the plugin needs the endpoint to query the correct country prefix like +49

I could implement a fallback, so user can decide it over config.json, but i can not guarantee that everything else will working fine due to the reason u re on FW v6.86

**Comment by tooh** [comment]
@SeydX thanks for investigating.

I see on the AVM site that the 7390  is end of support, so I assume they will not upgrade the firmware.

I appreciate your offer, but I agree with you that probably the next issue is around the corner.

**Comment by SeydX** [comment]
@tooh 

I do all this in my spare time and I also have to work on the side. Unfortunately I don't have the time to test older versions or to support them.

Here in Github you can see which versions are currently supported.

The project is open source and anyone is welcome to fork and extend it or send a PR. I would like to see it and implement it

**Comment by SeydX** [comment]
@tooh 

i will implement a „country“ option to config to skip the VOIP API call. This should fix the phoneBook issue for you

**Comment by tooh** [comment]
@SeydX 
Much appreciated!

**Comment by SeydX** [comment]
@tooh 

Should be fixed with v5.0.10

**Comment by SeydX** [comment]
@tooh 

there is a „countryPrefix“ option now under callmonitor. Just add your country prefix there with config ui x and it should work

**Comment by tooh** [comment]
@SeydX 

Installed new version.

Testresults:

- Phonebook is now dumped to the directory.

- Added countrycode in config.

 No resolution of callername yet.

I'm debugging this by switching on the -D flag on homebridge level.

Do not see anything related to the callername yet. Will investigate further.

Remarkable observation: logging info coming from your plugin is labeled as coming from WeatherPlus, another 
Plugin I use that is using fakegato.

Will investigate this further.

Thanks  for now.

**Comment by SeydX** [comment]
> Remarkable observation: logging info coming from your plugin is labeled as coming from WeatherPlus, another
> Plugin I use that is using fakegato.

Whot? Can i see the log pls
