### ISSUE TITLE
FRITZ!Box 7490An error occured by getting device state!

### ISSUE THREAD

**Issue by TNTLarsn** [SeydX/homebridge-fritz-platform#12]
[FritzBox] [ERROR] {
    "error": "Internal Server Error",
    "errorCode": 500,
    "tr064": "Invalid Action",
    "tr064code": "401",
    "serviceType": "urn:dslforum-org:service:WANPPPConnection:1",
    "action": "GetStatusInfo",
    "device": "FRITZ!Box 7490",
    "host": "fritz.box"
}

Running new FritzOS 07.01

**Comment by SeydX** [comment]
should be fixed with latest release
