### ISSUE TITLE
Error during polling state 

### ISSUE THREAD

**Issue by idominiki** [SeydX/homebridge-fritz-platform#121]
After one day of usage I got attached error with my 7590
![483096D1-98D1-453A-AB85-A9B34C20C43C](https://user-images.githubusercontent.com/62521486/99115096-2f407980-25f2-11eb-8444-05f48b3067f5.png)

**Comment by SeydX** [comment]
@idominiki 

Unauthorized? Wrong credentials?

**Comment by idominiki** [comment]
I 'm logging in to the FritzBox without a username. The username field in the config is "". It works one day, but now I'm getting these errors

**Comment by SeydX** [comment]
@idominiki 

Can u try with v5.0.9 pls

**Comment by idominiki** [comment]
Worked now again! Thanks
