### ISSUE TITLE
Plugin legt HOOBS lahm

### ISSUE THREAD

**Issue by freddair** [SeydX/homebridge-fritz-platform#123]
Hallo,

seit dem vorletzten und jetzt auch noch mit dem neuesten Plugin-Update lässt sich Hoobs nicht mehr starten.

Log:

14.11.2020, 09:52:33 [FritzPlatform] Initializing FritzPlatform platform...
14.11.2020, 09:52:33 TypeError: this.config.devices.map is not a function
    at new FritzPlatform (/home/hoobs/.hoobs/node_modules/homebridge-fritz-platform/src/platform.js:79:25)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:346:30
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
14.11.2020, 09:52:33 Got SIGTERM, shutting down Bridge...

**Comment by SeydX** [comment]
Hattest du vorher v4 am laufen? Dein config scheint falsch zu sein

**Comment by freddair** [comment]
ja hatte ich... ok, gibt es eine Anleitung, was geändert werden muss? Hab inzwischen Node.js auf den neuesten Stand gebracht und jetzt ist Hoobs nicht mehr erreichbar...

**Comment by SeydX** [comment]
@freddair 

Hier steht alles was man wissen muss

https://github.com/SeydX/homebridge-fritz-platform#changelog

**Comment by freddair** [comment]
> @freddair 
> 
> 
> 
> Hier steht alles was man wissen muss
> 
> 
> 
> https://github.com/SeydX/homebridge-fritz-platform#changelog

Danke @SeydX !
