### ISSUE TITLE
Question about Callmonitor and telephone number format

### ISSUE THREAD

**Issue by MirkoKas** [SeydX/homebridge-fritz-platform#125]
Hey,

it's seems I'm not able to configure the callmonitor as I want to.
I only want the contact sensor to trigger if one of my three telephone numbers in Fritzbox is called or called from.

It doesn't matter if I enter just the number in the format 12345678 or with the city code for example 030 for Berlin. The Callmonitor also triggers on any other number I have configured in FritzBox. What is it, that I'm doing wrong?

I also noticed an error/difference when I configure the plugin with Config-UI-X or directly in the config.json.
In Config-UI it's called "OutgoingTo" while in the config.json it's "OutgoingFrom". I expect the later is the correct interpretation, right?

Heres the part of my config.json

```
"callmonitor": {
                "active": true,
                "group": true,
                "ip": "192.168.1.42",
                "port": 1012,
                "incomingTo": [
                    "03012345678"
                ],
                "outgoingFrom": [
                    "12345678"
                ]
            },
```

**Comment by SeydX** [comment]
@MirkoKas 

„outgoingFrom“ is correct. Will fix this.

Atm the callmonitor will trigger on any calls. The „incomingTo/outgoingFrom are just for formatting text for log/telegram.

But u re right, i think what u want was my first intention on implementing „incomingTo“ and „outgoingFrom“. Need to refactor callmonitor again ^^

**Comment by MirkoKas** [comment]
Thanks for the clarification. I’m happy that it wasn’t me for me being to stupid to configure it properly. :-)
Looking forward for this feature but no rush. I really appreciate your work with this plugin and rewriting it completely!

**Comment by SeydX** [comment]
@MirkoKas 

Changed in v5.0.10

**Comment by MirkoKas** [comment]
Works perfectly! Thx.
