### ISSUE TITLE
Add additional information to callmonitor (telegram)

### ISSUE THREAD

**Issue by meinname** [SeydX/homebridge-fritz-platform#126]
Hi,
i noticed % on Callmonitor Telegram incoming messages doesn't get replaced with the number that gets called anymore.
Can you add this feature again as it was very useful when having multiple numbers.

**Comment by SeydX** [comment]
@meinname 

You re using a wrong char. Please repleace "%" with "@"

**Comment by meinname** [comment]
Hmm. just tried 
"incoming": "Eingehender Anruf von @ an @",
shows 
"Eingehender Anruf von 01xxxxxxxx an @"

**Comment by SeydX** [comment]
@meinname 

Telegram acceppts only one „@„ for callmonitor atm.

**Comment by SeydX** [comment]
Changed the title and labeled as enhancement.

Will add additional info to callmonitor (telegram) for next release

**Comment by meinname** [comment]
Great thank you 👍

**Comment by SeydX** [comment]
@meinname 

added in v5.0.11
