### ISSUE TITLE
Fritz & Comet DECT Thermostats interruptions in temp history (eve app)

### ISSUE THREAD

**Issue by olliox** [SeydX/homebridge-fritz-platform#127]
Since upgrading to the newest version, my Fritz and Comet Thermostats don't record the whole temp history in the eve app - which worked before. They have lacks of several hours, not following any pattern I understand.

**Comment by SeydX** [comment]
@olliox

That has nothing to do with the update. It seems that the internal timer from fakegato doesnt seems to work

**Comment by olliox** [comment]
@SeydX do you know how to get rid of this problem? it worked like charm before i updated.

**Comment by SeydX** [comment]
@olliox 

im already on it

https://github.com/simont77/fakegato-history/issues/106

**Comment by SeydX** [comment]
Fixed in v5.0.13
