### ISSUE TITLE
Option LED on/off in FritzBox 6591 only works partially

### ISSUE THREAD

**Issue by Holydevil66** [SeydX/homebridge-fritz-platform#129]
The on/off characteristic of the LED works well on my FritzBox 7590 and all of my FritzRepeater 3000.
But on the main box, a FritzBox 6591 (KDG / FritzOS 7.13), only "on" works - "off" does nothing (using EVE App)
In Homebridge/Hoobs, everything's looks ok, no error:

![image](https://user-images.githubusercontent.com/43577348/99429610-8737f280-2908-11eb-943b-186759d040fe.png)

**Comment by SeydX** [comment]
@Holydevil66 

Could you enable „Old FW“ in config ui x for this device pls and try again

**Comment by Holydevil66** [comment]
Wow... das nenne ich mal Reaktionszeit!
Klappt 👍
