### ISSUE TITLE
Presence - add notification option

### ISSUE THREAD

**Issue by Holydevil66** [SeydX/homebridge-fritz-platform#130]
I use presence and have telegram bot activated, works all fine.
But I wish I could have an option within presence to activate/deactivate telegram notifications per address/person - I don't need telegram to notify me I arrived at home 😉

**Comment by SeydX** [comment]
Added in v5.0.13

https://github.com/SeydX/homebridge-fritz-platform/blob/c4d669f1504594586da8f925e5b82177b2cfe927/example/example-config.json#L92
