### ISSUE TITLE
Seit gestern unterstützt der DECT 440 mit Firmware 5.10 die Anzeige von Luftfeuchtigkeit. Falls das über die API abfragbar ist, wäre es schön, diese auch zu Mappen 😅

### ISSUE THREAD

**Issue by MrWGT** [SeydX/homebridge-fritz-platform#131]
Auszug aus dem Web:

Nun bekommt der smarte Schalter Fritz!DECT 440 die Möglichkeit, nicht nur die Temperatur sondern auch die Luftfeuchtigkeit zu messen und auf dem E-Paper-Display anzuzeigen. 

Danke 

Gerd

**Comment by SeydX** [comment]
Die [Fritz API](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf) zeigt dazu leider nichts. Ist die Luftfeuchtigkeit auch über die Fritzbox Oberfläche sichtbar?

**Comment by MrWGT** [comment]
Ja, wird sie. Siehe Screenshot 7590:

https://1drv.ms/u/s!Assv5fIy-dXzgpdoZUKNtSPchxasig

**Comment by MrWGT** [comment]
In der Smarthome App von AVM allerdings (noch?) nicht.

**Comment by SeydX** [comment]
@MrWGT 

Ahh. Die Smarthome App funktioniert auch über die Fritz AHA-HTTP API. Sieht so aus als müsste die API noch aktualisiert werden. Sobald das der Fall ist werde ich es natürlich hinzufügen

**Comment by MrWGT** [comment]
Aktuell bin ich auf der neuesten 7590 Labor und nutze auch die Smarthome App von AVM. Mit dieser Mit dieser jetzt auch die Luftfeuchtigkeit in der App angezeigt. Die Info muss also jetzt über die API vorhaben sein.

[](https://1drv.ms/u/s!Assv5fIy-dXzgpdq2Lmm4Y6YwplLuQ)

**Comment by SeydX** [comment]
@MrWGT 

v5.0.18 ist online mit Luftfeuchtigkeitssensor support. (Einfach in config ui x unter Smarthome > Advanced "Humidity Sensor" einschalten)

Da ich kein Gerät dafür zum Testen da habe würde ich mich freuen wenn du die Funktion testen könntest und Rückmeldung geben könntest

lg

**Comment by MrWGT** [comment]
Wie geht das über die Config? Nutze Hoobs 3.3.1 und da ist auf der Oberfläche nichts auswählbar.

**Comment by MrWGT** [comment]
![image](https://user-images.githubusercontent.com/64701400/101181826-a1363c80-364d-11eb-9779-208de2ed27ab.jpeg)

**Comment by MrWGT** [comment]
![image](https://user-images.githubusercontent.com/64701400/101181853-a7c4b400-364d-11eb-823f-c4367e131589.jpeg)

**Comment by MrWGT** [comment]
Wenn ich debug enable, dann steht folgendes im Log:

4.12.2020, 16:56:09 [FritzPlatform] Fritzschalter WZ: Polling state (smarthome-temperature

4.12.2020, 16:56:09 [FritzPlatform] Fritzschalter WZ: {"name":"Temperatur WZ","id":"18","ain":"099950407656","online":1,"bitmask":"1048864","busy":0,"battery":{"value":100,"low":0},"alert":false,"temperature":{"value":22,"offset":0},"humidity":false,"powermeter":false,"switch":false,"button":[{"$":{"identifier":"09995 0407656-1","id":"5004"},"name":"Temperatur WZ: Oben rechts","lastpressedtimestamp":""},{"$":{"identifier":"09995 0407656-3","id":"5005"},"name":"Temperatur WZ: Unten rechts","lastpressedtimestamp":""},{"$":{"identifier":"09995 0407656-5","id":"5006"},"name":"Temperatur WZ: Unten links","lastpressedtimestamp":""},{"$":{"identifier":"09995 0407656-7","id":"5007"},"name":"Temperatur WZ: Oben links","lastpressedtimestamp":""}],"thermostat":false,"light":false}

4.12.2020, 16:56:09 [FritzPlatform] Fritzschalter KiZi: Polling state (smarthome-temperature)...

4.12.2020, 16:56:09 [FritzPlatform] Fritzschalter KiZi: {"name":"Temperatur KiZi","id":"20","ain":"099950407980","online":1,"bitmask":"1048864","busy":0,"battery":{"value":80,"low":0},"alert":false,"temperature":{"value":21,"offset":0},"humidity":false,"powermeter":false,"switch":false,"button":[{"$":{"identifier":"09995 0407980-1","id":"5000"},"name":"Temperatur KiZi: Oben rechts","lastpressedtimestamp":""},{"$":{"identifier":"09995 0407980-3","id":"5001"},"name":"Temperatur KiZi: Unten rechts","lastpressedtimestamp":""},{"$":{"identifier":"09995 0407980-5","id":"5002"},"name":"Temperatur KiZi: Unten links","lastpressedtimestamp":""},{"$":{"identifier":"09995 0407980-7","id":"5003"},"name":"Temperatur KiZi: Oben links","lastpressedtimestamp":""}],"thermostat":false,"light":false}

**Comment by SeydX** [comment]
@MrWGT 

Werde für die nächste Version mal debug erweitern, dann sollte ich sehen können woran es scheitert

**Comment by SeydX** [comment]
@MrWGT 

Kannst du bitte v5.0.19 probieren mit eingeschaltetem debug

Im Log müsste ein Eintrag stehen wie 

```
[5.12.2020, 09:03:24] [FritzPlatform] SmartHome Devices: [ ... ]
```

Genau diesen Eintrag brauche ich zum debuggen

**Comment by MrWGT** [comment]
5.12.2020, 09:13:56 [FritzPlatform] SmartHome Devices: [{"$":{"identifier":"09995 0453543","id":"17","functionbitmask":"320","fwversion":"04.95","manufacturer":"AVM","productname":"FRITZ!DECT 301"},"present":"1","txbusy":"0","name":"Heizung WZ","battery":"80","batterylow":"0","temperature":{"celsius":"215","offset":"-5"},"hkr":{"tist":"49","tsoll":"43","absenk":"36","komfort":"43","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1607203800","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"$":{"identifier":"09995 0407656","id":"18","functionbitmask":"1048864","fwversion":"05.10","manufacturer":"AVM","productname":"FRITZ!DECT 440"},"present":"1","txbusy":"0","name":"Temperatur WZ","battery":"100","batterylow":"0","temperature":{"celsius":"215","offset":"0"},"humidity":{"rel_humidity":"39"},"button":[{"$":{"identifier":"09995 0407656-1","id":"5004"},"name":"Temperatur WZ: Oben rechts","lastpressedtimestamp":""},{"$":{"identifier":"09995 0407656-3","id":"5005"},"name":"Temperatur WZ: Unten rechts","lastpressedtimestamp":""},{"$":{"identifier":"09995 0407656-5","id":"5006"},"name":"Temperatur WZ: Unten links","lastpressedtimestamp":""},{"$":{"identifier":"09995 0407656-7","id":"5007"},"name":"Temperatur WZ: Oben links","lastpressedtimestamp":""}]},{"$":{"identifier":"09995 0409035","id":"19","functionbitmask":"320","fwversion":"04.95","manufacturer":"AVM","productname":"FRITZ!DECT 301"},"present":"1","txbusy":"0","name":"Heizung KiZi","battery":"80","batterylow":"0","temperature":{"celsius":"205","offset":"-25"},"hkr":{"tist":"43","tsoll":"42","absenk":"32","komfort":"42","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"80","nextchange":{"endperiod":"1607203800","tchange":"32"},"summeractive":"0","holidayactive":"0"}},{"$":{"identifier":"09995 0407980","id":"20","functionbitmask":"1048864","fwversion":"05.10","manufacturer":"AVM","productname":"FRITZ!DECT 440"},"present":"1","txbusy":"0","name":"Temperatur KiZi","battery":"80","batterylow":"0","temperature":{"celsius":"205","offset":"0"},"humidity":{"rel_humidity":"43"},"button":[{"$":{"identifier":"09995 0407980-1","id":"5000"},"name":"Temperatur KiZi: Oben rechts","lastpressedtimestamp":""},{"$":{"identifier":"09995 0407980-3","id":"5001"},"name":"Temperatur KiZi: Unten rechts","lastpressedtimestamp":""},{"$":{"identifier":"09995 0407980-5","id":"5002"},"name":"Temperatur KiZi: Unten links","lastpressedtimestamp":""},{"$":{"identifier":"09995 0407980-7","id":"5003"},"name":"Temperatur KiZi: Oben links","lastpressedtimestamp":""}]},{"$":{"identifier":"11934 0208370","id":"407","functionbitmask":"1","fwversion":"31.20","manufacturer":"0x0feb","productname":"HAN-FUN"},"present":"1","txbusy":"0","name":"Kleines Fenster KiZi"},{"$":{"identifier":"11934 0208370-1","id":"2001","functionbitmask":"8208","fwversion":"0.0","manufacturer":"0x0feb","productname":"HAN-FUN"},"present":"1","txbusy":"0","name":"Kleines Fenster KiZi","etsiunitinfo":{"etsideviceid":"407","unittype":"514","interfaces":"256"},"alert":{"state":"0","lastalertchgtimestamp":"1607058226"}},{"$":{"identifier":"12701 0016851","id":"406","functionbitmask":"1","fwversion":"00.00","manufacturer":"0x319d","productname":"HAN-FUN"},"present":"0","txbusy":"0","name":"RGB Lampe"},{"$":{"identifier":"12701 0016851-1","id":"2000","functionbitmask":"237572","fwversion":"0.0","manufacturer":"0x319d","productname":"HAN-FUN"},"present":"0","txbusy":"0","name":"RGB Lampe","simpleonoff":{"state":""},"levelcontrol":{"level":"","levelpercentage":""},"colorcontrol":{"$":{"supported_modes":"0","current_mode":"","fullcolorsupport":"0","mapped":"0"},"hue":"","saturation":"","unmapped_hue":"","unmapped_saturation":"","temperature":""},"etsiunitinfo":{"etsideviceid":"406","unittype":"278","interfaces":"512,514,513"}}]

**Comment by SeydX** [comment]
@MrWGT 

Super vielen Dank

Sollte nun mit v5.0.20 funktionieren

lg

**Comment by MrWGT** [comment]
Geht 🙂 Danke 👍🏻![image](https://user-images.githubusercontent.com/64701400/101238170-ae4f3c00-36de-11eb-98d1-3038f838da3a.jpeg)

**Comment by SeydX** [comment]
Super :)
