### ISSUE TITLE
Fehlerhafte Temperatur Steuerung - Thermostat durch Szene

### ISSUE THREAD

**Issue by BKrnk1337** [SeydX/homebridge-fritz-platform#132]
Guten Abend,

Seit dem letzten Update auf Version 5 habe ich ein komisches Verhalten von meinen DECT Thermostaten. Diese verstellen sich, ohne mein Zutun, einfach auf eine Temperatur, welche in keiner Szene (in der Home App) definiert ist.

Ich habe bspw. ein Thermostat im Schlafzimmer, welches immer auf 17 Grad gestellt wird. Jedoch wenn ich nach Hause komme immer auf 22 Grad steht. 

Ich vermute, dass es hier ein Problem gibt. Wie gesagt das Thermostat ist zwar in Szene enthalten, aber dort überall auf 17 Grad gestellt.

Hast du hier vielleicht eine Idee? Liegt es an den Off-Set Temperatur Angaben? Behandelst du diese nun ggf. anderes?

Liebe Grüße ￼

**Comment by SeydX** [comment]
Das Plugin verwendet die von dir eingestellte Offset.

Ich schaue mal ob es bei mir das selbe Verhalten hat

**Comment by BKrnk1337** [comment]
Ich habe mir das ganze jetzt noch mal angeschaut. Mittlerweile hat es eine Zeit lang wieder funktioniert. Was mir jetzt merkwürdig vorkommt ist das ich wenn ich die Temperatur in der Küche auf 23° Stelle dann wird ebenfalls jedes Thermostat welches in der FRITZ!Box als Gruppe mit diesen Thermostat hinterlegt es auf die gleiche Temperatur gestellt. Ich habe bei dir in der Plaque in Konfiguration jedoch keine gruppieren Geräte eingestellt. Nur in der FRITZ!Box Oberfläche habe ich zwei Gruppen erstellt.

Weißt du woran das liegen könnte oder ist das Problem bekannt? Ich habe jetzt erst mal die Gruppen in der FRITZ!Box gelöscht und gucke mal wie das Ganze sich verhält.￼￼

**Comment by SeydX** [comment]
@BKrnk1337 

Das wird bestimmt an Fritzbox liegen. Kannst du mal probieren ob du das Gerät einzeln über die FritzBox Oberfläche steuern kannst obwohl dieser in einer Gruppe ist mit anderen Thermostaten? Und kannst du anschließend mal gucken ob die Temperaturen der anderen Thermostate sich ebenfalls ändern

Lg

**Comment by BKrnk1337** [comment]
Habe ich getestet. Wie du schon vermutet hast liegt es wohl an der FRITZ!Box. Wenn ich über die Oberfläche das eine Thermostat verändere dann wird ebenfalls das andere Thermostat welches auch in der Gruppe hängt auf die gleiche Temperatur gesetzt.

Dann werde ich jetzt einfach die Gruppen in der FRITZ!Box löschen und das ganze nur noch über HomeKit laufen lassen. Ist sowieso wesentlich einfacher.

Habe auch keine Option gefunden in der FRITZ!Box Oberfläche hier dieses Verhalten zu unterdrücken. Bin mir aber sicher dass das damals nicht so war. Keine Ahnung was AVM da nun wieder gemacht dort hat.

￼￼

**Comment by SeydX** [comment]
@BKrnk1337 

Funktionieren die Thermostate nun auch in Szenen? Oder besteht das Problem weiterhin?

**Comment by BKrnk1337** [comment]
Das Problem besteht weiterhin. Habe gerade noch mal eine Gruppe erstellt und versucht einzeln die Temperaturen zu verändern. Das wirkt sich jeweils auf die ganze Gruppe aus.

￼

**Comment by SeydX** [comment]
@BKrnk1337 

Ne ich meine nicht das. Das kann ich leider nicht ändern da es an FritzBox liegt. Ich meine das hier

>> Diese verstellen sich, ohne mein Zutun, einfach auf eine Temperatur, welche in keiner Szene (in der Home App) definiert ist.

**Comment by BKrnk1337** [comment]
Das Problem konnte ich nicht mehr feststellen.￼

**Comment by SeydX** [comment]
@BKrnk1337 

Alles klar. Dann schließ ich das hier mal weil es sich ja darauf bezogen hatte und das das Ändern der einzelnen Geräte in der Gruppe sich auf alle auswirkt liegt am FritzBox
