### ISSUE TITLE
Number to Phonebook does not work for Telegram notifications

### ISSUE THREAD

**Issue by california444** [SeydX/homebridge-fritz-platform#138]
**Describe the bug**
Thanks for the great plugin!
I expected that it should be possible to map an incoming call in Callmonitor  to an entry in the Fritz!Box phonebook.
This does not work. The telegram message always shows the number, not the phonebook entry name.

**To Reproduce**
1. make an entry in Fritz!Box phonebook for a given number.
2. activate phonebook and Callmonitor in the plugin settings.
3. activate telegram messages for incoming calls.
4. call fritzbox from the given number

**Expected behavior**
the telegram message shows the name not the number of the caller

**Comment by SeydX** [comment]
You need to create a phonebook.json file

Open your config and set phonebook type to characteristic or switch. This will expose a switch accessory or characteristic to HomeKit. To create the file, just toggle the switch. This will create the phonebook.json file. This is needed to map the incoming call to the phonebook entry to get the name

**Comment by california444** [comment]
Great. That worked. Thank you. 
I haven‘t found that hint in the documentation. Maybe you want to add it. That feature is really good.
