### ISSUE TITLE
Need Help for fritz-platform as after the update (Version 5.0.18) nothing warkes and I am such a newbie 😬

### ISSUE THREAD

**Issue by ManuNewbie** [SeydX/homebridge-fritz-platform#140]
Hey Guys.
I updated my smoothly running "fritz-platform" plugin, for which a great guy helped me setting it up...BUT now, everything is not working and I kind of have to build a new .json
now it seems to be kind of "HOOBS-certified", because it leaves separate fields to write in in the configuration section - but this is to much for me without help...
Gladly I made a copy from my hole previous .json file...
Is somebody so kind to help me out?
Maybe even @SeydX ?
Thank you guys so much!

**Comment by MrWGT** [comment]
I've you've used plugin version < 5 before you've to rewrite the plugin settings.

The simple way would be uninstall plugin, restart homebridge, install again and setup the fritz platform config from scratch. 

I've made it that way using the templates from github and inserting the AINs from my old config.json.

**Comment by ManuNewbie** [comment]
> If you've used plugin version < 5 before you've to rewrite the plugin settings.
> 
> The simple way would be uninstall plugin, restart homebridge, install again and setup the fritz platform config from scratch.
> 
> I've made it that way using the templates from github and inserting the AINs from my old config.json.

ok, exactly the starting from scratch was something I would have preferred not having to do....
Especially I cannot find "templates" in the order of HOOBS - which I already use, because it should be even easier as doing the hole programming...
And in that, there are different Fields now, to put in a configuration - when I start from scratch, in these fields are brackets like this:
[]
and I already dont know, if I have to put the parts of my previous.json file into those brackets, because in the original new example .json from @SeydX they don't exist...
I show you guys some Screenshots

**Comment by ManuNewbie** [comment]
sadly I can't upload screenshots right here and now via drag and drop, because github says "they don't support these type of file" even if I tried .png and .pdf which workedd before - when I try to click the part beneath the line - and through this open my finder - it just shows folder symbols and not the files inside

**Comment by SeydX** [comment]
@ManuNewbie 

just edit your config.json manually with the example-config.json as a template

https://github.com/SeydX/homebridge-fritz-platform/blob/master/example/example-config.json

**Comment by ManuNewbie** [comment]
> @ManuNewbie
> 
> just edit your config.json manually with the example-config.json as a template
> 
> https://github.com/SeydX/homebridge-fritz-platform/blob/master/example/example-config.json

Thanx very much for replying directly @SeydX!!!
Only thing is, that in "HOOBS" it`s not that easy to import a hole .json file, as there are new separate fields to put in the coding.
Were they generated without your knowing???
Because it seems, that this new "blocks" should make it easier to change parts of the .json - for example smarthome parts. but your new example .json seem to work "the old way" as it is just ONE long line of code....
Please see my atteched screen shot, of the hoobs configurator
<img width="419" alt="Bildschirmfoto 2020-12-04 um 20 08 21" src="https://user-images.githubusercontent.com/65829542/101498412-5c234a80-396c-11eb-98c3-ff299ed5de88.png">
