### ISSUE TITLE
Unterstützung für den Telekom Wandtaster möglich?

### ISSUE THREAD

**Issue by Nasuada** [SeydX/homebridge-fritz-platform#148]
Hi,

ich ahbe mir kürzlich den Telekom Wandtaster zugelegt als Angebot für weniger als 10€ das Stück, der via DECT Problemlos an die FritzBox angemeldet werden kann (wie ich vor dem Kauf gelesen habe). Das ging dann auch wirklich problemlos und nun war meine Hoffnung, wenn ich den Taster an die Fritz bekomme, das ich diesen dann auch über dieses Plugin hier das ganze unter Homebridge einbinden kann. 
Dem scheint aber leider nicht so, denn ich finde keine Konfiguration um einen Taster ein zu binden. 

Übersehe ich hier etwas oder ist hier einfach noch keine Lösung vorhanden. Gibt es da evt. eine Möglichkeit das in Zukunft zu ermöglichen? 

Würde mich über eine Rückmeldung freuen und wünsche einen guten Start in das neue Jahr. 

Achja, hier das Gerät: https://www.smarthome.de/geraete/smarthome-wandtaster-weiss

**Comment by SeydX** [comment]
@Nasuada 

Ich habe bereits versucht Taster Allgemein mit einzubinden. Problem hierbei ist, dass wenn auf den Taster gedrückt wird, die API nicht ‚sofort‘ informiert wird. Die Kommunikation findet direkt über die FritzBox statt.

Über die API habe ich lediglich Information darüber WANN zuletzt geklickt wurde. Und basierend auf diese Information die Taster in Apple Home einzubinden finde ich nicht gut.

Evtl. kommt da Seitens AVM später eine Verbesserung. Doch bis dahin werden diese erstmal nicht unterstützt.

lg
