### ISSUE TITLE
Authentification error - DECT Plug

### ISSUE THREAD

**Issue by martinB65** [SeydX/homebridge-fritz-platform#15]
Sometimes i get this error, when i want to switch on / off a DECT Plug (homeApp):

[FritzBox] [ERROR] Ventilator: An error occured by turning off Ventilator
[FritzBox] [ERROR] {
     "response": "OK",
     "responseCode": 200,
     "tr064": "Auth. failed",
     "tr064code": "503",
     "fault": "UPnPError",
     "faultcode": "s:Client",
     "serviceType": "urn:dslforum-org:service:X_AVM-DE_Homeauto:1",
     "action": "SetSwitch"
 }

After toggling several times (3 to 5 times) the error message doesn't occur anymore and everything works fine. After some hours the error occurs again.

FritzBox 7590
Firmware 7.01

Thanks for your support
M.

**Comment by SeydX** [comment]
can u try with v2.8 pls

**Comment by martinB65** [comment]
Thank you. After a quick test: seems to work!
