### ISSUE TITLE
Router Setting Problem 

### ISSUE THREAD

**Issue by Smarthome456SDl** [SeydX/homebridge-fritz-platform#150]
Dear @SeydX,

I´ve got the follow problem. I did everything what I have to do, bevor I  Install the program. But however I change the settings, he gives the information, that I where is no master router.

If I just set "master" from "false" to "true" he didn't accept it. 

So my question is, what do I need to change in the Fritz Settings, that he can see the router as a master and no just only as host.

Maybe its just a little Problem from my side, so it would be great if u could help me.

I already installed some devices from RING and it works. so it seems like where are going some things in the right direction 

[1/10/2021, 4:22:39 PM] [FritzPlatform] Initializing FritzPlatform platform...
[1/10/2021, 4:22:40 PM] [FritzPlatform] WARNING: There is no master router defined! Please check if "master" is enabled and "host" ist set in config.

 "name": "FritzPlatform",
            "devices": [
                {
                    "name": "Mein Fritz",
                    "host": "123.123.123.1",
                    "port": 123455,
                    "username": "Mustermann",
                    "password": "Max",   
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "master": false,
                    "connection": "dsl"
                }
            ],
            "presence": [
                {
                    "ping": false
                }
            ],
            "callmonitor": {
                "active": false,
                "port": 1012
            },
            "extras": {
                "alarm": {
                    "active": false
                },
                "wakeup": {
                    "active": false
                },
                "ringlock": {
                    "active": false
                },
                "phoneBook": {
                    "active": false
                }
            },
            "options": {
                "polling": {
                    "timer": 10
                }
            },
            "telegram": {
                "active": false
            },
            "platform": "FritzPlatform"
        }

**Comment by yourdawi** [comment]
"master": false,

so where is your master defined?
Change it to true, if you only use this fritzbox.
