### ISSUE TITLE
Start WPS Switch

### ISSUE THREAD

**Issue by jeatrexs** [SeydX/homebridge-fritz-platform#152]
**Is your feature request related to a problem? Please describe.**
Is there any possibility to get a switch to activate the WPS paring function of the FritzBox?
I know that there is a possibility for a switch to enable / disable WPS, but i could not find any configuration for that.

**Describe the solution you'd like**
It would be great, if there would be a config setting to get a switch to activate the WPS function, to connect a device via WPS with the WiFi of the FritzBox.

Thanks in advance :)

**Comment by SeydX** [comment]
You can set in device options `"wps": "switch"`

https://github.com/SeydX/homebridge-fritz-platform/blob/57c533b7fe8bc4d7e977dbb0e186a8ac4f132d74/example/example-config.json#L36
