### ISSUE TITLE
FRITZ!DECT 200 does report null value for temperature

### ISSUE THREAD

**Issue by heikobischoff** [SeydX/homebridge-fritz-platform#153]
**Describe the bug**
I added my FRITZ!DECT 200 plug to the Homebridge config. I can control it, but it does not report the temperature value. In Homebridge and finally Homekit I can see the temperature stated as 0°C. 

In the FRITZ!App, the temperature is reported correctly.

**Expected behavior**
The measured temperature value is pulled by the module and reported to Homebridge.

**Screenshots**
![Screenshot 2021-01-28 at 19 46 47](https://user-images.githubusercontent.com/34372415/106187876-82b07580-61a6-11eb-93c5-4480ae90c30a.png)
![Screenshot 2021-01-28 at 19 47 21](https://user-images.githubusercontent.com/34372415/106187892-85ab6600-61a6-11eb-9397-a1e5fe3ab696.png)
![IMG_F98C77858DE6-1](https://user-images.githubusercontent.com/34372415/106188193-f0f53800-61a6-11eb-8445-3f87b5a8957c.jpeg)

**Debug logs**
"3D Drucker" is the name of my plug.

[28/01/2021, 20:12:38] [FritzPlatform] 3D Drucker: Polling state (smarthome-switch)...
[28/01/2021, 20:12:38] [FritzPlatform] 3D Drucker: {"name":"3D Drucker","id":"16","ain":"xxxxxxx","online":1,"bitmask":"35456","busy":0,"battery":false,"alert":false,"temperature":false,"humidity":false,"powermeter":{"voltage":235.626,"power":23.96,"energy":535.724},"switch":{"state":1},"button":false,"thermostat":false,"light":false}
[28/01/2021, 20:12:38] [FritzPlatform] 3D Drucker Temperature: Polling state (smarthome-temperature)...
[28/01/2021, 20:12:38] [FritzPlatform] 3D Drucker Temperature: {"name":"3D Drucker","id":"16","ain":"xxxxxxxx","online":1,"bitmask":"35456","busy":0,"battery":false,"alert":false,"temperature":false,"humidity":false,"powermeter":{"voltage":235.626,"power":23.96,"energy":535.724},"switch":{"state":1},"button":false,"thermostat":false,"light":false}

**Config file**
        {
            "name": "FritzPlatform",
            "debug": true,
            "devices": [
                {
                    "name": "FRITZ!Box 7490",
                    "host": "fritz.box",
                    "username": "xxxxxxx",
                    "password": "xxxxxxx",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "master": true,
                    "connection": "repeater"
                }
            ],
            "presence": [
                {
                    "ping": false
                }
            ],
            "smarthome": [
                {
                    "name": "3D Drucker",
                    "ain": "08761 0264470",
                    "group": false,
                    "energy": true,
                    "temperature": true,
                    "accType": "switch"
                },
            ],
            "callmonitor": {
                "active": false,
                "port": 1012
            },
            "extras": {
                "alarm": {
                    "active": false
                },
                "wakeup": {
                    "active": false
                },
                "ringlock": {
                    "active": false
                },
                "phoneBook": {
                    "active": false
                }
            },
            "options": {
                "polling": {
                    "timer": 10
                }
            },
            "telegram": {
                "active": false
            },
            "platform": "FritzPlatform"
        }
    ]
}

**Comment by SeydX** [comment]
Sry for the late response, i ve looked into this. 

It seems that the API doesnt give any temp values back. 

can u try with a different AIN pls. Something like 

"```087610264470-1"``` or without empty space like "```087610264470```"

**Comment by Norbert-Witowski** [comment]
Hello, same issues with Fritz!Dect 210. AIN modifications were not effective.

**Comment by SeydX** [comment]
@Norbert-Witowski @heikobischoff 

can u enable debug pls and post your log

There must be a line starting with „ SmartHome Devices: ..“ in the log

**Comment by heikobischoff** [comment]
@SeydX Unfortunately I don't have the device anymore. 
@Norbert-Witowski Can you help?

**Comment by Norbert-Witowski** [comment]
Hello, as I do not have the FRITZ!DECT 200, I cannot help. My FRITZ!DECT 210 works reliably. Regards, Norbert!
