### ISSUE TITLE
Broadband just show 0,0

### ISSUE THREAD

**Issue by meistermolli** [SeydX/homebridge-fritz-platform#154]
**Describe the bug**
Broadband shows just Download / Upload 0,0 in Eve App

Homebridge Fritz Platform v5.0.20 / v5.0.21 / v5.0.22
Plugin Settings
Device "Master Device"
 - Options
 - Broadband - Characteristic   (not None)

**To Reproduce**
1. Go to Eve App
2. Click on Rooms / Fritz!Box Status (ON/OFF)
3. Scroll down to Download / Upload
4. See Status 0,0

**Smartphone (please complete the following information):**
iPhone v14.4
HomePod Mini Steuerzentrale v14.4
eve app v5.0.1
Homebridge v1.1.7 / v1.3.1 
Fritz!Box 7590 v7.21 / v7.25

**Comment by shinzan111** [comment]
Hello … same issue here but not "Download, Upload 0/0" it measured once a value 108 / 41,5 at the beginning and than it always keeps the same values. 
Could you please provide feedback or work on an update?
thx

**Comment by SeydX** [comment]
@meistermolli 

i have the same device and same OS version and it works. Only my homebridge version is the newest one.

@shinzan111 

Which device/OS?

**Comment by meistermolli** [comment]
Since yesterday newest homebridge Version doesnt work already. @SeydX is there any cache or something i can delete?

**Comment by SeydX** [comment]
can u try v5.0.22 pls

**Comment by meistermolli** [comment]
Leider 0,0

![7F3C10E6-EA98-48CB-BBEB-98421AEF6D91](https://user-images.githubusercontent.com/55836556/109397622-e067e700-7937-11eb-83cc-cfdd420c5614.jpeg)

**Comment by monza258** [comment]
Same by me. 

![image](https://user-images.githubusercontent.com/37027557/109398389-0348ca00-793d-11eb-99f4-b42021f870d7.jpeg)

**Comment by SeydX** [comment]
v5.0.23 is out, can u try again pls with "debug" enabled pls

if it shows "undefined", pls post your log here

**Comment by SeydX** [comment]
it should be fixed in v5.0.24

**Comment by meistermolli** [comment]
@SeydX yes Thank you.

v5.0.24 is Running Upload/Download.

👍
