### ISSUE TITLE
No characteristics found in Apple Home App

### ISSUE THREAD

**Issue by paffi05** [SeydX/homebridge-fritz-platform#155]
Hi,

I don't find any characteristics in my apple home, but they are enabled. I'm using a FritzBox 6490 Cable and FW 7.12.

`{
            "name": "FritzPlatform",
            "devices": [
                {
                    "name": "FritzBox",
                    "host": "192.168.178.1",
                    "username": "XXX",
                    "password": "xxx",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "manufacturer": "AVM",
                    "model": "Fritz!Box 6490 cable",
                    "oldFW": true,
                    "master": true,
                    "readOnly": false,
                    "hide": false,
                    "connection": "cable",
                    "options": {
                        "wifi_2ghz": "characteristic",
                        "wifi_5ghz": "characteristic",
                        "wifi_guest": "switch",
                        "wps": "switch",
                        "aw": "switch",
                        "broadband": "characteristic"
                    }
                }
            ],
            "presence": [
                {
                    "active": true,
                    "blockTelegram": true,
                    "name": "XXX",
                    "address": "xxx",
                    "accType": "occupancy",
                    "ping": true,
                    "threshold": 1
                }
            ],
            "callmonitor": {
                "active": true,
                "port": 1012,
                "countryPrefix": "+49",
                "cityPrefix": "08191"
            },
            "extras": {
                "alarm": {
                    "active": false
                },
                "wakeup": {
                    "active": false
                },
                "ringlock": {
                    "active": false
                },
                "phoneBook": {
                    "active": false
                }
            },
            "options": {
                "polling": {
                    "timer": 10
                }
            },
            "telegram": {
                "active": false
            },
            "platform": "FritzPlatform"
        }`

any ideas?
PS: I'm totally new to this Homebridge thing so please explain it like I'm five! 
Many thanks

**Comment by SeydX** [comment]
@paffi05 

"Characteristics" are only shown in third party apps like Elgatove Eve etc.
