### ISSUE TITLE
Error at installing the plugin

### ISSUE THREAD

**Issue by MasterofKungfu9999** [SeydX/homebridge-fritz-platform#158]
Hi,

get an error if i want to install the plugin:

ERR! notarget No matching version found for homebridge-fritz-platform@5.0.21.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
26.2.2021, 12:40:49 - 
26.2.2021, 12:40:49 - npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-02-26T11_40_49_152Z-debug.log

Here ist the log:

0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '--prefer-offline',
0 verbose cli   '--no-audit',
0 verbose cli   '--unsafe-perm',
0 verbose cli   '--progress=true',
0 verbose cli   'homebridge-fritz-platform@5.0.21'
0 verbose cli ]
1 info using npm@7.6.0
2 info using node@v14.15.5
3 timing config:load:defaults Completed in 4ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 3ms
5 timing config:load:builtin Completed in 4ms
6 timing config:load:cli Completed in 6ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/hoobs/.hoobs/.npmrc Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/home/hoobs/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 2ms
13 timing config:load:global Completed in 2ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 2ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 24ms
19 verbose npm-session 96238d5ded1aed04
20 timing npm:load Completed in 42ms
21 timing arborist:ctor Completed in 2ms
22 timing idealTree:init Completed in 446ms
23 timing idealTree:userRequests Completed in 6ms
24 silly idealTree buildDeps
25 silly fetch manifest homebridge-fritz-platform@5.0.21
26 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
27 http fetch GET 200 https://registry.npmjs.org/homebridge-fritz-platform 52ms (from cache)
28 silly placeDep ROOT homebridge-fritz-platform@ OK for: @hoobs/hoobs@3.3.2 want: 5.0.21
29 timing idealTree:#root Completed in 76ms
30 timing idealTree:node_modules/homebridge-fritz-platform Completed in 0ms
31 timing idealTree:buildDeps Completed in 79ms
32 timing idealTree:fixDepFlags Completed in 9ms
33 timing idealTree Completed in 544ms
34 timing command:install Completed in 558ms
35 verbose type version
36 verbose stack homebridge-fritz-platform: No matching version found for homebridge-fritz-platform@5.0.21.
36 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:207:23)
36 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:26
36 verbose stack     at async Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:888:19)
36 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:836:11)
36 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
36 verbose stack     at async Promise.all (index 1)
36 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:130:5)
36 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:38:3)
37 verbose cwd /home/hoobs/.hoobs
38 verbose Linux 4.19.75-v7l+
39 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--prefer-offline" "--no-audit" "--unsafe-perm" "--progress=true" "homebridge-fritz-platform@5.0.21"
40 verbose node v14.15.5
41 verbose npm  v7.6.0
42 error code ETARGET
43 error notarget No matching version found for homebridge-fritz-platform@5.0.21.
44 error notarget In most cases you or one of your dependencies are requesting
44 error notarget a package version that doesn't exist.
45 verbose exit 1

Thanks foryour help

**Comment by SeydX** [comment]
Can u try v5.0.22

it seems that its related to hoobs

**Comment by MasterofKungfu9999** [comment]
I've tried but it didn't work so i opened an issue @hoobs

**Comment by MasterofKungfu9999** [comment]
@SeydX im using node version 	14.15.5 and homebridge version 1.1.7. Is some of this wrong and causes this error?

**Comment by MasterofKungfu9999** [comment]
Updating to hoobs 3.3.3 brings noch improvement

**Comment by SeydX** [comment]
@MasterofKungfu9999 

Funktioniert es jetzt?

**Comment by MasterofKungfu9999** [comment]
Nein, leider nicht

**Comment by mkellsy** [comment]
You may need to refresh the packages.
```
cd ~/.hoobs
rm -fR node_modules
npm install
```

**Comment by MasterofKungfu9999** [comment]
@mkellsy 

It didn't work it's the same error

Here is what i have done:

"hoobs@hoobs:~ $ cd ~/.hoobs
hoobs@hoobs:~/.hoobs $ rm -fR node_modules
hoobs@hoobs:~/.hoobs $ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'homebridge-hue@0.12.23',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     BSB001: '1.16.0',
npm WARN EBADENGINE     BSB002: '1.42.0',
npm WARN EBADENGINE     deCONZ: '2.9.3',
npm WARN EBADENGINE     homebridge: '^1.1.0',
npm WARN EBADENGINE     node: '^14.16.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v14.15.5', npm: '7.6.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'homebridge-lib@5.0.10',
npm WARN EBADENGINE   required: { homebridge: '^1.1.0', node: '^14.16.0' },
npm WARN EBADENGINE   current: { node: 'v14.15.5', npm: '7.6.0' }
npm WARN EBADENGINE }

added 231 packages, and audited 232 packages in 1m

40 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (2 low, 8 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details."

After that i restarted hoobs, but it's the same error

**Comment by MasterofKungfu9999** [comment]
Here is the debug-log:

0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '--prefer-offline',
0 verbose cli   '--no-audit',
0 verbose cli   '--unsafe-perm',
0 verbose cli   '--progress=true',
0 verbose cli   'homebridge-fritz-platform@5.0.25'
0 verbose cli ]
1 info using npm@7.6.0
2 info using node@v14.15.5
3 timing config:load:defaults Completed in 4ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 3ms
5 timing config:load:builtin Completed in 3ms
6 timing config:load:cli Completed in 7ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/home/hoobs/.hoobs/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/hoobs/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 3ms
13 timing config:load:global Completed in 3ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 2ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 25ms
19 verbose npm-session f12d51c5c4c5c672
20 timing npm:load Completed in 45ms
21 timing arborist:ctor Completed in 2ms
22 timing idealTree:init Completed in 456ms
23 timing idealTree:userRequests Completed in 6ms
24 silly idealTree buildDeps
25 silly fetch manifest homebridge-fritz-platform@5.0.25
26 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
27 http fetch GET 200 https://registry.npmjs.org/homebridge-fritz-platform 394ms (from cache)
28 silly placeDep ROOT homebridge-fritz-platform@ OK for: @hoobs/hoobs@3.3.3 want: 5.0.25
29 timing idealTree:#root Completed in 418ms
30 timing idealTree:node_modules/homebridge-fritz-platform Completed in 0ms
31 timing idealTree:buildDeps Completed in 421ms
32 timing idealTree:fixDepFlags Completed in 10ms
33 timing idealTree Completed in 896ms
34 timing command:install Completed in 911ms
35 verbose type version
36 verbose stack homebridge-fritz-platform: No matching version found for homebridge-fritz-platform@5.0.25.
36 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:207:23)
36 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:26
36 verbose stack     at async Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:888:19)
36 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:836:11)
36 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
36 verbose stack     at async Promise.all (index 1)
36 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:130:5)
36 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:38:3)
37 verbose cwd /home/hoobs/.hoobs
38 verbose Linux 4.19.75-v7l+
39 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--prefer-offline" "--no-audit" "--unsafe-perm" "--progress=true" "homebridge-fritz-platform@5.0.25"
40 verbose node v14.15.5
41 verbose npm  v7.6.0
42 error code ETARGET
43 error notarget No matching version found for homebridge-fritz-platform@5.0.25.
44 error notarget In most cases you or one of your dependencies are requesting
44 error notarget a package version that doesn't exist.
45 verbose exit 1

**Comment by SeydX** [comment]
Closing this issue. 

https://github.com/hoobs-org/HOOBS/issues/1110
