### ISSUE TITLE
FritzDect 210‘s temperature report incorrect

### ISSUE THREAD

**Issue by Norbert-Witowski** [SeydX/homebridge-fritz-platform#159]
Instead of real temperature, 0 degree is displayed by homebridge-fritz-platform v5.0.23. FritzDect 210 v. 04.17, FritzBox 7590 v. : 07.25 04.17

**Comment by SeydX** [comment]
@Norbert-Witowski 

already reported here https://github.com/SeydX/homebridge-fritz-platform/issues/153

can u enable debug pls and post your log

There must be a line starting with „ SmartHome Devices: ..“ in the log

**Comment by Norbert-Witowski** [comment]
Solved: Username was added to configuration which is required by new FritzOS 07.25. 
FritzDect 210‘s temperature report is correct.
