### ISSUE TITLE
phoneBook not working ?!

### ISSUE THREAD

**Issue by pitleh** [SeydX/homebridge-fritz-platform#16]
Hi SeydX,

It seems that the phonebook data is not stored or not being used.
What is it I am doing wrong? 
Please help.

I have correctly activated the "phoneBook": true,
Also the CallMonitor is activated combinded with Telegram, which is working fine.

Incoming call! 012345678 ( No name )
Incoming call - 012345678 ( No name ) - was disconnected!

Thank you,
Pit

**Comment by SeydX** [comment]
It depends on how the data (phone number) is stored and how the phone number is showing on the display.

I.e if a phone number is stored with (+49) and the number which is calling shows only (0) it will be not displayed via telegram

For Germany (+49) i added a function to fix this, but not for other countries

**Comment by pitleh** [comment]
Hi SeydX,

I checked this on my end, in my Fritzbox phonebock the number was stored without the +49.
btw. I live in Germany.
I supect that the phonebock has not been transfered to the Homebridge server. 
Since I don't know how to do this.

Any advise would be very welcome.

Thank you,
Pit

**Comment by SeydX** [comment]
Hey,

Im currently working on v3 and this should be fixed in v3

I have implemented a new function only to solve this issue ^^

**Comment by pitleh** [comment]
Thank you for the heads up. 
Looking forward for the new version.

**Comment by SeydX** [comment]
Should be fixed with v3
