### ISSUE TITLE
Bandwidth of dsl connection not working

### ISSUE THREAD

**Issue by shinzan111** [SeydX/homebridge-fritz-platform#161]
Hello, 

as I have seen you reworked somehow the DSL bandwidth connection feature, I still have to spot
that in my configuration it still does not work. 

Once the bandwidth has been written it does not change it afterwards. Event not after several days.

Could you please rework that again?

Here is my config-File snipped:
I have a FritzBox 7590 as main and a 7530 as a repeater:

{
            "name": "FritzPlatform",
            "devices": [
                {
                    "name": "FritzBox 7590",
                    "host": "xxx.xxx.xxx.xxx",
                    "port": 49000,
                    "username": "XXXXXXX",
                    "password": "xxxxxxxxxxxx",
                    "manufacturer": "Fritz Box",
                    "model": "7590",
                    "ssl": true,
                    "tr064": true,
                    "igd": true,
                    "master": true,
                    "readOnly": false,
                    "hide": false,
                    "connection": "dsl",
                    "options": {
                        "wifi_2ghz": "switch",
                        "wifi_5ghz": "switch",
                        "wifi_guest": "switch",
                        "wps": "switch",
                        "dect": "switch",
                        "aw": "switch",
                        "deflection": "switch",
                        "led": "switch",
                        "lock": "switch",
                        "broadband": "characteristic"
                    }
                },
                {
                    "name": "FritzBox 7530",
                    "host": "xxx.xxx.xxx.xxx",
                    "port": 49000,
                    "username": "XXXXXXXXXX",
                    "password": "XXXXXXXX",
                    "manufacturer": "Fritz Box",
                    "model": "7530",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "master": false,
                    "readOnly": false,
                    "connection": "repeater",
                    "options": {
                        "wifi_2ghz": "switch",
                        "wifi_5ghz": "switch",
                        "wifi_guest": "characteristic",
                        "led": "switch",
                        "lock": "characteristic"
                    }
                }
            ],
            "presence": [
                {
                    "active": true,
                    "blockTelegram": false,
                    "name": "XXXXX",
                    "address": "XXXXXXXX.…",
                    "accType": "motion",
                    "ping": true,
                    "threshold": 5
                },
                {
                    "active": true,
                    "blockTelegram": false,
                    "name": "XXXXX",
                    "address": "xxxxx",
                    "accType": "motion",
                    "ping": true,
                    "threshold": 4
                }
            ],
            "callmonitor": {
                "active": true,
                "ip": "xxxx.xxx.xxx.xxx",
                "port": 1012,
                "countryPrefix": "00xxx",
                "cityPrefix": "xxxxx",
                "incomingTo": [
                    "123456"
                ],
                "outgoingFrom": [
                    "123456"
                ]
            },
            "extras": {
                "alarm": {
                    "active": true,
                    "telNr": "XXXXX…",
                    "accType": "switch"
                },
                "wakeup": {
                    "active": false
                },
                "ringlock": {
                    "active": true,
                    "DECTphones": 6,
                    "start": "XX.XX",
                    "end": "XX.XX",
                    "accType": "switch"
                },
                "phoneBook": {
                    "active": false
                }
            },
            "options": {
                "presence": {
                    "anyone": true,
                    "accType": "motion"
                },
                "reboot": {
                    "on": "",
                    "off": ""
                },
                "polling": {
                    "timer": 10
                }
            },
            "telegram": {
                "active": true,
                "token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX…",
                "chatID": "XXXXXXXXXX",
                "messages": {
                    "callmonitor": {
                        "incoming": "Incoming call - @",
                        "outgoing": "Outgoing call - @",
                        "disconnected": "Call with @ disconnected"
                    },
                    "reboot": {
                        "start": "reboot started",
                        "finish": "reboot completed"
                    }
                }
            },
            "platform": "FritzPlatform"
        },

**Comment by SeydX** [comment]
@shinzan111 

Broadband is not a real measurement. It only shows the dsl speed shown also on the fritz GUI
