### ISSUE TITLE
Thermostat as HeaterCooler

### ISSUE THREAD

**Issue by SeydX** [SeydX/homebridge-fritz-platform#163]

**Comment by SeydX** [comment]
Added in v5.0.30

**Comment by ucsbricks** [comment]
There are two things I would like to comment on this "enhancement". 

First: What exactly is the advantage? Maybe I did not find it so far…

Second: Installing this update broke my extremely complex heating automations. As changing the service type forced HomeKit to recognize all thermostats as new device, all automations and scenes got useless and need to be fixed! I would highly appreciate if this was mentioned as a WARNING in the release notes. Restoring the broken settings will cost me an hour or more…

**Comment by SeydX** [comment]
@ucsbricks 

I'm sorry. You're right about that. I made the change because Fritz thermostats do not have different modes, only on/off.

I will add the warning in the changelog/release

**Comment by ucsbricks** [comment]
Thanks @SeydX

Unfortunately there is some more: It is no longer possible to set temperature in Home+ app now. 

Please consider to revert the enhancement as it renders the plugin useless for some.

**Comment by SeydX** [comment]
@ucsbricks 

can u explain why u can not adjust the temperature? I checked that and i have no issues on setting a new temperature

**Comment by ucsbricks** [comment]
There is no option shown for that. I can only see three options when I want to setup
the device in a scene: on/off, mode, threshold.

**Comment by SeydX** [comment]
@ucsbricks 

can u send a screenshot pls

**Comment by ucsbricks** [comment]
I am sorry, but no. I installed the previous release of your plugin on my Homebridge instance some minutes ago.

**Comment by SeydX** [comment]
@ucsbricks 

aight. The threshold u see in the app (Heating Threshold Temperature) is the target temperature for "Heater Cooler" Accessories

https://developers.homebridge.io/#/characteristic/HeatingThresholdTemperature

**Comment by ucsbricks** [comment]
OK. But the doc says 25 is max value for threshold. FRITZ thermostats have a max of 28. This would limit their usage.

**Comment by SeydX** [comment]
I have changed the maxValue

https://github.com/SeydX/homebridge-fritz-platform/blob/master/src/accessories/smarthome/thermostat.js#L91

**Comment by svenf01** [comment]
In my case the new heater show every time as state "heating". The old was showing correctly heating or cooling.
Heating was when wished temperature was lower then current. Cooling when wished temp was higher then current. It was easy to see be the read or blue color if temperature is reached. Actual it show permanent red and heating. That is a step back.

**Comment by SeydX** [comment]
@svenf01 

will be available with next version again

**Comment by SeydX** [comment]
"cooling" state added again in v5.0.31
