### ISSUE TITLE
Negative Temperatur bei Fritz DECT 301

### ISSUE THREAD

**Issue by Raspberry-Kay** [SeydX/homebridge-fritz-platform#164]
Hallo, seit dem Update auf Version 5.0.31 (vorherige Version war 5.0.20) lässt sich eine geringere Temperatur nicht mehr einstellen. Höhere Temperaturen und das Ein und Ausschalten funktioniert weiterhin. Mit Version 5.0.20 funktioniert alles problemlos. 

Will man eine niedrigere Temperatur einstellen, kommt in Homebridge lediglich folgende Meldung: 
[FritzBox] Wohnzimmer: ON (smarthome-thermostat)

**Comment by ucsbricks** [comment]
@SeydX could this probably be related to changing the device type from thermostat to heater/cooler (https://github.com/SeydX/homebridge-fritz-platform/issues/163)? @Raspberry-Kay describes that since he updated from 5.0.20 to 5.0.31 turning the thermostat on/off is still possible as well as increasing the temperature, but decreasing is not supported any more. If he tries to decrease the temperature, Homebridge outputs the log message cited above. 

@Raspberry-Kay ich war mal so frei den Sachverhalt zu übersetzen. Mit dem Update auf Version 5.0.30 wurde der Gerätetyp von Thermostat auf Klimaanlage geändert. Bei mir kam es dadurch auch zu einigen Problemen, weshalb ich im oben verlinkten Ticket bereits einen Bugreport anhängte.

**Comment by SeydX** [comment]
Hey, ich schaue mir das mal an.

**Comment by SeydX** [comment]
v5.0.32 ist online

**Comment by Raspberry-Kay** [comment]
Der Fehler besteht leider weiterhin.

**Comment by maciboy** [comment]
Ich habe einen weiteren Fehler mit dem Dect 301, würde vermuten seit deiner Änderung des Typs und wurde durch den Bugfix .32 auch nicht behoben:
Siri kann keine Temperatur mehr einstellen!
Sie sagt zwar, dass sie die Temperatur von X Grad auf Y Grad ändert, aber das wird nicht ausgeführt, im Log steht nur:
26.3.2021, 21:58:45 [FritzPlatform] Heizung Wohnzimmer: ON (smarthome-thermostat)
26.3.2021, 21:58:45 [FritzPlatform] Heizung Esszimmer: ON (smarthome-thermostat)
26.3.2021, 22:55:16 [FritzPlatform] Heizung Wohnzimmer: ON (smarthome-thermostat)
26.3.2021, 22:55:17 [FritzPlatform] Heizung Esszimmer: ON (smarthome-thermostat)
26.3.2021, 22:55:17 [FritzPlatform] Heizung Schlafzimmer: ON (smarthome-thermostat)
26.3.2021, 22:57:41 [FritzPlatform] Heizung Wohnzimmer: ON (smarthome-thermostat)
26.3.2021, 22:57:41 [FritzPlatform] Heizung Schlafzimmer: ON (smarthome-thermostat)
26.3.2021, 22:57:42 [FritzPlatform] Heizung Esszimmer: ON (smarthome-thermostat)
26.3.2021, 22:58:36 [FritzPlatform] Heizung Wohnzimmer: ON (smarthome-thermostat)

Wenn man während des Sprachkommandos die Home App offen hat, sieht man auch wie die Ziel-Temperatur sich kurzzeitig ändert, dann aber wieder auf den vorherigen Wert zurück springt. Ändert man es per Hand in der Home App, wird die Änderung übernommen und auch im Log angezeigt:
26.3.2021, 23:06:45 [FritzPlatform] Heizung Wohnzimmer: Setting temperature to 23.5 (smarthome-thermostat)

da ich die Temperatur meistens über den HomePod einstelle, wäre es sehr gut wenn das auch funktionieren würde.
Danke

**Comment by maciboy** [comment]
@SeydX hast du den Bug noch auf dem Schirm?
Können wir dich noch mit Infos unterstützen?
Danke dir :)

**Comment by teelander** [comment]
@SeydX mir ist noch aufgefallen, dass es über SIRI klappt, wenn man die Temperatur um z.B. 5 Grad reduziert.  Interessanterweise stellt er dann aber z.B. von 20 Grad auf 15,5 Grad. Vielleicht hilft das ja bei der Fehleranalyse.

**Comment by SeydX** [comment]
Should be fixed with v5.0.33

**Comment by teelander** [comment]
Just installed v5.0.33.
Same problem. Setting the temperature to a lower value does not work via Siri.
Even worse, now reducing the temperature by e.g. 5 degrees doesn't work either.

Console just says:
Name-of-Thermostat: ON (smarthome-thermostat)

Increasing the temperature and switching works like a charm. Setting directly in the home app works great too.

**Comment by SeydX** [comment]
@teelander 

Hm, strange… For me, both decrease and increase the temperature with Siri or HomeKit directly works without problems.

**Comment by teelander** [comment]
Thanks for the quick response.
After a reboot it works here as well.
Excellent work. :-)
