### ISSUE TITLE
Question to Repeator Setting

### ISSUE THREAD

**Issue by ash123-germany** [SeydX/homebridge-fritz-platform#165]
I have a repeator in the room of my sun.
The only think what i want to do there via homebridge is to switch onn/off the LED
What i have to set in config.json ?

in moment i set following:

        "name": "David-Repeator",
        "host": "192.168.XXXXXX",
        "port": 49000,
        "username": "XXXXXX",
        "password": "XXXXXX",
        "ssl": true,
        "tr064": true,
        "igd": false,
        "manufacturer": "FritzBox",
        "model": "Repeater",
        "serialNumber": "123456",
        "readOnly": false,
        "oldFW": true,
        "connection": "repeater",
        "hide": false,
        "options": {
            "led": "switch"

Homebrigde show me now 2 switches one for Power on/off the Repeator (which i do not want to  have)
And one for the LED which doesn't work ;-(

**Comment by SeydX** [comment]
@ash123-germany 

which repeater?

Tried with ``"oldFW": false`` ?

**Comment by ash123-germany** [comment]
Hi SeydX,
it works with oldFW  thanks.

But still i cannot disable the switch for Repeater , its a 2400.
greatings 
arnd
