### ISSUE TITLE
Child protection switch for hosts

### ISSUE THREAD

**Issue by fade2metal** [SeydX/homebridge-fritz-platform#168]
Dear @SeydX,

is there any possibility to get switches for single hosts to switch them to unlimited internet access or never internet access?

I thought about adding the hosts MAC adresses to the config to be able to switch them to local or internet access. Is that possible?

Could you add this to your very nice plugin?

**Comment by Hadea4711** [comment]
Hi, 

this enhancement would be wonderful! Switching off the devices / profiles of my kids in homebridge with just one click.

All parents will be thankful for that extension!

KR

**Comment by fade2metal** [comment]
Maybe this could help: https://community.openhab.org/t/disable-internet-connection-of-specific-echo-device-on-fritz-box-via-script/91374

With that Script It works perfectly to switch a specific profile to unlimited or never.

**Comment by Hadea4711** [comment]
Does it work also with homebridge? 

Which plugin do I have to install? 

Thanks for supporting me with this difficult "children-online-time" topic.

**Comment by fade2metal** [comment]
It would be so nice to have it integrated into homebridge-fritz-platform. It was meant as a helping script for the development process of fritz-platform.

You could use it with https://www.npmjs.com/package/homebridge-script2, but I would only use it as temporary solution.
For using it with script2 you'd have to use your own scripts:

For switching on:

`#!/bin/sh
ip='yourfritzip
username='username
password='password'
filtprof="yourprofilenumber"

challenge=$(curl -s "http://${ip}/login_sid.lua?username=$username" | grep -Po '(?<=<Challenge>).*?(?=</Challenge>)')
md5=$(echo -n ${challenge}"-"${password} | iconv -f ISO8859-1 -t UTF-16LE | md5sum -b | awk '{print substr($0,1,32)}') 
response="${challenge}-${md5}"
sid=$(curl -i -s -k -d "response=${response}&username=${username}" "http://${ip}" | grep -Po -m 1 '(?<=sid=)[a-f\d]+' | tail -1)

curl -d "sid=${sid}&edit=filtprof${filtprof}&time=unlimited&budget=unlimited&apply=&page=kids_profileedit" "http://${ip}/data.lua" >/dev/null 2>&1

echo "echo true" > state.sh`

For switching off:  

`#!/bin/sh
ip='yourfritzip
username='username
password='password'
filtprof="yourprofilenumber"

challenge=$(curl -s "http://${ip}/login_sid.lua?username=$username" | grep -Po '(?<=<Challenge>).*?(?=</Challenge>)')
md5=$(echo -n ${challenge}"-"${password} | iconv -f ISO8859-1 -t UTF-16LE | md5sum -b | awk '{print substr($0,1,32)}') 
response="${challenge}-${md5}"
sid=$(curl -i -s -k -d "response=${response}&username=${username}" "http://${ip}" | grep -Po -m 1 '(?<=sid=)[a-f\d]+' | tail -1)

curl -d "sid=${sid}&edit=filtprof${filtprof}&time=never&budget=unlimited&apply=&page=kids_profileedit" "http://${ip}/data.lua" >/dev/null 2>&1

echo "echo false" > state.sh`

and the state.sh script creates itself with true or false for state but it doesn't recognizes if you change the state in the ui of the FritzBox.

**Comment by Hadea4711** [comment]
Hi, what is the meaning of "yourprofilenumber" --> Profile Name like "kids"? I can't see any numbers for a profile.

**Comment by fade2metal** [comment]
https://community.openhab.org/t/disable-internet-connection-of-specific-echo-device-on-fritz-box-via-script/91374

There you'll find instructions for finding the profile number.

**Comment by fade2metal** [comment]
Dear @SeydX,
I saw in the docs of AVM that it should be possible to allow/disallow host specific WAN access by ip address via TR-064:
https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/x_hostfilterSCPD.pdf

Could you add this to homebridge-fritz-platform?

**Comment by SeydX** [comment]
Added in v6.0.0-beta.17

**Comment by SeydX** [comment]
Closing this issue since it was included in the beta (see last comment) and to keep track of which feature requests are still open.

**Comment by SeydX** [comment]
https://github.com/SeydX/homebridge-fritz-platform/issues/191
