### ISSUE TITLE
Disabling/enabling WiFi Guest does not work with Fritz!Repeater 3000

### ISSUE THREAD

**Issue by Rusty-Shacklef0rd** [SeydX/homebridge-fritz-platform#169]
Disabling/enabling WiFi Guest does not work with Fritz!Repeater 3000. Instead the second 5GHz Unit is toggled.

**Comment by SeydX** [comment]
@Rusty-Shacklef0rd 

can u try the latest version pls

**Comment by Rusty-Shacklef0rd** [comment]
@SeydX 

v5.1.0? there was no difference at all. do i have to add the 3000 in a specific way for the plugin to recognise it?

**Comment by SeydX** [comment]
@Rusty-Shacklef0rd 

No its the same. I released a new beta version. Can u try it pls?

``sudo npm i -g homebridge-fritz-platform@beta``

Note: Dont worry, you can always switch back to the latest version with

``sudo npm i -g homebridge-fritz-platform``

**Comment by Rusty-Shacklef0rd** [comment]
@SeydX thanks for your work but nothing has changed, the guest wifi is still controlling the second 5ghz unit.

**Comment by SeydX** [comment]
Wait a minute. Does your router habe multiple 5ghz units?

**Comment by Rusty-Shacklef0rd** [comment]
@SeydX it's a repeater and yes it does. both the Repeater 3000 and the Repeater 6000 have two 5GHz units, one is meant as a dedicated uplink to a Fritzbox.
<img width="438" alt="Screenshot 2021-06-05 at 08 01 16" src="https://user-images.githubusercontent.com/81234093/120881870-79ac3680-c5d4-11eb-8ef0-5defd3623a3c.png">

**Comment by SeydX** [comment]
Interesting. The plugin can not handle this atm. Will try to support it with the next release

**Comment by Rusty-Shacklef0rd** [comment]
no worries. thank you for your work!

**Comment by SeydX** [comment]
For the next release im planing to add a new option called `availableWifiUnits` to config which allows to manually set the available wifi units.

eg if your router/repeater supports 

- only 2,4GHZ => `1`
- 2,4GHZ and 5GHZ => `2`
- 2,4Ghz, 2x 5Ghz => `3`
- etc

(Default would be `2`)

This will allow to support dynamically each router/repeater with multiple wifi units

**Comment by SeydX** [comment]
Added/Fixed in v6.0.0-beta.17

**Comment by SeydX** [comment]
Closing this issue since it was included in the beta (see last comment) and to keep track of which feature requests are still open.

**Comment by SeydX** [comment]
https://github.com/SeydX/homebridge-fritz-platform/issues/191

**Comment by genfersee** [comment]
Working great with Repeater 6000 !

**Comment by Rusty-Shacklef0rd** [comment]
> Working great with Repeater 6000 !

same with my 3000. many thanks to @SeydX for his good work!
