### ISSUE TITLE
Too many motion sensor notifications

### ISSUE THREAD

**Issue by florian-muc** [SeydX/homebridge-fritz-platform#17]
Thanks for that plug-in, really nice work :)

**Describe the bug**
When running a HomeKit app and logging notifications, I see that the motion sensor that is installed as part of the presence function emits a motion detected notification once per second. I think this is not a good idea for the overall fidelity of a HomeKit installation, as HomeKit can't really deal well with too high traffic.

**To Reproduce**
Configure the presence feature with at least one device. I used a delay of 10, but that doesn't make a difference.

**Expected behavior**
See characteristic notifications in HomeKit when the state of the motion sensor changes, not on a regular interval, particularly not so often.

**Comment by SeydX** [comment]
V3 is out, presence now only as occupancy sensor and without fakegato
