### ISSUE TITLE
Callmonitor Incoming filter

### ISSUE THREAD

**Issue by mese16** [SeydX/homebridge-fritz-platform#171]
Hi Seyd

Nice Plugin, i really like it. 

1. It would be really nice to filter the incoming Phonenumbers, so the callmonitor reacts only to this specific Number. 
2. If a Number is blocked or the answering machine is on, the callmonitor status will not be closed again.

Regards Mese

**Comment by SeydX** [comment]
Added/Fixed in v6.0.0-beta.17

**Comment by SeydX** [comment]
Closing this issue since it was included in the beta (see last comment) and to keep track of which feature requests are still open. If the issue still exists, feel free to re-open

**Comment by SeydX** [comment]
https://github.com/SeydX/homebridge-fritz-platform/issues/191
