### ISSUE TITLE
Button for reconnecting internet connection to aquire a new ip address

### ISSUE THREAD

**Issue by Ms-Sudo** [SeydX/homebridge-fritz-platform#174]
In my fritz box menu there is a button which I can click to reconnect my internet connection. I use this to get a new ip address from my ISP. It is much quicker than restarting the entire fritz box and only takes a few seconds.

It would be great if this button could be integrated into the plugin as a feature.

My menu is in German, so I hope my translation fits your settings:
In the fritz box menu: Internet -> Onlinemonitor (1st entry) -> Button "reconnect" (on the right side just below the graphs).

At the moment I am using the program mFritzMon on my PC to reconnect. It also shows upload/download in MBit/s, connection time, current ip address and graphs for upload/download. It would be great if those items could be implemented into homekit as well, but I am not sure if homekit allows such information to be displayed.

Thank you.

**Comment by SeydX** [comment]
Added in v6.0.0-beta.17

**Comment by SeydX** [comment]
Closing this issue since it was included in the beta (see last comment) and to keep track of which feature requests are still open.

**Comment by SeydX** [comment]
https://github.com/SeydX/homebridge-fritz-platform/issues/191
