### ISSUE TITLE
Device seems to be offline 

### ISSUE THREAD

**Issue by pbanane** [SeydX/homebridge-fritz-platform#175]
**Describe the bug**
I tried to add my 7530 FritzBox and 3000 Repeater to the homebrige (fresh installation from an image today). 
The message in the status log of the homebrige is always "Device seems to be offline".
I tried different settings but it does not change. I see a successfull login in my fritzbox log from the Homebridge IP.

Port for "Diagnose und Wartung" on my FB is 47309 (Anbieter-Dienste (TR-069). 

Homebridge Version: v1.3.4
homebridge-fritz-platform v5.0.32

FritzOS 7.25 (i know it is not yet on your supported OS list, maybe this is already the issue...)
Network settings set as described in your prerequisites documentation.

I tried also to change the "IGD" Feature but also with no positive effect.

**Config**
"name": "FritzBox-App",
            "debug": true,
            "devices": [
                {
                    "name": "FritzBox 7530",
                    "host": "192.168.177.1",
                    "port": 47309,
                    "username": "xxx",
                    "password": "xxx",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "manufacturer": "AVM",
                    "model": "FritzBox 7530",
                    "master": true,
                    "connection": "cable",
                    "options": {
                        "wifi_5ghz": "characteristic",
                        "wifi_guest": "characteristic"
                    }
                },
                {
                    "name": "FritzRepeater 3000",
                    "host": "192.168.177.8",
                    "port": 47309,
                    "username": "xxx",
                    "password": "xxx",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "manufacturer": "AVM",
                    "model": "Fritz Repeater 3000",
                    "master": false,
                    "connection": "repeater",
                    "options": {
                        "wifi_2ghz": "switch",
                        "wifi_5ghz": "switch"
                    }

**Additional context**
[13/04/2021, 16:59:34] [FritzBox-App] FritzBox 7530: Polling state (router)...
[13/04/2021, 16:59:34] [FritzBox-App] FritzBox 7530: Device seems to be offline (router)
[13/04/2021, 16:59:34] [FritzBox-App] FritzRepeater 3000: Polling state (router)...
[13/04/2021, 16:59:34] [FritzBox-App] FritzRepeater 3000: Device seems to be offline (router)
[13/04/2021, 16:59:34] [FritzBox-App] FritzRepeater 3000 Wifi 2ghz: Polling state (wifi_2ghz)...
[13/04/2021, 16:59:34] [FritzBox-App] FritzRepeater 3000 Wifi 2ghz: Device seems to be offline (wifi_2ghz)
[13/04/2021, 16:59:34] [FritzBox-App] FritzRepeater 3000 Wifi 5ghz: Polling state (wifi_5ghz)...
[13/04/2021, 16:59:34] [FritzBox-App] FritzRepeater 3000 Wifi 5ghz: Device seems to be offline (wifi_5ghz)

**Comment by bezibaerchen** [comment]
I can confirm I'm seeing that issue as well. I do agree the assumption regarding FritzOS Version. I'm on a 6490 Cable and issue started occuring with 7.25 on the box.

**Comment by SeydX** [comment]
Can u try with a different fritzbox user pls ( create a new one with required permission and add it to config.json)

**Comment by bezibaerchen** [comment]
> Can u try with a different fritzbox user pls ( create a new one with required permission and add it to config.json)

Gave that a try with a completely new user and added to config.json

Unfortunately still same behaviour.

**Comment by bezibaerchen** [comment]
Anything else we can provide / test to help to get this sorted? It would be really cool to get this functional again.

**Comment by bezibaerchen** [comment]
Update from my end:

I just updated the 6490 to latest "Labor" from today (07.25-88295 BETA) and Plugin seems to work again from what I can say

**Comment by bezibaerchen** [comment]
Update: Without changing anything it stopped working again. Will try to analyze further

**Comment by SeydX** [comment]
Never had an issue like this after an update.

``Device seems to be offline`` means that the plugin can not access the device (could be due to wrong credentials, no permission, no tr064 enabled etc) and/or its offline.

The newest version of FritzBox has some breaking changes in the backend. I recommend everyone to add a new user with username AND password.

**Comment by bezibaerchen** [comment]
> Never had an issue like this after an update.
> 
> `Device seems to be offline` means that the plugin can not access the device (could be due to wrong credentials, no permission, no tr064 enabled etc) and/or its offline.
> 
> The newest version of FritzBox has some breaking changes in the backend. I recommend everyone to add a new user with username AND password.

Tried that as stated above: No luck

**Comment by SeydX** [comment]
@bezibaerchen 

can u post your config.json pls

**Comment by bezibaerchen** [comment]
@SeydX 

That should be relevant excerpts, let me know if you need something else:

`platforms": [
        {
            "name": "FritzPlatform",
            "debug": false,
            "devices": [
                {
                    "name": "FRITZ!Box 6490 Cable",
                    "host": "xxx.xxx.xxx.xxx",
                    "port": 49000,
                    "username": "<newly created>",
                    "password": "<password>",
                    "ssl": true,
                    "tr064": true,
                    "igd": true,
                    "manufacturer": "Fritz Box",
                    "model": "6490",
                    "serialNumber": "12345",
                    "master": true,
                    "readOnly": false,
                    "hide": false,
                    "connection": "cable",
                    "options": {
                        "wifi_2ghz": "switch",
                        "wifi_5ghz": "switch",
                        "wifi_guest": "switch",
                        "wps": "characteristic",
                        "dect": "switch",
                        "aw": "characteristic",
                        "led": "switch",
                        "lock": "switch"
                    }
                },
                {
                    "name": "repeater1750",
                    "host": "xxx.xxx.xxx.xxx",
                    "port": 49000,
                    "username": "<user>",
                    "password": "<password>",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "manufacturer": "FritzBox",
                    "model": "Repeater",
                    "serialNumber": "123456",
                    "oldFW": true,
                    "master": false,
                    "readOnly": false,
                    "hide": false,
                    "connection": "repeater",
                    "options": {
                        "led": "characteristic",
                        "lock": "characteristic"
                    }
                },
                {
                    "name": "repeater3000",
                    "host": "xxx.xxx.xxx.xxx",
                    "port": 49000,
                    "username": "<user>",
                    "password": "<password>",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "manufacturer": "FritzBox",
                    "model": "Repeater",
                    "serialNumber": "123456",
                    "oldFW": true,
                    "master": false,
                    "readOnly": false,
                    "hide": false,
                    "connection": "repeater",
                    "options": {
                        "led": "characteristic",
                        "lock": "characteristic"
                    }
                }`

**Comment by SeydX** [comment]
@bezibaerchen 

try with ``"igd": false`` pls for your router

**Comment by bezibaerchen** [comment]
> @bezibaerchen
> 
> try with `"igd": false` pls for your router

That slightly improved: Presence seems to work again. However:

[5/17/2021, 8:50:54 AM] [FritzPlatform] FRITZ!Box 6490 Cable Wifi guest: Device seems to be offline (wifi_guest)
[5/17/2021, 8:50:54 AM] [FritzPlatform] FRITZ!Box 6490 Cable Dect: Device seems to be offline (dect)
[5/17/2021, 8:50:54 AM] [FritzPlatform] FRITZ!Box 6490 Cable Led: Device seems to be offline (led)
[5/17/2021, 8:50:58 AM] [FritzPlatform] FRITZ!Box 6490 Cable Wifi guest: Device seems to be offline (wifi_guest)
[5/17/2021, 8:50:58 AM] [FritzPlatform] FRITZ!Box 6490 Cable Dect: Device seems to be offline (dect)
[5/17/2021, 8:50:58 AM] [FritzPlatform] FRITZ!Box 6490 Cable Led: Device seems to be offline (led)
[5/17/2021, 8:50:58 AM] [FritzPlatform] FRITZ!Box 6490 Cable Wifi 2ghz: Device seems to be offline (wifi_2ghz)
[5/17/2021, 8:50:58 AM] [FritzPlatform] FRITZ!Box 6490 Cable: Device seems to be offline (aw)
[5/17/2021, 8:51:06 AM] [FritzPlatform] FRITZ!Box 6490 Cable Wifi guest: Device seems to be offline (wifi_guest)
[5/17/2021, 8:51:06 AM] [FritzPlatform] FRITZ!Box 6490 Cable Wifi 5ghz: Device seems to be offline (wifi_5ghz)
[5/17/2021, 8:51:12 AM] [FritzPlatform] FRITZ!Box 6490 Cable: Device seems to be offline (wps)
[5/17/2021, 8:51:12 AM] [FritzPlatform] FRITZ!Box 6490 Cable: Device seems to be offline (aw)
[5/17/2021, 8:51:12 AM] [FritzPlatform] FRITZ!Box 6490 Cable Wifi 2ghz: Device seems to be offline (wifi_2ghz)
[5/17/2021, 8:51:12 AM] [FritzPlatform] FRITZ!Box 6490 Cable Wifi 5ghz: Device seems to be offline (wifi_5ghz)
[5/17/2021, 8:51:12 AM] [FritzPlatform] FRITZ!Box 6490 Cable Wifi guest: Device seems to be offline (wifi_guest)
[5/17/2021, 8:51:12 AM] [FritzPlatform] FRITZ!Box 6490 Cable Dect: Device seems to be offline (dect)
[5/17/2021, 8:51:16 AM] [FritzPlatform] FRITZ!Box 6490 Cable Dect: Device seems to be offline (dect)
[5/17/2021, 8:51:16 AM] [FritzPlatform] FRITZ!Box 6490 Cable Led: Device seems to be offline (led)
[5/17/2021, 8:51:18 AM] [FritzPlatform] FRITZ!Box 6490 Cable Wifi 2ghz: Device seems to be offline (wifi_2ghz)
[5/17/2021, 8:51:18 AM] [FritzPlatform] FRITZ!Box 6490 Cable Dect: Device seems to be offline (dect)
[5/17/2021, 8:51:19 AM] [FritzPlatform] FRITZ!Box 6490 Cable Wifi guest: Device seems to be offline (wifi_guest)
[5/17/2021, 8:51:19 AM] [FritzPlatform] FRITZ!Box 6490 Cable Dect: Device seems to be offline (dect)
[5/17/2021, 8:51:19 AM] [FritzPlatform] FRITZ!Box 6490 Cable Led: Device seems to be offline (led)
[5/17/2021, 8:51:19 AM] [FritzPlatform] FRITZ!Box 6490 Cable Lock: Device seems to be offline (lock)
[5/17/2021, 8:51:22 AM] [FritzPlatform] FRITZ!Box 6490 Cable Led: Device seems to be offline (led)
[5/17/2021, 8:51:22 AM] [FritzPlatform] FRITZ!Box 6490 Cable Dect: Device seems to be offline (dect)

**Comment by SeydX** [comment]
Restarting the router may help. The best way is to restart the router, when everything is online, restart Homebridge, see if it works.

If not, set ssl to false for your router and restart Homebridge and see if it works again.

**Comment by bezibaerchen** [comment]
Update: All switches currently online. Restarted router. SSL currently true, igd remaining at "false". What's that for?

**Comment by SeydX** [comment]
IGD stands for Internet Gateway Device and is needed for some endpoints. But unfortunately these endpoints are not implemented in the homebridge-fritz-platform and therefore it is not needed and can be set to ``false`` in the configuration.

If IGD is ``true``, the plugin tries to fetch the data through IGD, even if its not supported by the device. And this can cause the error.

Did restarting the router help? Or why are the switches online now?

**Comment by bezibaerchen** [comment]
Thanks for this explanation. Yepp, as stated above, router restarted. Let's see how long it remains stable.

**Comment by bezibaerchen** [comment]
Update: ~ 24 hours later: All failing again.

**Comment by bezibaerchen** [comment]
Another router and Homebridge restart brought things back to life. This wasn't neccessary before.

**Comment by bezibaerchen** [comment]
Still occuring after updating to new plugin version. Only a router restart helps to solve.

**Comment by SeydX** [comment]
@bezibaerchen 

Does it work normally after a restart? Or will the error come back at some point?

**Comment by bezibaerchen** [comment]
@SeydX As stated above. It works for some time then error comes back.

**Comment by SeydX** [comment]
You have a cable router, i assume its connected to an another router?

**Comment by bezibaerchen** [comment]
Nope, only router. Fritzbox 6490

**Comment by bezibaerchen** [comment]
So I did a little bit more investigation. No solution, but good evidence that it isn't down to the plugin itself.
What I discovered:

As a reboot solves it, I wanted to establish a scheduled reboot via curl from another host via TR064.
This did *not* work, Curl ran into a timeout.
I found that TR064 can be more or less checked via:

http://fritz.box:49000/tr64desc.xml

Didn't load. I manually rebooted the box and guess what? Reboot via curl worked and URL above shows content / is connectable.

So I am getting the suspicion that $something brakes TR064 after some time, not only for homebridge-fritz-platzform but also on a general basis.

Unfortunately I don't have an idea as of how to fix that. All I can say that this obviously came with one of the last FW versions.

I'd really appreciate if someone finds some more insights and hope it helps.

Let me know if you need anything more.

**Comment by SeydX** [comment]
@bezibaerchen 

Version 6 Beta is online. The code has been completely refactored (backward compatible).

Idk if it fix your issue, but it could be worth to try it?

https://github.com/SeydX/homebridge-fritz-platform/issues/173#issuecomment-861316024

**Comment by SeydX** [comment]
> I just installed 7.27 final. I will monitor the situation and feed back if this solves it

Version 6 is online
