### ISSUE TITLE
FRITZ!Box 7590 mit FRITZ!OS: 07.25 - Geräte werden in HomeKit nicht mehr angezeigt

### ISSUE THREAD

**Issue by Hertt226** [SeydX/homebridge-fritz-platform#176]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lugaetsch** [comment]
ob Absicht oder nicht - ich denke hier benötigen wir schon mehr Informationen hinsichtlich des bereits angefertigten Protokolls zur Beschreibung des Anliegens...
