### ISSUE TITLE
Outlet Wattage not available

### ISSUE THREAD

**Issue by rainbowcat1989** [SeydX/homebridge-fritz-platform#179]
Hey,

just want to report a Bug that i can not see my Outlet Wattage or Temperature.

![image](https://user-images.githubusercontent.com/64091338/115853285-4d27cb00-a429-11eb-96f8-edd13d11c6c4.png)

I can see that the Datas are pulled. 

![image](https://user-images.githubusercontent.com/64091338/115853191-31242980-a429-11eb-964f-6d232f904cac.png)

These are the Settings

![image](https://user-images.githubusercontent.com/64091338/115853407-70eb1100-a429-11eb-9ee7-6d4115dbd407.png)

The Outlet appears as a Switch in Apple Home

Thanks for the help 

greetings

**Comment by SeydX** [comment]
@rainbowcat1989 

tried to change "accType" to `outlet`?

**Comment by rainbowcat1989** [comment]
@SeydX 

After changing this in the JSON-File the Device disappear 

LOG:


   "smarthome": [
        {
            "name": "Solaranlage",
            "ain": "08761 00xxxxx",
            "readOnly": true,
            "group": false,
            "energy": true,
            "temperature": true,
            "humidity": false,
            "accTypeGroup": "outlet",
            "accType": "outlet"
        }
    ],



[5/2/2021, 5:40:21 PM] [FritzPlatform] Solaranlage: There is no or no valid type configured for this smarthome device. This device will be skipped.
[5/2/2021, 5:40:21 PM] [FritzPlatform] One of the user has no name configured. This user will be skipped.
[5/2/2021, 5:40:21 PM] [FritzPlatform] No or wrong accessory type setted up for this user. Setting it to "occupancy".

**Comment by SeydX** [comment]
> @SeydX
> 
> After changing this in the JSON-File the Device disappear
> 
> LOG:
> 
> "smarthome": [
> {
> "name": "Solaranlage",
> "ain": "08761 00xxxxx",
> "readOnly": true,
> "group": false,
> "energy": true,
> "temperature": true,
> "humidity": false,
> "accTypeGroup": "outlet",
> "accType": "outlet"
> }
> ],
> 
> [5/2/2021, 5:40:21 PM] [FritzPlatform] Solaranlage: There is no or no valid type configured for this smarthome device. This device will be skipped.
> [5/2/2021, 5:40:21 PM] [FritzPlatform] One of the user has no name configured. This user will be skipped.
> [5/2/2021, 5:40:21 PM] [FritzPlatform] No or wrong accessory type setted up for this user. Setting it to "occupancy".

ah sry my bad, the first config was ok.

The temperature sensor should be exposed as a separate sensor in HomeKit. and the energy usage is only visible with 3rd party apps like Elgato EVE. Had you already checked that?
