### ISSUE TITLE
Fritz!Dect 301 Window open, missing trigger (support)

### ISSUE THREAD

**Issue by luedi0** [SeydX/homebridge-fritz-platform#182]
**Is your feature request related to a problem? Please describe.**

Since the thermostats are not particularly good at detecting open windows, I am looking for a manual trigger through a window contact. So far, this plugin only shows the state (sensor). 

**Describe the solution you'd like**

Expose the "Window Open" sensor state also as a switch

**Describe alternatives you've considered**

Other methods of disabling heating in the meantime cause errors when re-enabling or while schedules intersect with down-time

Additional context

Best regards,
Max

**Comment by luedi0** [comment]
Passende Bindings könnte man von hier nehmen.
[https://community.openhab.org/t/avm-fritz-binding-does-not-recognize-radiator-mode-window-open/70265/11](url)

**Comment by SeydX** [comment]
Added in v6.0.0-beta.17

**Comment by SeydX** [comment]
Closing this issue since it was included in the beta (see last comment) and to keep track of which feature requests are still open.

**Comment by SeydX** [comment]
https://github.com/SeydX/homebridge-fritz-platform/issues/191
