### ISSUE TITLE
Multiple Fritzboxes

### ISSUE THREAD

**Issue by ksteff4711** [SeydX/homebridge-fritz-platform#185]
Hello. Thanks for the great Plugin.
I have two fritzboxes with different smarthome devices. Is it possible to do a configuration with this?
At the moment it causes an error:
[FritzPlatform] {"ain":"130770032780","cmd":"setsimpleonoff&onoff=0","status":400,"text":"Bad Request","message":"Bad Request"}

Help will be much appreciated
Thanks
Steff

**Comment by SeydX** [comment]
Hey its currently not possible to control multiple „master“ devices

https://github.com/SeydX/homebridge-fritz-platform/issues/183
