### ISSUE TITLE
An error occurred during polling

### ISSUE THREAD

**Issue by dirkhusemann** [SeydX/homebridge-fritz-platform#187]
**Describe the bug**

After installing and configuring homebridge-fritz-platform on a HOOBS device I'm getting a constant stream of "an error occurred during polling" log statements.

**To Reproduce**
Installed fritz platform 5.1.2 on on HOOBS device 3.3.5, configured for local Fritz!Box 7590 (FRITZ!OS: 07.25).

**Expected behavior**

No polling errors.

**Log file**

attached.
[logs.txt](https://github.com/SeydX/homebridge-fritz-platform/files/6569816/logs.txt)

**Comment by SeydX** [comment]
@dirkhusemann 

can u enable debug in your config pls and restart homebridge and post the whole log again

**Comment by masterbug** [comment]
To me it behaves the same. 
i was using a User/Pwd created extra for homebridge usage but this seams not to work at the moment.
When I change back to the default admin user and password it is fine.

**Comment by SeydX** [comment]
@masterbug 

so its a credentials issue?

**Comment by dirkhusemann** [comment]
@SeydX enabled debug in the config. Pretty much the same result.
[logs-2.txt](https://github.com/SeydX/homebridge-fritz-platform/files/6599825/logs-2.txt)

I doubt that it's a credentials issue: I did add a separate user --- and successfully tested that with https://github.com/jhubig/FritzBoxShell.

**Comment by SeydX** [comment]
@dirkhusemann 

according to the log, you dont have enabled debug in your config for fritzbox

**Comment by dirkhusemann** [comment]
well:
 ```
       {
            "platform": "FritzPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-fritz-platform"
            },
            "name": "FritzPlatform",
            "devices": [
                {
                    "name": "FritzBox 7590",
                    "host": "192.168.1.1",
                    "port": 49000,
                    "username": "XXXX",
                    "password": "XXXXXXXXX",
                    "manufacturer": "Fritz Box",
                    "model": "7590",
                    "serialNumber": "XXXXXXXXXX",
                    "master": true,
                    "ssl": true,
                    "tr064": true,
                    "igd": true,
                    "readOnly": false,
                    "hide": true,
                    "connection": "cable",
                    "options": {
                        "wifi_2ghz": "switch",
                        "wifi_5ghz": "switch",
                        "wifi_guest": "switch",
                        "wps": "characteristic",
                        "aw": "characteristic",
                        "deflection": "switch",
                        "led": "switch",
                        "lock": "switch",
                        "dect": "switch",
                        "broadband": "characteristic"
                    }
                }
            ],
            "callmonitor": {
                "active": false,
                "port": 1012,
                "ip": "192.168.8.1"
            },
            "extras": {
                "alarm": {
                    "active": false
                },
                "wakeup": {
                    "active": false
                },
                "ringlock": {
                    "active": false
                },
                "phoneBook": {
                    "active": false
                }
            },
            "options": {
                "polling": {
                    "timer": 10
                }
            },
            "telegram": {
                "active": false
            },
            "debug": true
        }
```
which I enabled through the UI on HOOBS:
<img width="323" alt="Screenshot 2021-06-04 at 22 03 28" src="https://user-images.githubusercontent.com/48989/120856908-c6662200-c580-11eb-927b-b9d6a33d2509.png">

If there's another way, let me know.

**Comment by SeydX** [comment]
@dirkhusemann 

Have you restarted the service to apply the changes?

**Comment by dirkhusemann** [comment]
Actually, just realised the error: the IP address was wrong! Working now! Apologies!
