### ISSUE TITLE
Status of FB is not showing any states

### ISSUE THREAD

**Issue by shinzan111** [SeydX/homebridge-fritz-platform#188]
Since I while I am facing some issues with the FB platform plugin. 

1. the DSL connection (download/upload numbers) always shows same numbers which cannot be true
2. since last update the plugin even does not show the status of the FB (on-off, wifi, dsl, a.o.)

Why is this happening?

**Comment by SeydX** [comment]
@shinzan111 

1. these numbers only show your maximum dsl speed and is not a real time measurement
2. Any error in the log?
