### ISSUE TITLE
Telegram always shows Unknown for outgoing calls

### ISSUE THREAD

**Issue by BigKrisch** [SeydX/homebridge-fritz-platform#19]
Hey SeydX,

with me with outgoing calls in the Telegram message always only "Unknown" indicated. In the logfile, however, the number is displayed. Do you have to add another entry in the config? With incoming calls everything works perfectly.

Is it also possible that the name is displayed in the phone book even with outgoing calls? As with incoming phone calls.

Thank you for your help!

**Comment by SeydX** [comment]
Hello, i will check the outgoing calls, but to display the name, the phone number you are calling must be the same as in the phonebook to show the name, otherwise the plugin wil show "unknown"

**Comment by osahner** [comment]
Wouldn't it be obvious to show the phone number instead?

**Comment by SeydX** [comment]
Normally the plugin shows always the phone number if its detects, it will show ‚Unknown‘ ONLY if no number detected on incomming call

**Comment by BigKrisch** [comment]
Unfortunately not. The outgoing telephone number is displayed in the log file. In Telegram but always "Unknown" is issued.

![Bildschirmfoto 2019-03-16 um 07 54 46](https://user-images.githubusercontent.com/35509005/54471987-cde35a00-47c1-11e9-8660-bcceb41901b6.png)

![Bildschirmfoto 2019-03-16 um 07 56 17](https://user-images.githubusercontent.com/35509005/54471989-d50a6800-47c1-11e9-918d-2e4ac4563a70.png)

**Comment by BigKrisch** [comment]
Unfortunately not. The outgoing telephone number is displayed in the log file. Telegram always outputs "Unknown".

Enclosed the log file and the telegram message:

![Bildschirmfoto 2019-03-16 um 07 54 46](https://user-images.githubusercontent.com/35509005/54472037-5eba3580-47c2-11e9-93a0-ce360d8036b9.png)

![Bildschirmfoto 2019-03-16 um 07 56 17](https://user-images.githubusercontent.com/35509005/54472040-624dbc80-47c2-11e9-8ce1-ea2d80a53d9b.png)

**Comment by SeydX** [comment]
Should be fixed in v3.0.6

**Comment by BigKrisch** [comment]
Perfect! Works flawlessly! Thank you for your help!!

**Comment by abbanatic** [comment]
Hi @BigKrisch,

how did you enable the telegram notification for outgoing calls? I didn't find the right option in the documentation. I thought only incoming call notifications were supported?

Thanks,
Thomas
