### ISSUE TITLE
Call Monitor Sensor not shown - FRITZ!Box 6591

### ISSUE THREAD

**Issue by Marcusg562** [SeydX/homebridge-fritz-platform#190]
**Describe the bug**
The Call Monitor Sensos will ot appear in the Home App as well as I can't see them in the Homebridge Config UI

**To Reproduce**
Enable the call monitor

**Expected behavior**
No sensor shown

**Screenshots**
![image](https://user-images.githubusercontent.com/105149/122197897-ef4bb880-ce98-11eb-89d9-13f11637d167.png)
Username & password removed for security reason

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro MAX
 - OS:  iOS 14.6

**Additional context**
I also tried to use the call monitor without country-&cityPrefix without success. Call monito was enabled by `#96*5*`

**Comment by SeydX** [comment]
@Marcusg562 

can u enable debug in config.json `"debug": true` and post the log after restarting homebridge

**Comment by Marcusg562** [comment]
I‘ve enabled debug but where can I find the log?

**Comment by SeydX** [comment]
Are you using homebridge-config-ui-x ? If yes, just open the interface and there you should be able to see the log or the console.

If you use it as a service (without homebridge-config-ui-x) then you can open the log with the following command

`sudo journalctl -f -u homebridge`

**Comment by Marcusg562** [comment]
Thanks a lot for this hint :) Yes I‘m using homebridge-config-ui-x and the issue was that the IP of the FRITZ!Box was not set in the CallMonitor Part. Perhaps you can fix this in the new version ;)

**Comment by SeydX** [comment]
> Thanks a lot for this hint :) Yes I‘m using homebridge-config-ui-x and the issue was that the IP of the FRITZ!Box was not set in the CallMonitor Part. Perhaps you can fix this in the new version ;)

This is intended and not a bug because some people have a different ip for the callmonitor :)

**Comment by Marcusg562** [comment]
> > Thanks a lot for this hint :) Yes I‘m using homebridge-config-ui-x and the issue was that the IP of the FRITZ!Box was not set in the CallMonitor Part. Perhaps you can fix this in the new version ;)
> 
> This is intended and not a bug because some people have a different ip for the callmonitor :)


Then it would be nice to be able to configure this in the homebridge-config-ui-x as well ;)
