### ISSUE TITLE
FritzPlatform - Version 6 Beta

### ISSUE THREAD

**Issue by SeydX** [SeydX/homebridge-fritz-platform#191]
This update is by far the biggest update for `homebridge-fritz-platform`. To make adding new devices also easier for developers, the complete plugin has been rewritten and made modular. This should give all developers the possibility to read the code more easily and add new devices via PR themselves.

## Installation
`sudo npm i -g homebridge-fritz-platform@beta`

_Updated: 2021-06-20 (Beta 39)_

## Example config.json
[example-config.txt (updated: 2020-06-20)](https://github.com/SeydX/homebridge-fritz-platform/files/6682535/example-config.txt)

## Breaking Changes
- **Homebridge**
  - Dropped support for homebridge below version 1.3.0
- **Devices**: 
  - Added `active` key to `devices` to enable/disable the device without removing it from config. Warning: Default value for `active` is false, this means, that if you DON'T adjust your config.json and add `"active": true` to the device, the device will be removed from HomeKit!
- **Smarthome**: 
  - Added `active` key to `smarthome` to enable/disable the device without removing it from config. Warning: Default value for `active` is false, this means, that if you DON'T adjust your config.json and add `"active": true` to the device, the device will be removed from HomeKit!
- **WOL**: 
  - Added `active` key to `wol` to enable/disable the device without removing it from config. Warning: Default value for `active` is false, this means, that if you DON'T adjust your config.json and add `"active": true` to the device, the device will be removed from HomeKit!
- **Network Monitoring**: 
  - Added `active` key to `network` to enable/disable the device without removing it from config. Warning: Default value for `active` is false, this means, that if you DON'T adjust your config.json and add `"active": true` to the device, the plugin will not notify you if the device is online/offline!

## Notable Changes
- **Child Lock**:
  - Added new `childLock` array into config to expose child lock switches for given device. Child Lock switches grants/denies acces to the internet for the given ip addresses.
- **Devices**: 
  - Added a new option `wifiUnits` to devices to manually set the available wifi units (support for multiple units like 1x 2.4Ghz and 2x 5Ghz)
  - Added a new option `reconnect` to device options to expose a Reconnect characteristic/switch which interrupt the internet access and reconnect (for changing external ip)
- **Smarthome**:
  - Blinds: Added `blind` as a new accessory (`accType`) type
  - Buttons: Added `button` as a new accessory (`accType`) type with 1/4 button support with oen polling timer (`timerSmarthomeButtons`) configurable under `options.polling.timerSmarthomeButtons`
  - Thermostat:
    - Added new `openWindow` option to expose an switch to manually trigger open/close window
  - Outlet:
    - Added new `startValue` option which is used for notification via telegram when device started (current power consumption above this value) or ended (current power consumption below this value)
- **Extras**:
  - Added new `dnsServer` option to `extras` config to expose a switch which toggles the dns server from fritzbox to "internet provider" or "own dns server"
  - Added new `fallbackInternet` option to `extras` config to expose a switch which toggles the fallback internet option from fritzbox
- **Presence**: 
  - Moved `onDelay` and `offDelay` from options.presence to presence user to allow separate values for each user
- **Callmonitor**:
  - Added `incomingFrom` array into callmonitor options to allow trigger callmonitor only for speicifc numbers
- **Telegram**:
  - Added `outlet.started` and `outlet.finished` as a new option to notify via Telegram if device is started/finished
- **Options**: 
  - Removed `onDelay` and `offDelay` from options.presence
  - Added `timerSmarthomeButtons` to options.polling
- **Polling**: 
  - Refactored `exclude` list. Now, only following type of accessories/characteristics can be excluded from polling: `dsl` (accessory name), `cable` (accessory name), `repeater` (accessory name), `wifi_2ghz`, `wifi_5ghz`, `wifi_guest`, `wps`, `led`, `lock`, `aw`, `dect`, `deflection`, `ringlock`
  - Minimum/Default polling timer (seconds) increased to 15 seconds

## Other Changes
- The code has been refactored (again)
- Adjusted config.schema.json to reflect the changes mentioned above
- Bug fixes
- Updated dependencies

**Comment by ulrgaer** [comment]
using Beta 28, using Wifi Guest switch I get the following error. what is going wrong ?

[17.6.2021, 22:19:11] [FritzPlatform] FritzBox Wifi guest (wifi_guest): An error occured during getting state!
[17.6.2021, 22:19:11] [FritzPlatform] Error: service with id urn:WLANConfiguration-com:serviceId:WLANConfigurationNaN not known
    at Fritzbox.exec (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:130:13)
    at Handler.get (/usr/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:243:28)
    at Handler.poll (/usr/lib/node_modules/homebridge-fritz-platform/src/accessories/extras/extras.handler.js:686:13)

**Comment by SeydX** [comment]
> using Beta 28, using Wifi Guest switch I get the following error. what is going wrong ?
> 
> [17.6.2021, 22:19:11] [FritzPlatform] FritzBox Wifi guest (wifi_guest): An error occured during getting state!
> [17.6.2021, 22:19:11] [FritzPlatform] Error: service with id urn:WLANConfiguration-com:serviceId:WLANConfigurationNaN not known
> at Fritzbox.exec (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:130:13)
> at Handler.get (/usr/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:243:28)
> at Handler.poll (/usr/lib/node_modules/homebridge-fritz-platform/src/accessories/extras/extras.handler.js:686:13)

Oh, its a bug related to wifiunits. Thx i will fix it

**Comment by ulrgaer** [comment]
This defect is as well with other wifi switches.

**Comment by SeydX** [comment]
> This defect is as well with other wifi switches.

can u post your config pls? and which beta version

**Comment by ulrgaer** [comment]
it's beta 28

{
            "name": "FritzPlatform",
            "debug": false,
            "devices": [
                {
                    "active": true,
                    "name": "FritzBox",
                    "host": "192.168.0.1",
                    "username": "test",
                    "password": "xyz",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "wifiUnits": 2,
                    "master": true,
                    "readOnly": true,
                    "hide": true,
                    "connection": "cable",
                    "options": {
                        "wifi_guest": "switch",
                        "led": "switch"
                    }
                }
            ],
            "presence": [
                {
                    "ping": false
                }
            ],
            "smarthome": [
                {
                    "active": true,
                    "name": "Rollo Fenster Aquarium ",
                    "ain": "14276 0503505",
                    "accType": "blind"
                }
            ],
            "callmonitor": {
                "active": false,
                "port": 1012
            },
            "extras": {
                "alarm": {
                    "active": false
                },
                "wakeup": {
                    "active": false
                },
                "ringlock": {
                    "active": false
                },
                "phoneBook": {
                    "active": false
                },
                "dnsServer": {
                    "active": false
                }
            },
            "options": {
                "polling": {
                    "timer": 10
                }
            },
            "telegram": {
                "active": false
            },
            "platform": "FritzPlatform"
        }

**Comment by SeydX** [comment]
> it's beta 28
> 
> {
> "name": "FritzPlatform",
> "debug": false,
> "devices": [
> {
> "active": true,
> "name": "FritzBox",
> "host": "192.168.0.1",
> "username": "test",
> "password": "xyz",
> "ssl": true,
> "tr064": true,
> "igd": false,
> "wifiUnits": 2,
> "master": true,
> "readOnly": true,
> "hide": true,
> "connection": "cable",
> "options": {
> "wifi_guest": "switch",
> "led": "switch"
> }
> }
> ],
> "presence": [
> {
> "ping": false
> }
> ],
> "smarthome": [
> {
> "active": true,
> "name": "Rollo Fenster Aquarium ",
> "ain": "14276 0503505",
> "accType": "blind"
> }
> ],
> "callmonitor": {
> "active": false,
> "port": 1012
> },
> "extras": {
> "alarm": {
> "active": false
> },
> "wakeup": {
> "active": false
> },
> "ringlock": {
> "active": false
> },
> "phoneBook": {
> "active": false
> },
> "dnsServer": {
> "active": false
> }
> },
> "options": {
> "polling": {
> "timer": 10
> }
> },
> "telegram": {
> "active": false
> },
> "platform": "FritzPlatform"
> }

Beta 30 is online, can u try it pls

**Comment by ulrgaer** [comment]
looks good. Tkx. Great job.

**Comment by ulrgaer** [comment]
Hi, this morning I saw the following issue. LED at FRITZ!Box  off. While switching LED on via HomeKit, switch is changing to on. After a while it’s falling back to off. On FRITZ!Box no change at all.

**Comment by SeydX** [comment]
> Hi, this morning I saw the following issue. LED at FRITZ!Box off. While switching LED on via HomeKit, switch is changing to on. After a while it’s falling back to off. On FRITZ!Box no change at all.

Yeah could reproduce it. Fixed in v6.0.0-beta.31 - Thanks! :)

**Comment by ulrgaer** [comment]
Testet v6.0.0-beta 34, led behavior unchanged.

**Comment by SeydX** [comment]
> Testet v6.0.0-beta 34, led behavior unchanged.

Hm, are u sure u restarted gb after update? It fixed on my test environment, beta 36 is online btw

**Comment by ulrgaer** [comment]
> > Testet v6.0.0-beta 34, led behavior unchanged.
> 
> Hm, are u sure u restarted homebridge after update? It fixed on my test environment, beta 36 is online btw

yes, I'm sure, but I will restart the pi

**Comment by SeydX** [comment]
Hmm tried again with 7590 (v7.27), 7430 (v7.21) and Fritz Repeater (v7.13) and it worked as expected without any issues

**Comment by SeydX** [comment]
Maybe install the latest update again, restart homebridge and try again

**Comment by ulrgaer** [comment]
I did it, everything is fine. May I did restart after installation. Sorry for any confusion.

**Comment by SeydX** [comment]
Version 6 is online! Thanks all!
