### ISSUE TITLE
Nach dem Upgrade auf 6.0.1

### ISSUE THREAD

**Issue by BKrnk1337** [SeydX/homebridge-fritz-platform#192]
**Describe the bug**
Nach dem Upgrade auf 6.0.1 kann ich aktuell keine Geräte mehr kontrollieren. Ich habe die Geräte, wie beschrieben, mit active = true versehen (über die Homebridge GUI).

Die Geräte werden in HomeKit angezeigt.

Was mir auffällt ist folgende Meldung im Log:

```
[21/06/2021, 16:05:43] [FritzPlattform] Initializing FritzPlatform platform...
[21/06/2021, 16:05:46] [FritzPlattform] [DEBUG] Telegram successfully configured!
[21/06/2021, 16:05:46] [FritzPlattform] WARNING: There is no master router configured! Please check if "master" is enabled in config.
```

Meine Config sieht jedoch, meines Erachtens nach, gut aus: (IP, Username und Passwort habe ich entfernt) - sonst habe ich keine Änderungen nach dem Upgrade vorgenommen.

```
{
            "name": "FritzPlattform",
            "debug": true,
            "devices": [
                {
                    "name": "FRITZ!Box",
                    "host": "",
                    "port": 49000,
                    "username": "",
                    "password": "",
                    "ssl": false,
                    "tr064": true,
                    "igd": true,
                    "manufacturer": "AVM Computersysteme Vertriebs GmbH",
                    "model": "FRITZ!Box 7490",
                    "serialNumber": "",
                    "wifiUnits": 2,
                    "master": true,
                    "readOnly": true,
                    "hide": false,
                    "connection": "dsl",
                    "options": {
                        "wifi_2ghz": "characteristic",
                        "wifi_5ghz": "characteristic",
                        "wifi_guest": "switch",
                        "wps": "characteristic",
                        "aw": "characteristic",
                        "led": "characteristic",
                        "broadband": "characteristic"
                    }
                }
            ],
```

**Comment by BKrnk1337** [comment]
Ich schließe das Ticket mal - scheinbar muss auch die FritzBox auf "active = True" gesetzt werden.

Verstehe nicht warum true nicht default ist. Aber da wird sich @SeydX bestimmt etwas bei gedacht haben.

**Comment by SeydX** [comment]
Im Changelog habe ich explizit drauf hingewiesen :) 

Ich hatte es anfangs auf true (default), problem war jedoch das es viele Leite gab die ihren config falsch oder nicht ganz ausgefüllt haben, hier würde das Plugin vermehrt warnungen rausgeben (weil standardmäßig active = true) das im config etwas fehlt und so würde es später mehr issues hier geben weil config nicht vollständig ist

**Comment by BKrnk1337** [comment]
Danke für die Antwort :)
