### ISSUE TITLE
Wlan Gastzugang schaltet 5Ghz Wlan an/aus

### ISSUE THREAD

**Issue by brasi93** [SeydX/homebridge-fritz-platform#197]
Möchte ich den Gastzugang ein oder ausschalten, schaltet sich leider bloß das 5 Ghz Wlan an/aus.

Habe das Plugin bereits neu installiert. Ist das Problem bereits bekannt?

**Comment by SeydX** [comment]
@brasi93 

kannst du dein config.json posten bitte? Evtl. hilft es, falls nicht schon gesetzt, "wifiUnits" im config auf 2 zu setzen

**Comment by brasi93** [comment]
werde es im anschluss direkt mit der 2 probieren

      {
            "name": "FritzPlatform",
            "devices": [
                {
                    "active": true,
                    "name": "Obi-Wlan-Knobi",
                    "host": "192.168.192.1",
                    "username": "XXXXXXX",
                    "password": "XXXXXXX",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "wifiUnits": 1,
                    "master": true,
                    "connection": "dsl",
                    "options": {
                        "wifi_guest": "switch",
                        "reconnect": "switch"
                    }
                }
            ],
            "options": {
                "polling": {
                    "timer": 15
                }
            },
            "platform": "FritzPlatform"
        },

**Comment by SeydX** [comment]
"wifiUnits": 1 bedeutet das dein Router nur 1 Unit (also 1x 2.4Ghz hat)

**Comment by brasi93** [comment]
perfekt, das war bereits der Fehler. Vielen Dank.
