### ISSUE TITLE
Powerline WLAN Repeater Support (1260E)

### ISSUE THREAD

**Issue by SmoothMC** [SeydX/homebridge-fritz-platform#2]
**Is your feature request related to a problem? Please describe.**
i add a FRTIZ!Powerline 1260E to the config but it does not work

"FRITZ!Powerline 1260E": {
				"disable": false,
				"ip": "192.168.10.4",
				"port": 49000,
				"username": "pi",
				"password": "********",
				"led": true,
				"wifi": {
					"2.4ghz": true,
					"5ghz": true,
					"guest": false
    				}
    			}

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
her is the error from the homebridge log

[2018-7-12 11:29:24] [FritzBox] [ERROR] FRITZ!Powerline 1260E: An error occured by getting device state!
Jul 12 11:29:24 MiniServer homebridge[7530]: [2018-7-12 11:29:24] [FritzBox] [ERROR] {
Jul 12 11:29:24 MiniServer homebridge[7530]:     "errorCode": "ESOCKETTIMEDOUT",
Jul 12 11:29:24 MiniServer homebridge[7530]:     "serviceType": "urn:dslforum-org:service:WLANConfiguration:1",
Jul 12 11:29:24 MiniServer homebridge[7530]:     "action": "GetInfo",
Jul 12 11:29:24 MiniServer homebridge[7530]:     "device": "FRITZ!Powerline 1260E",
Jul 12 11:29:24 MiniServer homebridge[7530]:     "host": "192.168.10.4"
Jul 12 11:29:24 MiniServer homebridge[7530]: }

**Comment by SeydX** [comment]
should be fixed with latest version
