### ISSUE TITLE
DECT 200 Temperature broken

### ISSUE THREAD

**Issue by sieren** [SeydX/homebridge-fritz-platform#20]
Hey there,

thanks for your work on this!
It seems like in the most recent version DECT200's temperature readings are broken.
The switch itself seems to be working, however temperature readings are a constant 0.0 with no data points in the Fakegato history.

**Comment by sieren** [comment]
Nevermind, I debugged that thing and figured it out, it's worth fixing or at least documenting, but I'm not familiar with the codebase enough myself to do it quickly.

Basically what happened was that I forgot to replace the `ain` on first launch. While a subsequent change of the `ain` propagated to the switch, it was never checked for the temperature accessory (which continued to look for the 0123456.. one).

**Comment by SeydX** [comment]
Yes, that's normal. Fakegato always checks the AIN address entered in the config.json. If this is changed, Fakegato looks for the new address.

It is "checked". But Fakegato has problems with multiple cached data in the accessories folder and it needs several minutes to refresh the data.

To fix this, i recommend to remove the accessory and re-add with correct AIN address
