### ISSUE TITLE
DECT 200 not switching although active

### ISSUE THREAD

**Issue by hanwalt** [SeydX/homebridge-fritz-platform#204]
Hello,
since the update to 6.05 my 2 AVM DECT 200 are not working anymore. I already set them to „active“ in the new preferences.

They still appear in the Home App and Siri says that it executed the switch (on/off) but the DECT 200 is actually not switching.

FritzBox 6591 with 7.27

**Comment by SeydX** [comment]
anything in the log?

**Comment by hanwalt** [comment]
Thanks for the hint. I saw that I needed to set the Device itself to active, too. Not only the Smart Home Accessories.

Because the FritzBox etc. still appeared in the Home App I thought everything was ok.

can be set to closed
