### ISSUE TITLE
No name lookup from incoming call in callmonitor

### ISSUE THREAD

**Issue by tooh** [SeydX/homebridge-fritz-platform#207]
**Describe the bug**
Callmonitor does not do a name lookup from the address book.

**To Reproduce**
1. Create address book entry with two phone numbers
2. Call from the second number
3. Look in log and assert that the incoming call is logged
4. Notice that phone number is visible but the name lookup fails

**Expected behavior**
Correct name lookup even if the person has several phone numbers

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
My hint would be that the lookup fails when the incoming call is not from the first phone book entry

**Comment by SeydX** [comment]
should be fixed in v6.0.16 (beta) - pushig soon

if you want to try it:

`sudo npm i -g homebridge-fritz-platform@beta`

**Comment by SeydX** [comment]
Fixed in v6.0.16

**Comment by tooh** [comment]
Thx

**Comment by SeydX** [comment]
Pls resync the phonebook before withing a 3rd party app like EVE
