### ISSUE TITLE
No data transfer between Fritzbox and homebridge

### ISSUE THREAD

**Issue by Edwin-RM** [SeydX/homebridge-fritz-platform#208]
**Describe the bug**

For about an half year the installation was running normal.
I‘m not using the functions of the homebridge every day.
Now I observed since the update of the plugin to 6.0.10, there is no communication any more between Fritzbox and homebridge for smart home units of AVM.
All other devices from other solutions like Shelly are running normal.

If you are looking into the plugin settings, you think, where are the settings? You can only see and set the settings by the json configuration file. 

On the homebridge protocol, you can see the communication. Shellys and other solutions are transfer data or status, but no data or status of fritz/avm units. 

On Fritzbox, there is the version 7.2.7 running. 
As well, I tried to make the latest updates for the homebridge via ssh. 
As well, I tried older versions of the plugin like 5.12. no help.

**To Reproduce**

This configuration stays on.

**Expected behavior**

Maybe the company AVM has changed the rules for reading and setting data for smart home on the last updates. Since 7.25 you have to have an user name with a password.

**Comment by SeydX** [comment]
There were some minor changes in the config.json in regarding to the devices which u need to adapt to your config.json. And you can also change the settings with config ui x as before.

You need to „ACTIVATE“ the device to take further changes like here eg

https://user-images.githubusercontent.com/34152761/123830935-14faa800-d904-11eb-8ea4-c5fb1b3509aa.MP4

if a device is not activated ("active": true) it will not be exposed to HomeKit and there will be no communication between your device and homebridge/homekit


and please take a look to the example config json and adjust yours and everything will work as normal.

https://github.com/SeydX/homebridge-fritz-platform/blob/master/example/example-config.json

**Comment by Edwin-RM** [comment]
Thank you! 
Now it is working.

I was only trying one of the active switch. There was still no function. 
But after setting all relevant active switch to on, now it is working!

Thank you!
