### ISSUE TITLE
WARNING: There is no master router configured! Please check if "master" is enabled in config.

### ISSUE THREAD

**Issue by CyberChris79** [SeydX/homebridge-fritz-platform#210]
Hi,

i think, this is not really a but, but i get this warning permanently 
**WARNING: There is no master router configured! Please check if "master" is enabled in config.**

I tried to set master to false, but nothing changed.

Thank you

**Comment by CyberChris79** [comment]
I solved this issue, by setting the tag "active": true

Thank you. 

It can be closed

**Comment by messmic** [comment]
Hi, I did get the same message but can't find "the master" to set to active. I didn't even find anything like a master in the config. Can you please explain, how and where did you done this?
Thanks
