### ISSUE TITLE
Child Lock & Reconnect in Favoriten Ansicht

### ISSUE THREAD

**Issue by BKrnk1337** [SeydX/homebridge-fritz-platform#211]
Guten Morgen,

mir fällt auf, dass nach einem Restart der HomeBridge die "Child Locks" und der "Reconnect" immer wieder als Favoriten in der Home App von Apple angezeigt werden.

Bei anderen Geräten (auch in deinem Plugin) passiert das nicht.

Könntest du mir da weiterhelfen?

**Comment by SeydX** [comment]
Hey, ich glaube nicht das das was mit dem Plugin zu tun hat, sondern eher ein Syncing Problem mit deinem Apple Home ist

Plugin Entwickler können nämlich nicht auf die Home „Favoriten“ zugreifen oder diese ändern

Ich hatte das Problem mal früher mit dem Hue Plugin, ging irgendwann von alleine weg

**Comment by BKrnk1337** [comment]
Danke für die Info. Ich gucke mir das Verhalten mal näher an
