### ISSUE TITLE
Fehler nach HOOBS 4 Update

### ISSUE THREAD

**Issue by Raczka1989** [SeydX/homebridge-fritz-platform#212]
**Describe the bug**
Nach dem Update auf Hoobs 4 startet der Plugin nicht und es kommt zu einem Error

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
LOG->

7.7.2021, 20:51:27 HOOBS HOOBS starting
7.7.2021, 20:51:30 HOOBS [ DEBUG ] Initializing HAP-NodeJS v0.9.4...
7.7.2021, 20:51:31 HOOBS Loaded plugin 'homebridge-fritz-platform'
7.7.2021, 20:51:33 HOOBS [ ERROR ] Error initializing plugin 'homebridge-fritz-platform'
7.7.2021, 20:51:33 HOOBS [ ERROR ] Error: Cannot find module '/var/lib/hoobs/hoobs/node_modules/underscore/underscore-node.cjs'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:922:15)
    at resolveExports (internal/modules/cjs/loader.js:450:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/var/lib/hoobs/hoobs/node_modules/ping/lib/ping-promise.js:21:10)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/var/lib/hoobs/hoobs/node_modules/ping/lib/ping-sys.js:14:12)
7.7.2021, 20:51:36 HOOBS Loaded plugin 'homebridge-hue'
7.7.2021, 20:51:36 HOOBS [ DEBUG ] Registering platform 'homebridge-hue.Hue'
7.7.2021, 20:51:36 HOOBS Loaded plugin 'homebridge-shelly'
7.7.2021, 20:51:37 HOOBS [ DEBUG ] Registering platform 'homebridge-shelly.Shelly'
7.7.2021, 20:51:37 HOOBS Loaded plugin 'homebridge-tplink-smarthome'
7.7.2021, 20:51:37 HOOBS [ DEBUG ] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
7.7.2021, 20:51:37 HOOBS Loading 4 platforms...
7.7.2021, 20:51:37 HOOBS Conbee 2 homebridge-hue v0.13.17, node v14.17.2, homebridge v1.3.4
7.7.2021, 20:51:37 HOOBS TplinkSmarthome homebridge-tplink-smarthome v6.4.0, node v14.17.2, homebridge v1.3.4, api v2.7
7.7.2021, 20:51:38 HOOBS TplinkSmarthome Configuring cached accessory: [Entertainment] UUID: 24a8344c-a947-4e09-9252-06a74f77d2ce deviceId: 80064E1CF85D392673FCD9771CC424561CF9018C 
7.7.2021, 20:51:38 HOOBS TplinkSmarthome Configuring cached accessory: [Sofa] UUID: db2a8f18-53c8-4e88-bfa6-624fb5f36ea7 deviceId: 800627A2E2C453A29362DB45CB9EA9A61CF9FADA 
7.7.2021, 20:51:38 HOOBS TplinkSmarthome Configuring cached accessory: [3D Drucker] UUID: 8920bc37-4259-4078-b64e-62053cccef73 deviceId: 8006E73680FDB007C69EB4421D3F21461CF9E5EF 
7.7.2021, 20:51:38 HOOBS TplinkSmarthome Configuring cached accessory: [PC] UUID: 0d939ba7-f8ef-4257-8abf-385c57ff7dd3 deviceId: 80060294194524D00A3D1E13294B19CB18E77D7A 
7.7.2021, 20:51:38 HOOBS Shelly 1 accessory loaded from cache
7.7.2021, 20:51:38 HOOBS Shelly [ WARNING ] Ignoring unknown network interface name or address 192.168.178.1
7.7.2021, 20:51:38 HOOBS Shelly Admin server is running on port 8181
7.7.2021, 20:51:38 HOOBS Conbee 2 192.***.***.35: request 1: GET /config
7.7.2021, 20:51:38 HOOBS Conbee 2 [ WARNING ] 192.168.178.35: request 1: 192.168.178.35:1881: cannot connect: ECONNREFUSED
7.7.2021, 20:51:38 HOOBS Conbee 2 [ ERROR ] 192.168.178.35:1881: not found - retrying in 30s
7.7.2021, 20:51:38 HOOBS TplinkSmarthome New Device Online: [Entertainment] plug [80064E1CF85D392673FCD9771CC424561CF9018C] 192.168.178.72 9999
7.7.2021, 20:51:38 HOOBS TplinkSmarthome Adding: [Entertainment] plug [80064E1CF85D392673FCD9771CC424561CF9018C]
7.7.2021, 20:51:38 HOOBS [ ERROR ] [HOOBS@Entertainment@Entertainment@Amperes] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 20:51:38 HOOBS [ ERROR ] [HOOBS@Entertainment@Entertainment@Total Consumption] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 20:51:38 HOOBS [ ERROR ] [HOOBS@Entertainment@Entertainment@Apparent Power] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 20:51:38 HOOBS [ ERROR ] [HOOBS@Entertainment@Entertainment@Volts] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 20:51:38 HOOBS [ ERROR ] [HOOBS@Entertainment@Entertainment@Consumption] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 20:51:38 HOOBS TplinkSmarthome New Device Online: [3D Drucker] plug [8006E73680FDB007C69EB4421D3F21461CF9E5EF] 192.168.178.73 9999
7.7.2021, 20:51:38 HOOBS TplinkSmarthome Adding: [3D Drucker] plug [8006E73680FDB007C69EB4421D3F21461CF9E5EF]
7.7.2021, 20:51:38 HOOBS [ ERROR ] [HOOBS@3D Drucker@3D Drucker@Amperes] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 20:51:38 HOOBS [ ERROR ] [HOOBS@3D Drucker@3D Drucker@Apparent Power] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 20:51:38 HOOBS [ ERROR ] [HOOBS@3D Drucker@3D Drucker@Total Consumption] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 20:51:38 HOOBS [ ERROR ] [HOOBS@3D Drucker@3D Drucker@Volts] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 20:51:38 HOOBS [ ERROR ] [HOOBS@3D Drucker@3D Drucker@Consumption] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 20:51:38 HOOBS TplinkSmarthome Adding: [Sofa] plug [800627A2E2C453A29362DB45CB9EA9A61CF9FADA]
7.7.2021, 20:51:38 HOOBS TplinkSmarthome New Device Online: [Sofa] plug [800627A2E2C453A29362DB45CB9EA9A61CF9FADA] 192.168.178.71 9999
7.7.2021, 20:51:38 HOOBS [ ERROR ] [HOOBS@Sofa@Sofa@Amperes] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 20:51:38 HOOBS [ ERROR ] [HOOBS@Sofa@Sofa@Total Consumption] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 20:51:38 HOOBS [ ERROR ] [HOOBS@Sofa@Sofa@Apparent Power] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 20:51:38 HOOBS [ ERROR ] [HOOBS@Sofa@Sofa@Volts] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 20:51:38 HOOBS [ ERROR ] [HOOBS@Sofa@Sofa@Consumption] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 20:51:38 HOOBS TplinkSmarthome Adding: [PC] plug [80060294194524D00A3D1E13294B19CB18E77D7A]
7.7.2021, 20:51:38 HOOBS TplinkSmarthome New Device Online: [PC] plug [80060294194524D00A3D1E13294B19CB18E77D7A] 192.168.178.34 9999
7.7.2021, 20:52:08 HOOBS Conbee 2 192.***.***.35: request 1: GET /config
7.7.2021, 20:52:08 HOOBS Conbee 2 [ WARNING ] 192.168.178.35: request 1: 192.168.178.35:1881: cannot connect: ECONNREFUSED
7.7.2021, 20:52:08 HOOBS Conbee 2 [ ERROR ] 192.168.178.35:1881: not found - retrying in 30s
7.7.2021, 20:52:38 HOOBS Conbee 2 192.***.***.35: request 1: GET /config
7.7.2021, 20:52:38 HOOBS Conbee 2 [ WARNING ] 192.168.178.35: request 1: 192.168.178.35:1881: cannot connect: ECONNREFUSED
7.7.2021, 20:52:38 HOOBS Conbee 2 [ ERROR ] 192.168.178.35:1881: not found - retrying in 30s
7.7.2021, 20:53:08 HOOBS Conbee 2 192.***.***.35: request 1: GET /config
7.7.2021, 20:53:08 HOOBS Conbee 2 [ ERROR ] 192.168.178.35:1881: not found - retrying in 30s
7.7.2021, 20:53:08 HOOBS Conbee 2 [ WARNING ] 192.168.178.35: request 1: 192.168.178.35:1881: cannot connect: ECONNREFUSED
7.7.2021, 20:53:38 HOOBS Conbee 2 [ WARNING ] 192.168.178.35: request 1: 192.168.178.35:1881: cannot connect: ECONNREFUSED
7.7.2021, 20:53:38 HOOBS Conbee 2 192.***.***.35: request 1: GET /config
7.7.2021, 20:53:38 HOOBS Conbee 2 [ ERROR ] 192.168.178.35:1881: not found - retrying in 30s
7.7.2021, 20:54:08 HOOBS Conbee 2 192.***.***.35: request 1: GET /config
7.7.2021, 20:54:08 HOOBS Conbee 2 [ ERROR ] 192.168.178.35:1881: not found - retrying in 30s
7.7.2021, 20:54:08 HOOBS Conbee 2 [ WARNING ] 192.168.178.35: request 1: 192.168.178.35:1881: cannot connect: ECONNREFUSED
7.7.2021, 20:54:38 HOOBS Conbee 2 192.***.***.35: request 1: GET /config
7.7.2021, 20:54:38 HOOBS Conbee 2 [ ERROR ] 192.168.178.35:1881: not found - retrying in 30s
7.7.2021, 20:54:38 HOOBS Conbee 2 [ WARNING ] 192.168.178.35: request 1: 192.168.178.35:1881: cannot connect: 
7.7.2021, 21:12:03 Hub hub is running on port 80
7.7.2021, 21:12:08 Hub HOOBS starting
7.7.2021, 21:12:10 HOOBS [ DEBUG ] Initializing HAP-NodeJS v0.9.4...
7.7.2021, 21:12:12 HOOBS Loaded plugin 'homebridge-fritz-platform'
7.7.2021, 21:12:15 HOOBS [ ERROR ] Error initializing plugin 'homebridge-fritz-platform'
7.7.2021, 21:12:15 HOOBS [ ERROR ] Error: Cannot find module '/var/lib/hoobs/hoobs/node_modules/underscore/underscore-node.cjs'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:922:15)
    at resolveExports (internal/modules/cjs/loader.js:450:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/var/lib/hoobs/hoobs/node_modules/ping/lib/ping-promise.js:21:10)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/var/lib/hoobs/hoobs/node_modules/ping/lib/ping-sys.js:14:12)
7.7.2021, 21:12:22 HOOBS Loaded plugin 'homebridge-hue'
7.7.2021, 21:12:22 HOOBS [ DEBUG ] Registering platform 'homebridge-hue.Hue'
7.7.2021, 21:12:22 HOOBS Loaded plugin 'homebridge-shelly'
7.7.2021, 21:12:23 HOOBS [ DEBUG ] Registering platform 'homebridge-shelly.Shelly'
7.7.2021, 21:12:24 HOOBS Loaded plugin 'homebridge-tplink-smarthome'
7.7.2021, 21:12:24 HOOBS [ DEBUG ] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
7.7.2021, 21:12:24 HOOBS Loading 4 platforms...
7.7.2021, 21:12:24 HOOBS Conbee 2 homebridge-hue v0.13.17, node v14.17.2, homebridge v1.3.4
7.7.2021, 21:12:24 HOOBS TplinkSmarthome homebridge-tplink-smarthome v6.4.0, node v14.17.2, homebridge v1.3.4, api v2.7
7.7.2021, 21:12:25 HOOBS TplinkSmarthome Configuring cached accessory: [Entertainment] UUID: 24a8344c-a947-4e09-9252-06a74f77d2ce deviceId: 80064E1CF85D392673FCD9771CC424561CF9018C 
7.7.2021, 21:12:25 HOOBS TplinkSmarthome Configuring cached accessory: [Sofa] UUID: db2a8f18-53c8-4e88-bfa6-624fb5f36ea7 deviceId: 800627A2E2C453A29362DB45CB9EA9A61CF9FADA 
7.7.2021, 21:12:25 HOOBS TplinkSmarthome Configuring cached accessory: [3D Drucker] UUID: 8920bc37-4259-4078-b64e-62053cccef73 deviceId: 8006E73680FDB007C69EB4421D3F21461CF9E5EF 
7.7.2021, 21:12:25 HOOBS TplinkSmarthome Configuring cached accessory: [PC] UUID: 0d939ba7-f8ef-4257-8abf-385c57ff7dd3 deviceId: 80060294194524D00A3D1E13294B19CB18E77D7A 
7.7.2021, 21:12:25 HOOBS Shelly 1 accessory loaded from cache
7.7.2021, 21:12:25 HOOBS Shelly [ WARNING ] Ignoring unknown network interface name or address 192.168.178.1
7.7.2021, 21:12:25 HOOBS Shelly Admin server is running on port 8181
7.7.2021, 21:12:25 HOOBS Conbee 2 192.***.***.35: request 1: GET /config
7.7.2021, 21:12:25 HOOBS Conbee 2 [ WARNING ] 192.168.178.35: request 1: 192.168.178.35:1881: cannot connect: ECONNREFUSED
7.7.2021, 21:12:25 HOOBS Conbee 2 [ ERROR ] 192.168.178.35:1881: not found - retrying in 30s
7.7.2021, 21:12:25 HOOBS TplinkSmarthome New Device Online: [Entertainment] plug [80064E1CF85D392673FCD9771CC424561CF9018C] 192.168.178.72 9999
7.7.2021, 21:12:25 HOOBS TplinkSmarthome Adding: [Entertainment] plug [80064E1CF85D392673FCD9771CC424561CF9018C]
7.7.2021, 21:12:25 HOOBS [ ERROR ] [HOOBS@Entertainment@Entertainment@Amperes] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 21:12:25 HOOBS [ ERROR ] [HOOBS@Entertainment@Entertainment@Total Consumption] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 21:12:25 HOOBS [ ERROR ] [HOOBS@Entertainment@Entertainment@Apparent Power] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 21:12:25 HOOBS [ ERROR ] [HOOBS@Entertainment@Entertainment@Volts] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 21:12:25 HOOBS [ ERROR ] [HOOBS@Entertainment@Entertainment@Consumption] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 21:12:25 HOOBS TplinkSmarthome New Device Online: [3D Drucker] plug [8006E73680FDB007C69EB4421D3F21461CF9E5EF] 192.168.178.73 9999
7.7.2021, 21:12:25 HOOBS TplinkSmarthome Adding: [3D Drucker] plug [8006E73680FDB007C69EB4421D3F21461CF9E5EF]
7.7.2021, 21:12:25 HOOBS [ ERROR ] [HOOBS@3D Drucker@3D Drucker@Amperes] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 21:12:25 HOOBS [ ERROR ] [HOOBS@3D Drucker@3D Drucker@Total Consumption] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 21:12:25 HOOBS [ ERROR ] [HOOBS@3D Drucker@3D Drucker@Apparent Power] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 21:12:25 HOOBS [ ERROR ] [HOOBS@3D Drucker@3D Drucker@Volts] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 21:12:25 HOOBS [ ERROR ] [HOOBS@3D Drucker@3D Drucker@Consumption] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 21:12:25 HOOBS TplinkSmarthome New Device Online: [Sofa] plug [800627A2E2C453A29362DB45CB9EA9A61CF9FADA] 192.168.178.71 9999
7.7.2021, 21:12:25 HOOBS TplinkSmarthome Adding: [Sofa] plug [800627A2E2C453A29362DB45CB9EA9A61CF9FADA]
7.7.2021, 21:12:25 HOOBS [ ERROR ] [HOOBS@Sofa@Sofa@Amperes] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 21:12:25 HOOBS [ ERROR ] [HOOBS@Sofa@Sofa@Total Consumption] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 21:12:25 HOOBS [ ERROR ] [HOOBS@Sofa@Sofa@Apparent Power] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 21:12:25 HOOBS [ ERROR ] [HOOBS@Sofa@Sofa@Volts] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 21:12:25 HOOBS [ ERROR ] [HOOBS@Sofa@Sofa@Consumption] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
7.7.2021, 21:12:25 HOOBS TplinkSmarthome New Device Online: [PC] plug [80060294194524D00A3D1E13294B19CB18E77D7A] 192.168.178.34 9999
7.7.2021, 21:12:25 HOOBS TplinkSmarthome Adding: [PC] plug [80060294194524D00A3D1E13294B19CB18E77D7A]
7.7.2021, 21:12:55 HOOBS Conbee 2 192.***.***.35: request 1: GET /config
7.7.2021, 21:12:55 HOOBS Conbee 2 [ WARNING ] 192.168.178.35: request 1: 192.168.178.35:1881: cannot connect: ECONNREFUSED
7.7.2021, 21:12:55 HOOBS Conbee 2 [ ERROR ] 192.168.178.35:1881: not found - retrying in 30s
7.7.2021, 21:13:25 HOOBS Conbee 2 192.***.***.35: request 1: GET /config
7.7.2021, 21:13:25 HOOBS Conbee 2 [ WARNING ] 192.168.178.35: request 1: 192.168.178.35:1881: cannot connect: ECONNREFUSED
7.7.2021, 21:13:25 HOOBS Conbee 2 [ ERROR ] 192.168.178.35:1881: not found - retrying in 30s
7.7.2021, 21:13:55 HOOBS Conbee 2 192.***.***.35: request 1: GET /config
7.7.2021, 21:13:55 HOOBS Conbee 2 [ WARNING ] 192.168.178.35: request 1: 192.168.178.35:1881: cannot connect: ECONNREFUSED
7.7.2021, 21:13:55 HOOBS Conbee 2 [ ERROR ] 192.168.178.35:1881: not found - retrying in 30s

**Comment by mkellsy** [comment]
The NPM repos have been acting wired the last few days.
Can you try to reinstall the plugin.

1. Go to the Plugins screen
2. Go to the Fritz Platform plugin
3. Click on the Versions tab
4. Click the Download Icon on the latest version
5. Select the Bridge you have this installed on, from your logs, this is the HOOBS bridge.

If this doesn't work you can install this plugin to it's own bridge and move your config over.
