### ISSUE TITLE
Homebridge restarting FritzBox for no reason

### ISSUE THREAD

**Issue by flowoy96** [SeydX/homebridge-fritz-platform#214]
Hi there,

is there any known problem/feature that allows the Homebridge Plugin to restart my Fritzbox 7580?

This happens sometimes for no reason.

**Comment by SeydX** [comment]
Are you sure that the reboot is caused by Homebridge?

**Comment by flowoy96** [comment]
Yes. Before the FRITZ!Box restarts it sends me the latest logs which shows that the user „Homebridge“ initiated a restart:

![Uploading 42984AE7-3837-4E93-BB0C-DBBF344069B7.jpeg…]()

**Comment by SeydX** [comment]
Hmm, can u send me the log pls?

Normally the plugin CAN NOT restart the fritzbox by itself without an user interaction..

Are you sure u dont clicked on the switch? Maybe via an automation?

**Comment by flowoy96** [comment]
This is what the log says at the exact time:

2021-07-08 00:20:04 [7/8/2021, 2:20:04 AM] [FritzBridge][AVM Homebridge: Polling state (router)...

I'm using HomeBridge inside of a Docker container running on my Synology NAS.

**Comment by SeydX** [comment]
> This is what the log says at the exact time:
> 
> 2021-07-08 00:20:04 [7/8/2021, 2:20:04 AM] [FritzBridge][AVM Homebridge: Polling state (router)...
> 
> I'm using HomeBridge inside of a Docker container running on my Synology NAS.

But this has nothing to do with the restart. It only says that the FritzBox is queried (polling) to set the status correctly in HomeKit. This has nothing to do with the restart.

**Comment by flowoy96** [comment]
This is the only log I can see. In Homebridge itself I can't see any logs further that 11 AM this day...

**Comment by SeydX** [comment]
> This is the only log I can see. In Homebridge itself I can't see any logs further that 11 AM this day...

As i said, it has nothing to do with homebridge and the log also confirms that the restart DOES NOT executed from homebridge

maybe check the fritzbox events

**Comment by flowoy96** [comment]
The log says that the restart was initiated by the FritzBox user "homebridge" which I especially created for the homebridge plugin. I also changed the password to make sure it's not compromised. Further the user "homebridge" is not allowed to login from internet, only the local network.

Unfortunately I can only check the event log provided per email and it says what I mentioned in https://github.com/SeydX/homebridge-fritz-platform/issues/214#issuecomment-876175233

**Comment by SeydX** [comment]
Can u post your config pls

**Comment by flowoy96** [comment]
`{
    "bridge": {
        "name": "Homebridge 0850",
        "username": "censored",
        "port": 53406,
        "pin": "censored"
    },
    "accessories": [
        {
            "name": "censored",
            "ip": "10.10.1.10",
            "pingInterval": 2,
            "pingsToChange": 5,
            "pingTimeout": 1,
            "pingCommandTimeout": 0,
            "mac": "censored",
            "broadcastAddress": "10.10.1.255",
            "startCommandTimeout": 0,
            "wakeGraceTime": 45,
            "wakeCommandTimeout": 0,
            "shutdownGraceTime": 15,
            "shutdownCommandTimeout": 0,
            "log": true,
            "logPinger": false,
            "debugLog": false,
            "returnEarly": false,
            "accessory": "NetworkDevice",
            "_bridge": {
                "username": "censored",
                "port": 33772
            }
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "FritzBridge",
            "debug": true,
            "devices": [
                {
                    "name": "AVM Homebridge",
                    "host": "10.10.1.1",
                    "username": "homebridge",
                    "password": "censored",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "manufacturer": "AVM",
                    "model": "FRITZ!Box 7580",
                    "master": true,
                    "connection": "dsl",
                    "options": {
                        "wifi_guest": "switch",
                        "led": "switch"
                    }
                }
            ],
            "presence": [
                {
                    "ping": false
                }
            ],
            "smarthome": [
                {
                    "name": "Wohnzimmerfenster",
                    "ain": "censored",
                    "group": false,
                    "accType": "lightbulb"
                },
                {
                    "name": "Sideboard",
                    "ain": "censored",
                    "accType": "lightbulb"
                },
                {
                    "name": "Kugel",
                    "ain": "censored",
                    "accType": "lightbulb"
                },
                {
                    "name": "Zaun",
                    "ain": "censored",
                    "accType": "lightbulb"
                },
                {
                    "name": "Ventilator",
                    "ain": "censored",
                    "accType": "switch"
                }
            ],
            "callmonitor": {
                "active": false,
                "port": 1012
            },
            "extras": {
                "alarm": {
                    "active": false
                },
                "wakeup": {
                    "active": false
                },
                "ringlock": {
                    "active": false
                },
                "phoneBook": {
                    "active": false
                }
            },
            "options": {
                "polling": {
                    "timer": 10
                }
            },
            "telegram": {
                "active": true,
                "token": "censored",
                "chatID": "censored"
            },
            "platform": "FritzPlatform"
        }
    ]
}`

**OR NOT AS CODE**

{
    "bridge": {
        "name": "Homebridge 0850",
        "username": "censored",
        "port": 53406,
        "pin": "censored"
    },
    "accessories": [
        {
            "name": "censored",
            "ip": "10.10.1.10",
            "pingInterval": 2,
            "pingsToChange": 5,
            "pingTimeout": 1,
            "pingCommandTimeout": 0,
            "mac": "censored",
            "broadcastAddress": "10.10.1.255",
            "startCommandTimeout": 0,
            "wakeGraceTime": 45,
            "wakeCommandTimeout": 0,
            "shutdownGraceTime": 15,
            "shutdownCommandTimeout": 0,
            "log": true,
            "logPinger": false,
            "debugLog": false,
            "returnEarly": false,
            "accessory": "NetworkDevice",
            "_bridge": {
                "username": "censored",
                "port": 33772
            }
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "FritzBridge",
            "debug": true,
            "devices": [
                {
                    "name": "AVM Homebridge",
                    "host": "10.10.1.1",
                    "username": "homebridge",
                    "password": "censored",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "manufacturer": "AVM",
                    "model": "FRITZ!Box 7580",
                    "master": true,
                    "connection": "dsl",
                    "options": {
                        "wifi_guest": "switch",
                        "led": "switch"
                    }
                }
            ],
            "presence": [
                {
                    "ping": false
                }
            ],
            "smarthome": [
                {
                    "name": "Wohnzimmerfenster",
                    "ain": "censored",
                    "group": false,
                    "accType": "lightbulb"
                },
                {
                    "name": "Sideboard",
                    "ain": "censored",
                    "accType": "lightbulb"
                },
                {
                    "name": "Kugel",
                    "ain": "censored",
                    "accType": "lightbulb"
                },
                {
                    "name": "Zaun",
                    "ain": "censored",
                    "accType": "lightbulb"
                },
                {
                    "name": "Ventilator",
                    "ain": "censored",
                    "accType": "switch"
                }
            ],
            "callmonitor": {
                "active": false,
                "port": 1012
            },
            "extras": {
                "alarm": {
                    "active": false
                },
                "wakeup": {
                    "active": false
                },
                "ringlock": {
                    "active": false
                },
                "phoneBook": {
                    "active": false
                }
            },
            "options": {
                "polling": {
                    "timer": 10
                }
            },
            "telegram": {
                "active": true,
                "token": "censored",
                "chatID": "censored"
            },
            "platform": "FritzPlatform"
        }
    ]
}

**Comment by EpsilonAlpha** [comment]
I had the same issue, there is a switch provided to HomeKit which is the FritzBox itself, then either a reboot of the Box or a reset of the connection happening. In the end, it killed my internet connection for a couple of minutes.

I changed the config to make the Switch not visible to HomeKit, so I can't accidentally press it. Maybe it's the same for you

**Comment by flowoy96** [comment]
Thanks @EpsilonAlpha! This solved my problem. I just hid the Bridge which probably caused the restart.

![image](https://user-images.githubusercontent.com/46541777/125093120-504e6100-e0d2-11eb-97a9-fb06ce4c8ee5.png)
