### ISSUE TITLE
Since V6 LED Switch working,but always show off

### ISSUE THREAD

**Issue by Cheroba** [SeydX/homebridge-fritz-platform#216]
The LED switch always shows status OFF. If I press and turn it ON after a state uodate goes OFF, but the LED on device remains ON

**Comment by hartmutfredrich** [comment]
I have the same „Problem“, V6.0.14, FB 6660 Cable ,FritzOS 7.27

**Comment by db77x** [comment]
Same problem with 6591

**Comment by maciboy** [comment]
Same for me, updated Hoobs to v4 and plugin to v6.0.14 yesterday.

**Comment by Nastras** [comment]
7590AX, 1750e, 3000 me too.

**Comment by SeydX** [comment]
fixed in v6.0.15
