### ISSUE TITLE
Disable all deflections

### ISSUE THREAD

**Issue by MasterofKungfu9999** [SeydX/homebridge-fritz-platform#217]
**Is your feature request related to a problem? Please describe.**
Is it possible to implent a feature to disable all deflections?  At the moment all deflections are enabled with the switch. If i`m going to disable deflection with the switch only the first deflection will be disabled 

**Describe the solution you'd like**
Disable all deflections in fritz

**Describe alternatives you've considered**

**Additional context**

**Comment by SeydX** [comment]
should be fixed in v6.0.16 (beta) - pushig soon

if you want to try it:

`sudo npm i -g homebridge-fritz-platform@beta`
