### ISSUE TITLE
ESOCKETTIMEDOUT errors

### ISSUE THREAD

**Issue by Phoenix-DH** [SeydX/homebridge-fritz-platform#22]
Hi,

today after I restart of my homebridge I saw the following in the log:

> [2019-3-30 22:42:46] [FritzPlatform] [ERROR] Fritz!Box: An error occured while getting WIFI WPS state!
[2019-3-30 22:42:46] [FritzPlatform] [ERROR] {
    "error": "ESOCKETTIMEDOUT",
    "errorCode": "ESOCKETTIMEDOUT",
    "serviceType": "urn:dslforum-org:service:WLANConfiguration:1",
    "action": "X_AVM-DE_GetWPSInfo"
}
[2019-3-30 22:42:46] [FritzPlatform] [ERROR] Fritz!Box: An error occured while getting Answering Machine state!
[2019-3-30 22:42:46] [FritzPlatform] [ERROR] {
    "error": "ESOCKETTIMEDOUT",
    "errorCode": "ESOCKETTIMEDOUT",
    "serviceType": "urn:dslforum-org:service:X_AVM-DE_TAM:1",
    "action": "GetInfo"
}

Do not know if this is critical and where it comes from.

**Comment by SeydX** [comment]
How often does the error message come?

The error can have many causes. Can be due to the registered user, Internet connection etc etc

**Comment by SeydX** [comment]
See also https://github.com/SeydX/homebridge-fritz-platform/blob/master/FAQ.md#etimedoutesockettimedout

**Comment by Phoenix-DH** [comment]
Saw the FAQ. I checked user, is my admin.
As far as I see it correct, error appears only once after rebooting the service.

I will have an eye on and try the hints when occuring again.

Thanks

**Comment by Phoenix-DH** [comment]
I had a look to the log on config-ui-x ... I see only the information after restarting the homebridge service once.

But what I in addition figured out with the smarthome features I am using:
I have the DECT 200 with temperature.
It seems that after a period of time there will be no new temp information be delivered to the plugin.
Because the temperature is constant an a value.
I cross checked it with the value on fritz.box website.

Maybe something related?

I use FW 7.01 delivered from Vodafone.

**Comment by Phoenix-DH** [comment]
After several days of testing. This errors occur not always after restarting homebridge, only sometines.
But updating temp is always only working for some hours... arround 12 I think.

I created also an addirional user.

Thanks snd a great weekend

**Comment by SeydX** [comment]
Hey, v7.1 is up, tried with FritzOS 7.1 ?

**Comment by Phoenix-DH** [comment]
Hey, not possible for me because my box is hired from my provider.
I am forced to use what he provides me.
Manual updates are not possible.

**Comment by SeydX** [comment]
Can u test the beta version pls

https://github.com/SeydX/homebridge-fritz-platform/issues/30

**Comment by Phoenix-DH** [comment]
Will test it within the next days.
Maybe my problem with updating temperature of DECT is also fixed.

**Comment by SeydX** [comment]
@Phoenix-DH 

any news on this?

**Comment by Phoenix-DH** [comment]
Unfortunately not. I was trriing to install v4 yesterday, but I have troubles and need to uninstall the whole plugin again.
I will try again this week and keep you up to date.

**Comment by Phoenix-DH** [comment]
Hey, I think we can close this topic, the error has gone.
But the plugin is not working for me until now.

I will create ann own toipic for it.

Thank you!
