### ISSUE TITLE
Presence not working anymore - DSL measuring fails (always showing same numbers)

### ISSUE THREAD

**Issue by shinzan111** [SeydX/homebridge-fritz-platform#220]
**Describe the bug**
#1 Issue ->  Since several Updates the Plugin does not shows any status of Presence
#2 Issue ->  The DSL Connection does not show the right Up- and Download No. as flagged many times before

If this does not work, it seems redundant to use this App anymore.

1. Go to HomeKit or Eve
2. Click on FritzBox or however you named it
3. Scroll down to DSL
4. See that the Upload and Download sizes are always the same numbers

**Expected behavior**
Before it started a measuring and showed after some seconds the real numbers regarding Upload and Download
which have always been different as before the last measuring.

**Screenshots**
no screenshots

**Desktop (please complete the following information):**
 - OS: Synology / Docker / Homebridge
 - Browser:  doesn't matter as I am looking at it from HomeKit or Eve App

**Smartphone (please complete the following information):**
 - Device: iPhone regardless which modell
 - OS: regardless which version ... had it on different versions
 - Browser:  no browser ... its on the App
 - Version:  does not matter

**Additional context**

Could you please refer 3 or 4 Versions before and check why I cannot see a correct measuring of the DSL Upload and Download numbers and why the Presence does not flagg anymore if someone has left the network??

Thanks

**Comment by SeydX** [comment]
@shinzan111 

The broadband function is not a real measurement. It only shows your highest possible download/upload value

And for presence, i need more information like your config.json, which fritzbox model, version etc
