### ISSUE TITLE
An error occured during getting state!

### ISSUE THREAD

**Issue by Triopal** [SeydX/homebridge-fritz-platform#222]
```
[09/08/2021, 20:41:29] [FritzPlatform] FritzBox (dsl): An error occured during getting state!
[09/08/2021, 20:41:29] [FritzPlatform] Error: Internal Server Error
at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:227:20)
at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
at Handler.get (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:101:28)
at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:967:11) {
title: 'Invalid Response',
code: 500,
soap: { errorCode: '401', errorDescription: 'Invalid Action' },
url: 'https://Homebridge:****@192.168.178.1:49443/upnp/control/wanpppconn1'
}
```

**Guten Abend,
diese Fehlermeldung erhalte ich leider in der HB alle paar Sekunden. Einen neuen Benutzer habe ich in der FritzBox (7490 OS 07.27) mit allen Rechten bereits erstellt, leider ohne Abhilfe. Leider ist mein Latein damit am Ende. Die Steuerung der Smarthomeprodukte funktioniert tadellos. Aber ignorieren fällt doch schwer.**

Die zugehörige Konfiguration:
],
"platforms": [
{
"name": "Config",
"port": 8581,
"platform": "config"
},
{
"name": "FritzPlatform",
"debug": false,
"warn": true,
"error": true,
"extendedError": true,
"devices": [
{
"active": true,
"name": "FritzBox",
"host": "192.168.178.1",
"username": "Homebridge",
"password": "****",
"ssl": true,
"tr064": true,
"igd": false,
"model": "7490",
"wifiUnits": 2,
"master": true,
"connection": "dsl",
"options": {
"wifi_2ghz": "switch",
"wifi_5ghz": "switch"
}
},
{
"active": false,
"ssl": true,
"tr064": true,
"igd": false,
"wifiUnits": 2
}
],
"smarthome": [
{
"active": true,
"name": "Heizung Schlafzimmer",
"ain": "119610827456",
"group": false,
"window": true,
"openWindow": false,
"battery": true,
"accTypeGroup": "thermostat",
"accType": "thermostat"
},
{
"active": true,
"name": "Heizung Badezimmer ",
"ain": "119600964264",
"externTemperatureSensor": false,
"window": true,
"battery": true,
"accType": "thermostat"
},
{
"active": true,
"name": "Heizung Arbeitszimmer",
"ain": "119590559496",
"window": true,
"openWindow": false,
"battery": true,
"accType": "thermostat"
},
{
"active": true,
"name": "Heizung Wohnzimmer Balkon",
"ain": "119590299152",
"group": false,
"window": true,
"openWindow": false,
"battery": true,
"accTypeGroup": "thermostat",
"accType": "thermostat"
},
{
"active": true,
"name": "Heizung Wohnzimmer Fenster",
"ain": "11959 0299336",
"window": true,
"openWindow": false,
"battery": true,
"accType": "thermostat"
}
],
"callmonitor": {
"active": false
},
"options": {
"polling": {
"timer": 15
}
},
"platform": "FritzPlatform"
}

**Comment by SeydX** [comment]
@Triopal 

``{ errorCode: '401', errorDescription: 'Invalid Action' }``

es scheint so als ob das Plugin keine Abfrage zum DSL Status machen kann bzw. diesen garnicht kennt?

Wie ist dein Router angeschlossen? Ist es dein "Haupt" Router?

Versuch mal ``"connection": "repeater"``

lg

**Comment by martind1983** [comment]
HI @SeydX 

ich nutze die FRITZ!Box 6850 LTE mit dem aktuellen FRITZ!OS: 07.28 - good news, das Plugin funktioniert auch damit.
Anfangs hatte ich den selben Fehler, da ich als Connection "DSL" ausgewählt habe (es gibt ja nur DSL, Cable, Repeater).
Die Fritz Box LTE aber natürlich nur Mobile Connection.
Mit dem Tipp von dir auf Repeater zu wechseln, hab ich immerhin keine Fehlermeldung mehr. Super!

Frage: kannst du die LTE connection auch implementieren und abfragen?

Das wär ein Wahnsinn ;-)

(und fettes Danke für das mega plugin!)
