### ISSUE TITLE
DECT200: Temperatur wird in Apple Home nicht angezeigt

### ISSUE THREAD

**Issue by tobihoby** [SeydX/homebridge-fritz-platform#226]
Hi,

erstmalige Installation des Plugins in neuster Version.
Die Fritzbox und der DECT200 werden auch erkannt, aber beim DECT200 wird mir nur die Steckdose angezeigt, die Temperatur in Apple Home leider nicht.
Konfig Smarthome:
[
    {
        "active": true,
        "name": "STD Tor",
        "ain": "xxxxx",
        "energy": true,
        "temperature": false,
        "accType": "switch",
        "startValue": 3
    },
    {
        "active": true,
        "name": "Temp. Garage",
        "ain": "xxxxxxxx",
        "accType": "temperature"
    }
]

Ist das so korrekt?!

Gruß
Tobi

**Comment by SeydX** [comment]
Geht es hierbei um STD Tor? Oder Temp. garage?
