### ISSUE TITLE
DECT 200 Energieanzeige

### ISSUE THREAD

**Issue by baerenmarke90** [SeydX/homebridge-fritz-platform#23]
Hi,

ist es möglich die Energieanzeige in Eve darstellen zu lassen? Beispielsweise könnte man damit Push-Benachrichtigungen triggern, wenn die Energie an der Steckdose einen bestimmten Wert erreicht hat.

VG

**Comment by SeydX** [comment]
Habe ich mir notiert ! Danke

**Comment by cschildhorn** [comment]
Das ganze mit fakegato als historische Daten zu haben, wäre auch echt top. Aktuell sehe ich nur die historischen Temperaturdaten der DECTs.

**Comment by SeydX** [comment]
Bin an der Funktion dran und wir mit v5 kommen 

Lg

**Comment by SeydX** [comment]
Added in v5 Beta 22
