### ISSUE TITLE
Home App Automationen werden nicht übernommen

### ISSUE THREAD

**Issue by Raczka1989** [SeydX/homebridge-fritz-platform#232]
**Describe the bug**
Ich habe mir in der Apple Home App eine Automation erstellt z.b. 23:00 Uhr 21 grad Temperatur einstellen, aber die Automation schaltet nicht um 23 uhr um, Manuell wenn ich die Temperatur einstell funktioniert es ganz normal.  

**To Reproduce**

**Expected behavior**

22.9.2021, 23:00:00 Fritz Platform Bridge FritzPlatform Comet DECT #7 (smarthome-thermostat): Temperature 21
22.9.2021, 23:00:00 Fritz Platform Bridge FritzPlatform [DEBUG] Comet DECT #7 (smarthome-thermostat): Send CMD: {"ain":"140790335312","sid":"60ca3100a3c42f00","switchcmd":"sethkrtsoll","param":42}
22.9.2021, 23:00:00 Fritz Platform Bridge FritzPlatform Comet DECT #7 (smarthome-thermostat): ON
22.9.2021, 23:00:00 Fritz Platform Bridge FritzPlatform [DEBUG] Comet DECT #7 (smarthome-thermostat): Send CMD: {"ain":"140790335312","sid":"60ca3100a3c42f00","switchcmd":"sethkrtsoll","param":34}
22.9.2021, 23:00:00 Fritz Platform Bridge FritzPlatform Comet DECT #7 (smarthome-thermostat): Temperature 17
22.9.2021, 23:00:00 Fritz Platform Bridge FritzPlatform [DEBUG] Comet DECT #7 (smarthome-thermostat): Send CMD: {"ain":"140790335312","sid":"60ca3100a3c42f00","switchcmd":"sethkrtsoll","param":34}

das steht im LOG also wird der Befehl ja von der App an die Bridge gesendet. Oder?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] IOS 15

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Iphone 11 Pro
 - OS: [e.g. iOS8.1] IOS 15

**Additional context**
[log (1).txt](https://github.com/SeydX/homebridge-fritz-platform/files/7213893/log.1.txt)

**Comment by Raczka1989** [comment]
Wo find ich den die Log datei von der Fritz Bridge (Speicherort) habe ja nur die Logdatei der Homebridge.

Ich habe schon die Bridge öfters deinstalliet und neu installiert problem is immer das die Automation nicht auslöst. Aber Manuell sich steuern lässt. Ab und an funktioniert es sogar aber dann wieder nicht, was komisch ist das wenn die Automation auslösen soll immer der Befehl ON mit dazu kommt wenn ich Manuell Steuer wird nur die Grad Zahl als Befehl in der Homebridge angezeigt.

**Comment by SeydX** [comment]
Fixed in v6.0.17

**Comment by Raczka1989** [comment]
![53428170-B209-4241-AA7E-1C990347D7D5](https://user-images.githubusercontent.com/87095533/136436579-ac72d3e3-e0ba-44a7-862b-0ea77771e95b.jpeg)


![91EDC6E3-1F00-4662-BE55-C1840A0FBDB8](https://user-images.githubusercontent.com/87095533/136436615-01c0500c-3382-48e1-8981-c41c5aa53ecf.jpeg)

hab ich gemacht steht immer noch Update da. Automation geht auch nicht.🤔😕
Danke für die Hilfe

**Comment by Raczka1989** [comment]
genau hab immer eingestellt das er um z.b. 23:00 die Bad Heizung auf 21 grad stellen soll und so weiter. 
Hab es in der Apple Home App angelegt die Automation genau.

**Comment by Raczka1989** [comment]
![D6CFCD2D-A606-431B-93A3-976211DD35DF](https://user-images.githubusercontent.com/87095533/136462036-e2084994-8829-43fd-b981-eb1585c4c83a.png)

**Comment by SeydX** [comment]
Kann es sein das die Automationen ich gegenseitig beißen? 

Könntest du die Automationen ausschalten und eine simple Automation anlegen wie "XX Lampe ein = Heizun AN + Temperatur 26 Grad"

**Comment by SeydX** [comment]
Also funktioniert das Plugin wie es soll? Nur liegt es an deinen Automationen?

**Comment by Raczka1989** [comment]
Letztes Jahr hat nämlich alles so funktioniert hab da nix verändert aber jetzt wo das Heizen wieder los geht is es mir aufgefallen.

**Comment by tim-hilt** [comment]
I have a similar problem when targeting multiple thermostats at the same time. One thermostat will always be set correctly, but the other ones will not detect the change in my case. Could it be, that homebridge sends the individual commands "too fast", so that the FRITZ!Box doesn't actually notice all of them?
