### ISSUE TITLE
Max Einstellung Thermostat issue

### ISSUE THREAD

**Issue by Kai9555** [SeydX/homebridge-fritz-platform#233]
Hallo zusammen,

zunächst vielen Dank für das tolle Plugin und die super Arbeit damit.

Ich gehe mit Absicht erst einmal nicht ins Detail bezüglich Config etc, da ich grundlegend erst einmal in Erfahrung bringen wollte, ob meine Beobachtung „normal“ ist, oder ob es sich um einen Fehler handelt.

Wenn ich die Thermostate (DECT 301) manuell am Gerät auf Max schalte, dann ändert sich in HomeKit die Temperatur nicht auf 28 Grad, sondern bleibt beim ursprünglichen Zustand (z.B. 19 Grad).

Ich meine in der letzten Heizperiode es so gesehen zu haben. Immerhin würde es ja Sinn machen bei Max auf eben 28 grad zu gehen. HomeKit kennt den Wert „Max“ ja nicht.

Danke und VG Kai

**Comment by SeydX** [comment]
Hey @Kai9555 

Eine Änderung direkt am Thermostat wird (bedingt durch AVM) erst 15min später angezeigt.

könntest du mal schauen ob das bei dir auch der Fall ist? Sowohl Fritzbox Oberfläche als ob Plugin (HomeKit)

**Comment by Kai9555** [comment]
Hi,

ja grundlegend passt das alles. Ich würde auch sagen das ich ziemlich gut in der Materie stecke. 

Verändere ich am Thermostat die Temperatur auf 22 Grad und öffne HomeKit, erzwinge ich ja sozusagen die Abfrage des aktuellen Status vom Thermostat und in HomeKit werden mir dann auch die 22 Grad angezeigt. Stelle ich das Thermostat auf Max verändert sich der Status jedoch nicht. Das gleiche lässt sich auch reproduzieren wenn ich die Werte entsprechend in der Smart Home App von AVM ändere. Alle Werte von Aus über 8 Grad bis 28 Grad werden direkt in die HomeKit App übertragen. Nur bei Max rührt sich nichts.

Wenn ich also abends noch einmal kontrolliere ob die Thermostate auch alle bei 19 grad stehen, kann ich mir nicht sicher sein ob es wirklich so ist. Meine Frau heizt das Bad und Kinderzimmer mit „Max“ immer schnell hoch und stellt es dann aber oft nicht zurück. In der Home App wird es dann jedoch nicht widergespiegelt

Im Log gibt es dann auch keine Regung wenn der Wert beim öffnen der Home App abgefragt wird und das Thermostat auf Max steht. Debug log kann ich mal einschalten und hier zur Verfügung stellen. Ich denke aber das dem Wert „Max“ kein Gegenwert (28Grad) für HomeKit gegeben wurde?!

**Comment by Kai9555** [comment]
`[24/09/2021, 21:54:06] [FritzPlatform] [DEBUG] Heizkörper Gästezimmer (smarthome-thermostat): {"name":"Heizkörper Gästezimmer","id":"17","ain":"099950281684","online":1,"bitmask":"320","busy":0,"battery":{"value":90,"low":0},"alert":false,"temperature":{"value":19,"offset":-20},"humidity":false,"powermeter":false,"switch":false,"button":false,"blind":false,"thermostat":{"current":19,"target":19,"windowOpen":0},"light":false}`

Das Thermostat stand zu den Zeitpunkt der Abfrage aber schon weit über 15min bei Max. Der Wert war sowohl in der Fritz Box UI zu sehen, als auch am Thermostat. Nur HomeKit zeigt weiterhin 19 Grad an.
