### ISSUE TITLE
Window Contacts not showing actual status

### ISSUE THREAD

**Issue by thorstenman** [seydx/homebridge-fritz-platform#238]
**Describe the bug**
Since some time the so far perfectly working (original) Qivicon SmartHome Door Contact Sensors connected to my FritzBox 7590 do not show actual status, contacts are linked via DECT to router

**To Reproduce**
1. Go to status of door contact in HomeKit App
2. Click on status 
3. Check status
4. Status never changes, for me always Open

Instead AVM router software shows them Close (which is correct)

**Expected behavior**
Status needs to reflect the correct value

**Desktop (please complete the following information):**
 - OS: MacOSX Big Sur latest version 
 - Browser Safari / HomeKit App
 - Latest Version

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 15
 - Browser Safari / HomeKit App
 - Latest version

**Comment by SeydX** [comment]
can u enable ``"debug"`` in your config.json and post your homebridge log pls
