### ISSUE TITLE
Fritz DECT 301 Änderungen werden seit der Version 6.0.0 nicht übernommen

### ISSUE THREAD

**Issue by Raspberry-Kay** [SeydX/homebridge-fritz-platform#239]
Hallo, seit dem Update auf die Version 6.0.0 reagieren meine Fritz DECT 301 auf keine Änderungen. Ich kann zwar alles in HomeKit einstellen, allerdings werden die Änderungen der Temperatur oder das ein oder ausschalten nicht vom Thermostat übernommen bzw. empfangen. In der Homebridge erscheint auch keine Meldung. Mit Version 5.1.2 funktioniert alles problemlos.

**Comment by corratecextremer** [comment]
Hallo, 
@Raspberry-Kay kannst du bestätigen das es sich bei dir um eine FritzBox mit dem FritzOS 06.x handelt? 
Ich habe mit dem FritzOS 07.x (Fritz!Box 7490) keine Probleme es läuft einwandfrei! Vielen Dank an der Stelle @SeydX.
Bei der Fritz!Box 7390 mit FritzOS 06.x läuft die Plugin Version 5.1.2 problemlos. Vielleicht hilft euch das - Viele Grüße.

**Comment by Raspberry-Kay** [comment]
Hallo,
nein bei der Fritz!Box handelt es sich um eine 7590 mit dem FritzOS 07.28. Mit Version 6.0.0 meinte ich die Plugin-Version. Habe verschiedene Versionen ausprobiert, unter anderem auch die neuste 6.0.16 aber immer mit demselben Ergebnis. Muss ich ggf. was in den Einstellungen im Plugin verändern damit es wieder funktioniert? Viele Grüße
