### ISSUE TITLE
Falsche Target Temp bei DECT301

### ISSUE THREAD

**Issue by schweden1997** [SeydX/homebridge-fritz-platform#24]
Wenn durch Änderung der Temperatur auch automatisch der Modus geändert wird, ist die Target Temp die aktuelle Temperatur + heat oder coolValue und nicht die von mir eingestellte Temperatur.
***

Verschiedene Szenarien:

1. Im Raum sind es 20°, Target sind 20°, Modus ist **Cooling**
2. Target wird auf 22° gesetzt
3. Modus ändert sich auf Heating
4. Target ist nun 25° (aktuelle Temp + 5°)

___

1. Im Raum sind es 20°, Target sind 20°, Modus ist **Heating**
2. Target wird auf 22° gesetzt
3. Modus ändert sich nicht 
4. Target bleibt bei 22°
***

Um also beim 1. Szenario die Temperatur auf 22° zu setzen muss man entweder zuerst den Heating Button drücken und dann die Temperatur einstellen oder die Temperatur 2x einstellen.
Das ist insbesondere bei Automatisierungen problematisch

Die ganze Funktionalität um die Modi erschließt sich mir auch nicht so wirklich.

Ich glaube ein relativ "einfacher" Fix wäre es die komplette Funktion mit dem heatValue und coolValue zu entfernen. Die Anzeige ob nun geheizt oder "gekühlt" wird ist ja an sich nicht schlecht, passt aber auch nicht wirklich zu einem Thermostat.

Oder es muss sichergestellt werden, dass zuerst der Befehl heating oder cooling gesendet wird und erst danach die eingestellte Temperatur.

**Comment by SeydX** [comment]
Hallo, werde im Laufe der nächsten Tage ein großes Update bzgl den Thermostaten rausbringen, damit diese so funktionieren wie mein tado-platform

Das Problem sollte dann auch behoben sein

**Comment by SeydX** [comment]
Hey magst du evtl die Beta Version zu v4 testen?

https://github.com/SeydX/homebridge-fritz-platform/issues/30

**Comment by schweden1997** [comment]
Ja kann ich gerne machen 👍

**Comment by SeydX** [comment]
v4 ist online
