### ISSUE TITLE
Reboot Toggle don't work

### ISSUE THREAD

**Issue by Krocko** [SeydX/homebridge-fritz-platform#25]
Hi @SeydX. 
Thanks for this really great plugin (like all of your plugins 😄). 
For me the reboot toggle don’t work. 
I have a 7590 with firmware 7.10.

**Comment by SeydX** [comment]
Hey, you mean the "extendedReboot" or the normal reboot via Switch in Home App ?

If you mean the Switch in Home App and NOT "extendedReboot" you need to set "readOnlySwitches" to false

https://github.com/SeydX/homebridge-fritz-platform/blob/master/docs/Telegram.md#markdown

**Comment by Krocko** [comment]
I mean the normal reboot switch. "readOnlySwitches"  is already false. 
But I have set "extendedReboot" to true also. If i switch the toggle, nothing happened.

**Comment by SeydX** [comment]
@Krocko 

can you post your log and config pls

**Comment by Krocko** [comment]
config. json

`{
   "bridge":{
      "name":"Homebridge-fritz",
      "username":"CC:22:3D:E3:CE:33",
      "port":42840,
      "pin":"031-45-154"
   },
   "plugins":[
      "homebridge-fritz-platform"
   ],
   "accessories":[

   ],
   "platforms":[
      {
         "platform":"FritzPlatform",
         "devices":{
            "FritzBox":{
               "host":"xxx.xxx.xx.x",
               "port":49000,
               "username":"xxxxx",
               "password":"xxxxx",
               "type":"dsl",
               "wifi2":true,
               "wifi5":true,
               "wifiGuest":true,
               "phoneBook":true,
               "wps":true,
               "aw":true,
               "deflection":true,
               "led":true,
               "lock":true,
               "beta":true,
               "mesh":false,
               "master":true
            }
         },
         "callmonitor":{
            "active":true,
            "ip":"xxx.xxx.xx.x",
            "port":1012,
            "country":"DE",
            "incomingTo":false,
            "outgoingFrom":false
         },
         "presence":{
            "A":"asdghjklö",
            "B":"asghkllbb",
            "C":"dgjlmnvcfgui"
         },
         "wol":{

         },
         "alarm":{
            "active":true,
            "telNr":"1234567890",
            "duration":30
         },
         "wakeup":{
            "active":true,
            "internNr":"**xxx",
            "duration":60
         },
         "ringlock":{
            "active":true,
            "DECTphones":1,
            "start":"21:00",
            "end":"06:00"
         },
         "broadband":{
            "active":false,
            "measureTime":5,
            "polling":30
         },
         "extReboot":{
            "active":true,
            "cmdOn":"sh /var/homebridge/homebridge-fritz/reboot-start.sh",
            "cmdOff":"sh /var/homebridge/homebridge-fritz/reboot-finished.sh"
         },
         "telegram":{
            "active":true,
            "token":"xxxxxxx:xxxxxxx",
            "chatID":"xxxxxxxxx",
            "presence":{
               "in":"*Homebridge FRITZ!Box:* \nWillkommen zu Hause _@_",
               "out":"*Homebridge FRITZ!Box:* \nAuf Wiedersehen _@_",
               "anyoneOut":"*Homebridge FRITZ!Box:* \nNiemand zu Hause!"
            },
            "callmonitor":{
               "incoming":"*Homebridge FRITZ!Box:* \nAnkommender Anruf! \n_@_",
               "disconnected":"*Homebridge FRITZ!Box:* \nAnruf mit \n_@_ \nwurde beendet!"
            }
         },
         "readOnlySwitches":false,
         "anyone":false,
         "delay":180,
         "onDelay":15,
         "polling":5,
         "timeout":5
      }
   ]
}`

log:
`Apr 24 14:15:37 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Apr 24 14:15:43 raspberrypi homebridge[19315]: Loaded config.json with 0 accessories and 1 platforms.
Apr 24 14:15:43 raspberrypi homebridge[19315]: ---
Apr 24 14:15:43 raspberrypi homebridge[19315]: Plugin /usr/local/lib/node_modules/homebridge-fritz-platform requires Node version of ^10.15.3 which does not satisfy the current Node version of v11.14.0. You may need to upgrade your installation of Node.
Apr 24 14:15:43 raspberrypi homebridge[19315]: Loaded plugin: homebridge-fritz-platform
Apr 24 14:15:46 raspberrypi homebridge[19315]: Registering platform 'homebridge-fritz-platform.FritzPlatform'
Apr 24 14:15:46 raspberrypi homebridge[19315]: ---
Apr 24 14:15:46 raspberrypi homebridge[19315]: Loading 1 platforms...
Apr 24 14:15:46 raspberrypi homebridge[19315]: [FritzPlatform] Initializing FritzPlatform platform...
Apr 24 14:15:46 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] **************************************************************
Apr 24 14:15:46 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] FritzPlatform v3.2.2 by SeydX
Apr 24 14:15:46 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] GitHub: https://github.com/SeydX/homebridge-fritz-platform
Apr 24 14:15:46 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] Email: seyd55@outlook.de
Apr 24 14:15:46 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] **************************************************************
Apr 24 14:15:46 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] start success...
Apr 24 14:15:46 raspberrypi homebridge[19315]: Loading 0 accessories...
Apr 24 14:15:46 raspberrypi homebridge[19315]: Setup Payload:
Apr 24 14:15:46 raspberrypi homebridge[19315]: X-HM://0023ISYWYL770
Apr 24 14:15:46 raspberrypi homebridge[19315]: Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]:                                                       
Apr 24 14:15:47 raspberrypi homebridge[19315]: Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
Apr 24 14:15:47 raspberrypi homebridge[19315]:                        
Apr 24 14:15:47 raspberrypi homebridge[19315]:     ┌────────────┐     
Apr 24 14:15:47 raspberrypi homebridge[19315]:     │ 031-45-154 │     
Apr 24 14:15:47 raspberrypi homebridge[19315]:     └────────────┘     
Apr 24 14:15:47 raspberrypi homebridge[19315]:                        
Apr 24 14:15:47 raspberrypi homebridge[19315]: Homebridge is running on port 42840.
Apr 24 14:15:51 raspberrypi homebridge[19315]: [FritzPlatform] [INIT] Device initialized: Router
Apr 24 14:15:51 raspberrypi homebridge[19315]: [FritzPlatform] [INIT] Encrypted communication started with: Router
Apr 24 14:15:53 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] Initializing platform...
Apr 24 14:15:53 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] Configuring accessory: FritzBox
Apr 24 14:15:53 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] Configuring Device LED for beta firmware...
Apr 24 14:15:53 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] Refreshing phone book...
Apr 24 14:15:53 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] Configuring accessory: A
Apr 24 14:15:53 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] Configuring accessory: B
Apr 24 14:15:53 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] Configuring accessory: C
Apr 24 14:15:53 raspberrypi homebridge[19315]: [FritzPlatform] [INIT] Callmonitor connection established with xxx.xxx.xx.x:1012
Apr 24 14:15:53 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] Configuring accessory: Callmonitor Incoming
Apr 24 14:15:54 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] Configuring accessory: Callmonitor Outgoing
Apr 24 14:15:56 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] Found 1 book! Fetching entries...
Apr 24 14:16:00 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] Found 144 entries in phone book. Setting it to storage!
Apr 24 14:22:16 raspberrypi homebridge[19315]: [FritzPlatform] [INFO] FritzBox: Initialising reboot...
Apr 24 14:22:16 raspberrypi sudo[24276]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl stop homebridge
Apr 24 14:22:16 raspberrypi sudo[24276]: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 24 14:22:22 raspberrypi sudo[24276]: pam_unix(sudo:session): session closed for user root
Apr 24 14:22:22 raspberrypi sudo[24370]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl stop homebridge-cmd
Apr 24 14:22:22 raspberrypi sudo[24370]: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 24 14:22:27 raspberrypi sudo[24370]: pam_unix(sudo:session): session closed for user root
Apr 24 14:22:27 raspberrypi sudo[24404]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl stop homebridge-hue
Apr 24 14:22:27 raspberrypi sudo[24404]: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 24 14:22:32 raspberrypi sudo[24404]: pam_unix(sudo:session): session closed for user root
Apr 24 14:22:32 raspberrypi sudo[24483]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl stop homebridge-fritz
Apr 24 14:22:32 raspberrypi sudo[24483]: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 24 14:22:32 raspberrypi systemd[1]: Stopping Node.js HomeKit Server...
Apr 24 14:22:32 raspberrypi homebridge[19315]: Got SIGTERM, shutting down Homebridge...
Apr 24 14:22:37 raspberrypi systemd[1]: homebridge-fritz.service: Main process exited, code=exited, status=143/n/a
Apr 24 14:22:37 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Apr 24 14:22:37 raspberrypi systemd[1]: homebridge-fritz.service: Unit entered failed state.
Apr 24 14:22:37 raspberrypi systemd[1]: homebridge-fritz.service: Failed with result 'exit-code'.
Apr 24 14:22:37 raspberrypi sudo[24483]: pam_unix(sudo:session): session closed for user root
`

**Comment by SeydX** [comment]
can you post your reboot.sh files pls

**Comment by Krocko** [comment]
Found a mistake.
Had wrongly the fritz instance in the reboot-start.sh.
Now the router is rebooting but i get the following error in the log.

`Apr 24 16:10:23 raspberrypi homebridge[25228]: [FritzPlatform] [INFO] FritzBox: All homebridge instances were stopped! Preparing for reboot...
Apr 24 16:10:23 raspberrypi homebridge[25228]: TypeError: Cannot read property 'start' of undefined
Apr 24 16:10:23 raspberrypi homebridge[25228]:     at /usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/device.js:592:101
Apr 24 16:10:23 raspberrypi homebridge[25228]:     at /usr/local/lib/node_modules/homebridge-fritz-platform/lib/Service.js:284:15
Apr 24 16:10:23 raspberrypi homebridge[25228]:     at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/xml2js/lib/parser.js:303:18)
Apr 24 16:10:23 raspberrypi homebridge[25228]:     at Parser.emit (events.js:193:13)
Apr 24 16:10:23 raspberrypi homebridge[25228]:     at SAXParser.onclosetag (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/xml2js/lib/parser.js:261:26)
Apr 24 16:10:23 raspberrypi homebridge[25228]:     at emit (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/sax/lib/sax.js:624:35)
Apr 24 16:10:23 raspberrypi homebridge[25228]:     at emitNode (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/sax/lib/sax.js:629:5)
Apr 24 16:10:23 raspberrypi homebridge[25228]:     at closeTag (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/sax/lib/sax.js:889:7)
Apr 24 16:10:23 raspberrypi homebridge[25228]:     at SAXParser.write (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/sax/lib/sax.js:1436:13)
Apr 24 16:10:23 raspberrypi homebridge[25228]:     at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/xml2js/lib/parser.js:322:31)

**Comment by Krocko** [comment]
reboot-start

**Comment by SeydX** [comment]
Should be fixed with v3.2.3

**Comment by Krocko** [comment]
The Reboot of the Fritzbox and the restart of the instances are working now.
Thank you. 
The following errors are ok?

```
Apr 25 09:07:16 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m [ERROR] FritzBox: An error occured while fetching SID, trying again in 30 seconds...
Apr 25 09:07:16 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m [ERROR] {
Apr 25 09:07:16 raspberrypi homebridge[17486]:     "error": "ESOCKETTIMEDOUT",
Apr 25 09:07:16 raspberrypi homebridge[17486]:     "errorCode": "ESOCKETTIMEDOUT",
Apr 25 09:07:16 raspberrypi homebridge[17486]:     "serviceType": "urn:dslforum-org:service:DeviceConfig:1",
Apr 25 09:07:16 raspberrypi homebridge[17486]:     "action": "X_AVM-DE_CreateUrlSID"
Apr 25 09:07:16 raspberrypi homebridge[17486]: }
Apr 25 09:07:17 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m [ERROR] FritzBox: An error occured while getting new host list, trying again in 15 seconds...
Apr 25 09:07:17 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m [ERROR] {
Apr 25 09:07:17 raspberrypi homebridge[17486]:     "errorCode": "ESOCKETTIMEDOUT"
Apr 25 09:07:17 raspberrypi homebridge[17486]: }
Apr 25 09:07:18 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m [ERROR] FritzBox: An error occured while getting WIFI Guest state!
Apr 25 09:07:18 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m [ERROR] {
Apr 25 09:07:18 raspberrypi homebridge[17486]:     "error": "ECONNREFUSED",
Apr 25 09:07:18 raspberrypi homebridge[17486]:     "errorCode": "ECONNREFUSED",
Apr 25 09:07:18 raspberrypi homebridge[17486]:     "serviceType": "urn:dslforum-org:service:WLANConfiguration:3",
Apr 25 09:07:18 raspberrypi homebridge[17486]:     "action": "GetInfo"
Apr 25 09:07:18 raspberrypi homebridge[17486]: }
Apr 25 09:07:19 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m #033[33m[WARN] FritzBox: Can not reach xx.xx.xx.x:49000 - Trying again in 60 seconds...#033[39m
Apr 25 09:07:28 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m #033[33m[WARN] FritzBox: Can not reach xxx.xxx.xx.x:49000 - Trying again in 60 seconds...#033[39m
Apr 25 09:07:28 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m #033[33m[WARN] FritzBox: Can not reach xxx.xxx.xx.x:49000 - Trying again in 60 seconds...#033[39m
Apr 25 09:07:29 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m [WARN] Callmonitor connection were closed!
Apr 25 09:07:29 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m #033[33m[WARN] FritzBox: Can not reach xxx.xx.xx.x:49000 - Trying again in 60 seconds...#033[39m
Apr 25 09:07:31 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m #033[33m[WARN] FritzBox: Can not reach xxx.xxx.xx.x:49000 - Trying again in 60 seconds...#033[39m
Apr 25 09:07:32 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m #033[33m[WARN] FritzBox: Can not reach xxx.xxx.xx.x:49000/devicehostlist.lua?sid=15f1a59f8083e805 - Trying again in 30 seconds#033[39m
Apr 25 09:07:36 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m #033[33m[WARN] FritzBox: Can not reach xxx.xxx.xx.x:49000 - Trying again in 60 seconds...#033[39m
Apr 25 09:07:36 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m [ERROR] FritzBox:An error occured while getting Ring Lock for Phone 1
Apr 25 09:07:36 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m [ERROR] {
Apr 25 09:07:36 raspberrypi homebridge[17486]:     "error": "ECONNREFUSED",
Apr 25 09:07:36 raspberrypi homebridge[17486]:     "errorCode": "ECONNREFUSED"
Apr 25 09:07:36 raspberrypi homebridge[17486]: }
Apr 25 09:07:46 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m #033[33m[WARN] FritzBox fetchSID: Can not reach xxx.xxx.xx.x:49000 - Trying again in 30 seconds...#033[39m
Apr 25 09:07:52 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m [ERROR] FritzBox: An error occured while getting Device Lock state!
Apr 25 09:07:52 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m [ERROR] {
Apr 25 09:07:52 raspberrypi homebridge[17486]:     "error": "ECONNREFUSED",
Apr 25 09:07:52 raspberrypi homebridge[17486]:     "errorCode": "ECONNREFUSED"
Apr 25 09:07:52 raspberrypi homebridge[17486]: }
Apr 25 09:07:56 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m [ERROR] FritzBox: An error occured while getting LED Beta state!
Apr 25 09:07:56 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m [ERROR] {
Apr 25 09:07:56 raspberrypi homebridge[17486]:     "error": "ECONNREFUSED",
Apr 25 09:07:56 raspberrypi homebridge[17486]:     "errorCode": "ECONNREFUSED"
Apr 25 09:07:56 raspberrypi homebridge[17486]: }
Apr 25 09:08:02 raspberrypi homebridge[17486]: #033[36m[FritzPlatform]#033[39m #033[33m[WARN] FritzBox: Can not reach xxx.xxx.xx.x:49000/devicehostlist.lua?sid=15f1a59f8083e805 - Trying again in 30 seconds#033[39m
```

**Comment by Krocko** [comment]
Schould we get a Telegram notification for the extended reboot?
This don‘t work also.  

If you need any other log or files, let me know.

**Comment by SeydX** [comment]
@Krocko

The error you got is normal after toggling reboot

Because the router is not available at reboot, therefore you got ETIMEDOUT/ESOCKETTIMEDOUT etc

**Comment by Krocko** [comment]
Thank you for clarification. 
Can you say something to my previous post?
Schould we get Telegram notifications for the extended reboot? Saw something in the code.

**Comment by SeydX** [comment]
@Krocko 

It is possible to get telegram notification

See https://github.com/SeydX/homebridge-fritz-platform/blob/master/docs/config/Telegram.md

‚extReboot‘

**Comment by Krocko** [comment]
Sorry to annoying you. 
Now I got this error. 

```
Apr 26 21:36:41 raspberrypi homebridge[23412]: [FritzPlatform] [ERROR] An error occured by sending telegram notification!
Apr 26 21:36:41 raspberrypi homebridge[23412]: TypeError: JSON.stringlockify is not a function
Apr 26 21:36:41 raspberrypi homebridge[23412]:     at Request._callback (/usr/local/lib/node_modules/homebridge-fritz-platform/src/platform.js:977:36)
Apr 26 21:36:41 raspberrypi homebridge[23412]:     at Request.self.callback (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/request/request.js:185:22)
Apr 26 21:36:41 raspberrypi homebridge[23412]:     at Request.emit (events.js:193:13)
Apr 26 21:36:41 raspberrypi homebridge[23412]:     at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/request/request.js:1161:10)
Apr 26 21:36:41 raspberrypi homebridge[23412]:     at Request.emit (events.js:193:13)
Apr 26 21:36:41 raspberrypi homebridge[23412]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/request/request.js:1083:12)
Apr 26 21:36:41 raspberrypi homebridge[23412]:     at Object.onceWrapper (events.js:281:20)
Apr 26 21:36:41 raspberrypi homebridge[23412]:     at IncomingMessage.emit (events.js:198:15)
Apr 26 21:36:41 raspberrypi homebridge[23412]:     at endReadableNT (_stream_readable.js:1139:12)
Apr 26 21:36:41 raspberrypi homebridge[23412]:     at processTicksAndRejections (internal/process/task_queues.js:81:17)

```

**Comment by SeydX** [comment]
@Krocko 

should be fixed with v3.2.4

**Comment by Krocko** [comment]
The error is gone. But no Telegram notification is sending. 
I think it is the timing. The router is already in the reboot process and the sending of the notification is to late. 

```
Apr 26 22:12:44 raspberrypi homebridge[27885]: [FritzPlatform] [INFO] FritzBox: All homebridge instances were stopped! Preparing for reboot...
Apr 26 22:12:44 raspberrypi homebridge[27885]: [FritzPlatform] [INFO] Router is restarting 
Apr 26 22:12:44 raspberrypi homebridge[27885]: [FritzPlatform] [INFO] FritzBox: Homebridge instances will be restarted automatically in 5 minutes!
Apr 26 22:12:44 raspberrypi homebridge[27885]: [FritzPlatform] [INFO] FritzBox: Rebooting...
Apr 26 22:12:44 raspberrypi homebridge[27885]: [FritzPlatform] [ERROR] An error occured by sending telegram notification!
Apr 26 22:12:44 raspberrypi homebridge[27885]: [FritzPlatform] [ERROR] {
Apr 26 22:12:44 raspberrypi homebridge[27885]:     "error": "Bad Request",
Apr 26 22:12:44 raspberrypi homebridge[27885]:     "errorCode": 400
Apr 26 22:12:44 raspberrypi homebridge[27885]: }

```

**Comment by SeydX** [comment]
@Krocko 

It seems your token /chat id maybe not correct, the plugin tried already to send, but due to a config error (chatID or Token or message) it pushes an error

**Comment by Krocko** [comment]
The other notifications (presence, callmonitor) are working. 
So I don‘t think it is the Token/Chat ID.

**Comment by summerset77** [comment]
@SeydX 
Can you explain, what is the trigger for the Fritz Box reboot? There is no Toogle in the homebridge available.

Works this function with FritzBox Firmware Revision 7.21?

Many thanks and best regards.
