### ISSUE TITLE
Markdown feature for Telegram notifications 

### ISSUE THREAD

**Issue by Krocko** [SeydX/homebridge-fritz-platform#26]
Is it possible for you to add the markdown feature for the telegram notifications?
Would be really nice.

**Comment by SeydX** [comment]
Hey,

v3.2.2 is online with markdown support

below you can find more information about markdown

https://github.com/SeydX/homebridge-fritz-platform/blob/master/docs/Telegram.md#markdown

**Comment by Krocko** [comment]
That was quick!
You are awesome!!!
Thank you.
