### ISSUE TITLE
Provide HomeKit switch for Guest Wifi

### ISSUE THREAD

**Issue by jannnik** [SeydX/homebridge-fritz-platform#27]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to have a switch to enable the Guest WiFi via HomeKit App without using any third party app.

**Comment by Binog** [comment]
hätte ich auch gerne !!!

**Comment by SeydX** [comment]
Will be added in v4 - currently in work

**Comment by SeydX** [comment]
Added in v4

**Comment by SeydX** [comment]
See https://github.com/SeydX/homebridge-fritz-platform/blob/master/docs/config/FritzBox.md

**Comment by ChrWi** [comment]
@SeydX I have installed latest v4.10 - with a fritzbox 7490 running on v07.11. Everything is fine, incl. Smarthome (FRITZ!DECT 200, incl. Temperature), 1260 Repeater etc. Only wifi ist not visible at all using configuration according to documentation:
"wifiGuest": [
                            true,
                            false
                        ]
On the fritzbox everything is set incl. WPA key - using e.g. homebridge-fritz plugin give me a working Wifi Guest switch right away.
