### ISSUE TITLE
node 10 

### ISSUE THREAD

**Issue by Binog** [SeydX/homebridge-fritz-platform#28]
hey, I do get this warning:

Plugin /usr/lib/node_modules/homebridge-fritz-platform requires Node version of ^10.15.3 which does not satisfy the current Node version of v8.11.1. You may need to upgrade your installation of Node.

what could I do? how to update this. apt-get says it is uptodate. and I thought I installed it via apt-get.

thank you !!

**Comment by SeydX** [comment]
You can ignore this if your node version is already above v8
