### ISSUE TITLE
Wifi Units 7590 AX

### ISSUE THREAD

**Issue by solbadguy2010** [seydx/homebridge-fritz-platform#284]
Can you please explain where to get the correct value for „WifiUnits“? I guessed for my 540E one unit, for my 1750E two units and for my 3000 three units. But for my 7590 AX i do not know what to choose. It has Wifi 4,5 and 6, but set to three WifiUnits it crashes the Plugin. Two work, but i think it is wrong?

by the way, what does this value exactly?

**Comment by Gummibando** [comment]
2 is correct for the 7590ax.
"WifiUnits" refers to the distinct WiFi hardware units of the device (WiFi 4, 5, 6 is "just" the WiFi standard).
7590ax has 2 units, one for 2.4 GHz, one for 5 GHz.
The Repeater 3000 has two 5 GHz units in addition to the 2.4 GHz unit, hence 3 total.
(Reason: in wireless repeater mode, the 3000 would use one 5 GHz unit to connect to the main Fritzbox, while clients would connect to the other unit.)

**Comment by solbadguy2010** [comment]
@Gummibando Great! thank you! This helps me to understand this. Does the 1750E also have 3 Units?

and do you know wich effect a „wrong“ setting in the plugin has? Does this really change anything?

**Comment by Gummibando** [comment]
The 1750e is, IIRC, a dual-band repeater.

**Comment by solbadguy2010** [comment]
@Gummibando Thank you! That helps. Do you know what happens when i configure „WifiUnits=2“ for the 3000 for example? Will that change something that matters?

**Comment by Gummibando** [comment]
You can expose the WiFi modules/band as a switch (enable/disable WiFi band) in HomeKit.
If you set the number lower than the actual number of WiFi modules, I assume the additional WiFi band will not be available as a switch.
