### ISSUE TITLE
Version 4 - Bugfix Thread

### ISSUE THREAD

**Issue by SeydX** [SeydX/homebridge-fritz-platform#30]
Hey everyone,

as some of you may know, I am currently working on the v4 of my Fritz Platform plugin. Most of it is already done. Currently I'm looking for beta testers to wipe out the remaining bugs and / or incorporate new requests.

**Note:** Before you install the new plugin, I recommend you to delete the old plugin and remove it from HomeKit! And also delete the accessories and persist folders (only if u are using the v3.x)

The new version is completely rewritten, supports async/await and should be faster than the previous versions. It has a auto config generator and detects automatically all FRITZ!Box devices in the network.  I fixed also some bugs and improved i.e smarthome etc (i can‘t test smarthome properly due to the reason i don‘t have smarthome devices here, so every bug is welcome)

~~The plugin supports at the moment only devices with MESH! Devices without MESH will be added very soon!~~

To install the beta version, run following command

```
sudo npm i -g homebridge-fritz-platform@dev
```

Here you will find some information about first steps with version 4

https://github.com/SeydX/homebridge-fritz-platform/blob/dev/FIRSTSTART.md

**Comment by Krocko** [comment]
Hello @SeydX.
I am currently testing the beta. The plugin runs in a separate instance. If i stop this instance i got the following error every 2 minutes:
```
May 11 17:28:00 raspberrypi homebridge[449]: Error: from server 192.168.88.45:42840 Error: connect ECONNREFUSED 192.168.88.45:42840
May 11 17:28:00 raspberrypi homebridge[449]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14) {
May 11 17:28:00 raspberrypi homebridge[449]:   errno: 'ECONNREFUSED',
May 11 17:28:00 raspberrypi homebridge[449]:   code: 'ECONNREFUSED',
May 11 17:28:00 raspberrypi homebridge[449]:   syscall: 'connect',
May 11 17:28:00 raspberrypi homebridge[449]:   address: '192.168.88.45',
May 11 17:28:00 raspberrypi homebridge[449]:   port: 42840
May 11 17:28:00 raspberrypi homebridge[449]: }

```

**Comment by SeydX** [comment]
@Krocko 

You got the error AFTER stopping it ? Or which instance do you stopping and from which instance you got the error?

**Comment by Krocko** [comment]
Yes, after stopping it.
The error is in the syslog and your instances plugin sends the telegram message for the error too.

![IMG_3638](https://user-images.githubusercontent.com/29394115/57571895-0004e700-7414-11e9-9edb-09aad64380f5.png)

**Comment by SeydX** [comment]
Can u post the whole log pls before and after stopping the instance

**Comment by Krocko** [comment]
Sure. But can we do this in private?
Are you on Slack?

**Comment by SeydX** [comment]
Yes

**Comment by Krocko** [comment]
OK.
I wrote you a private message on the homebridge slack

**Comment by Krocko** [comment]
Problem solved by rebooting all homebridge instances.

**Comment by BigKrisch** [comment]
Dev version 16 will always return the error message "[ERROR] Can not confirm master device!" output, although in the config.json the Fritz! Box is indicated as master.

`[2019-5-19 12:37:17] [FritzPlatform] [INFO] Initializing config...
[2019-5-19 12:37:17] [FritzPlatform] [INFO] Callmonitor connection established with 192.168.1.1:1012
[2019-5-19 12:37:17] [FritzPlatform] [INFO] Found 23 active devices...
[2019-5-19 12:37:19] [FritzPlatform] [ERROR] Can not confirm master device!`

` "FritzBox7580": {
                    "active": true,
                    "host": "192.168.1.1",
                    "port": 49000,
                    "username": "XXX",
                    "password": "XXX",
                    "type": "dsl",
                    "master": true,
                    "mesh": true,
                    "readOnly": true,
                    "options": {
                        "reconnect": true,
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            true
                        ],
                        "phoneBook": true,
                        "wps": [
                            true,
                            false
                        ],
                        "aw": [
                            true,
                            false
                        ],
                        "deflection": [
                            true,
                            true
                        ],
                        "led": [
                            true,
                            false
                        ],
                        "lock": [
                            true,
                            false
                        ]
                    }
                }`

**Comment by SeydX** [comment]
@BigKrisch 

Which FritzBox do u have? And what kind of setup? Cable? Dsl? Fiber?

**Comment by BigKrisch** [comment]
@SeydX 

I have a FritzBox 7580 with fiber which is connected via the WAN port with the fiber optic modem.

**Comment by SeydX** [comment]
@BigKrisch 

can u try dev17 pls

**Comment by BigKrisch** [comment]
Now it worked. THX!

However, I now get the following error message after the restart. The message comes with the repeaters 1750E and 3000. The 1750E run with the FritzOS 7.10 and the 3000 with the current laboratory version (07.08-67677 BETA).
For the repeaters 1160 which also run with the laboratory version (07.08-68397 BETA) the error message does not come.

> [2019-5-19 17:30:45] [FritzPlatform] [ERROR] FRITZWLAN-Repeater-3000-ESSZIMMER: An error occured while checking firmware!
[2019-5-19 17:30:45] [FritzPlatform] [ERROR] FRITZWLAN-Repeater-3000-WOHNZIMMER: An error occured while checking firmware!
[2019-5-19 17:30:45] [FritzPlatform] [ERROR] FRITZWLAN-Repeater-1750E-KAMMERL: An error occured while checking firmware!
[2019-5-19 17:30:45] [FritzPlatform] [ERROR] FRITZWLAN-Repeater-1750E-KUECHE: An error occured while checking firmware!
[2019-5-19 17:30:45] [FritzPlatform] [ERROR] FRITZWLAN-Repeater-1750E-ELTERN: An error occured while checking firmware!
[2019-5-19 17:30:45] [FritzPlatform] [ERROR] FRITZWLAN-Repeater-1750E-ELTERN-2: An error occured while checking firmware!

In addition, the following information message is displayed:

> [2019-5-19 17:30:43] [FritzPlatform] [INFO] FritzBox7580: An error occured while initializing accessory services and characteristics!

**Comment by SeydX** [comment]
Its because of the connection type, need to debug more... have u slack or something else where we can debug this? can u install this pls 

https://github.com/SeydX/fritzplatform-util

**Comment by BigKrisch** [comment]
The debug tool is installed.
I have Slack on the Mac, but never used it. But I can try it.

**Comment by SeydX** [comment]
need your name on slack

**Comment by BigKrisch** [comment]
Its BigKrisch

**Comment by SeydX** [comment]
can u join here pls

https://join.slack.com/t/hbfritzplatform/shared_invite/enQtNjQxNzY1MjMxMDc5LTRjNjVhOTAxNjdlZGEyODk3ZTc2NzE2NGQ1NjBhNTEyMjJjOTEwN2QzMTAzMGViYzkwZTQ2OTY0YjUyMWNjNWQ

**Comment by frahli** [comment]
Hi,

the plugin is working fine. But my thermos aren't found at all. This is my smarthome-part in the config.json:

`                "Wohnzimmer TV": {
                    "type": "thermo",
                    "ain": "099950140858",
                    "heatValue": 5,
                    "coolValue": 5,
                    "windowSensor": false
                },
                "Wohnzimmer Sofa": {
                    "type": "thermo",
                    "ain": "099950140966",
                    "heatValue": 5,
                    "coolValue": 5,
                    "windowSensor": false
                },
                "Kinderzimmer Anna": {
                    "type": "thermo",
                    "ain": "119601032712",
                    "heatValue": 5,
                    "coolValue": 5,
                    "windowSensor": false
                },
                "Kinderzimmer Marie": {
                    "type": "thermo",
                    "ain": "119601000424",
                    "heatValue": 5,
                    "coolValue": 5,
                    "windowSensor": false
                }`

**Comment by SeydX** [comment]
@frahli 

As u can see here

https://github.com/SeydX/homebridge-fritz-platform/blob/master/docs/config/Smarthome.md

Its called ‚thermostat‘ now AND type needs to be changed to devType

**Comment by frahli** [comment]
Hi,
I did the following changes, but ther thermos arent found, yet :-(

> "Wohnzimmer TV": {
                    "active": true,
                    "devtype": "thermostat",
                    "ain": "099950140858",
                    "heatValue": 5,
                    "coolValue": 5,
                    "windowSensor": false
                },

**Comment by SeydX** [comment]
Closing this beta thread

Please open own thread if you have issues

Thanks
