### ISSUE TITLE
miscellaneous

### ISSUE THREAD

**Issue by Binog** [SeydX/homebridge-fritz-platform#31]
**Describe the bug**
not working switches,..

**To Reproduce**
I have pretty much the standard config

**Screenshots**
![IMG_20CE7E88EA99-1](https://user-images.githubusercontent.com/11355616/57543979-485dcf80-7356-11e9-892f-1461060a1dd7.jpeg)

**Desktop (please complete the following information):**
 - OS: [latest]
 - Browser [eve app]

unclear statements:
incoming and outgoing calls shows yes or no,. it actually shows yes, but there have been none.
presences are shown as away, although all are present.

is there a possibility to add e.g. the GuestWifi tap to the generell screen. I can add it as a scene, but not as a switch/bottom in the home-screen of e.g. eve-app or apples home-app.

Config: 
`        {
            "platform": "FritzPlatform",
            "devices": {
                "FritzBox": {
                    "name": "Fritz common name",
                    "master": true,
                    "host": "x.x.x.1",
                    "username": "me",
                    "password": "password",
                    "type": "cable",
                    "wifi2": false,
                    "wifi5": false,
                    "wifiGuest": true,
                    "phoneBook": true,
                    "wps": false,
                    "aw": true,
                    "deflection": false,
                    "led": true,
                    "lock": false,
                    "strictSSL": true,
                    "beta": false,
                    "mesh": false,
                    "presence": {
                        "me": "10.0.1.15",
                        "you": "10.0.1.3",
                        "Anyone": ""
                    },
                    "anyone": true,
                    "delay": 90,
                    "onDelay": 15
                }
            }
        },`

Do I have forgotten anything?

**Comment by SeydX** [comment]
Should be fixed in v4

**Comment by SeydX** [comment]
Fixed in v4
