### ISSUE TITLE
Direktverbindung zur Fritzbox nötig?

### ISSUE THREAD

**Issue by etcg** [SeydX/homebridge-fritz-platform#33]
Hallo,

ist es mit V4 nötig, dass die Homebridge direkt mit der Fritzbox verbunden sein muss? Mein Setup ist nämlich: Homebridge --> Router --> Fritzbox statt Homebridge --> Fritzbox. In Version 3 hat das sehr gut so funktioniert. Mit V4 geht es nicht, trotz manueller Eingabe der devices. Sie werden nach jedem Homebridge Restart wieder gelöscht. Ein Test ohne den Router als Mittelglied hat gut funktioniert, nach Umstellung des WLAN der Homebridge wieder zurück auf den Router wurden die devices jedoch wieder automatisch gelöscht.

**Comment by SeydX** [comment]
Hm habe ich nicht ganz verstanden, ist das Gerät wo das Plugin drauf läuft in einem anderen Netzwerk?

Das Plugin sucht alle im Netzwerk befindlichen Geräte automatisch und fügt diese in config ein

Womit ist dein homebridge nun verbunden?

**Comment by SeydX** [comment]
@etcg 

Kannst auch gerne in slack channel eintreten, da kann ich schneller behilflich sein, button dafür findest du auf der Hauptseite hier

**Comment by etcg** [comment]
Also ganz konkret dient die Fritzbox hier fast nur als Modem. An der Fritzbox ist über LAN ein weiterer Router (TP-Link) angeschlossen. Die Homebridge ist mit dem Router verbunden nicht direkt mit der Fritzbox. Es ist aber das gleiche Netzwerk. In diesem Setup findet das Plugin die Fritzbox nicht. Das war aber mit V3 noch möglich. Ein manuelles Eintragen ist nicht möglich, weil das automatische Skript die config immer wieder zurücksetzt.

**Comment by SeydX** [comment]
@etcg 

Verstehe, werde mal ne Funktion einbauen um die auto Suche zu entgehen und so quasi eigene Geräte einbinden zu können

**Comment by etcg** [comment]
Perfekt, genau so eine Funktion brauche ich. Danke. Sehr gutes Plugin btw. Hat bei mir immer auf Anhieb fehlerfrei funktioniert.

**Comment by SeydX** [comment]
v4.0.2 ist online, hier die Anleitung wie es ohne auto device search funktioniert

https://github.com/SeydX/homebridge-fritz-platform/blob/master/docs/FirstStart.md#1b-init-disabled-auto-device-search

**Comment by etcg** [comment]
Funktioniert auf den ersten Blick hervorragend. Vielen Dank für den schnellen Fix.

**Comment by SeydX** [comment]
Wunderbar
