### ISSUE TITLE
Fritzbox does not show up since v4

### ISSUE THREAD

**Issue by daberlin** [SeydX/homebridge-fritz-platform#34]
**Describe the bug**
Before v4 my fritzbox showed up, since v4 is does not. Config checked and valid!

**Comment by SeydX** [comment]
@daberlin 

Can u post your config pls

**Comment by daberlin** [comment]
Currently I'm using this hand-tailored config, but tried with the automatic one as well.
When I disable "clearCache" my config gets overwritten with useless defaults on every start.
The setting of "disableAutoSearch" does not change anything: nothing shows up.
        {
            "platform": "FritzPlatform",
            "name": "FritzBox",
            "devices": {
                "FritzBox": {
                    "active": true,
                    "host": "fritz.box",
                    "port": 49000,
                    "username": "xxxxx",
                    "password": "x",xxxx
                    "type": "cable",
                    "master": true,
                    "mesh": true,
                    "readOnly": false,
                    "options": {
                        "wifiGuest": [
                            true,
                            true
                        ],
                        "wps": [
                            true,
                            true
                        ]
                    }
                },
                "FritzRepeater-A": {
                    "active": false,
                    "host": "fritzrepeater-a",
                    "port": 49000,
                    "username": "",
                    "password": "",
                    "type": "repeater",
                    "master": false,
                    "mesh": true,
                    "readOnly": true,
                    "options": false
                },
                "FritzRepeater-B": {
                    "active": false,
                    "host": "fritzrepeater-b",
                    "port": 49000,
                    "username": "",
                    "password": "",
                    "type": "repeater",
                    "master": false,
                    "mesh": true,
                    "readOnly": true,
                    "options": false
                }
            },
            "alarm": {
                "active": false
            },
            "broadband": {
                "active": false
            },
            "callmonitor": {
                "active": false
            },
            "extReboot": {
                "active": false
            },
            "presence": {
                "user": [],
                "anyone": false,
                "onDelay": 15,
                "offDelay": 90
            },
            "ringlock": {
                "active": false
            },
            "smarthome": {},
            "telegram": {
                "active": false
            },
            "wakeup": {
                "active": false
            },
            "wol": [],
            "polling": 60,
            "timeout": 10,
            "clearCache": true,
            "debug": false,
            "disableAutoSearch": true
        },

**Comment by SeydX** [comment]
@daberlin 

clearCache MUST be disabled, otherwise the plugin will remove all accessories

The plugin offers a auto complete config feature

Show here

https://github.com/SeydX/homebridge-fritz-platform/blob/master/docs/FirstStart.md

**Comment by SeydX** [comment]
@daberlin 

new function added

"disableAutoConfig"

**Comment by SeydX** [comment]
@daberlin 

Any news on this?

**Comment by daberlin** [comment]
Works perfectly! Thanks a lot
