### ISSUE TITLE
Devices available, but greyed out and not updated

### ISSUE THREAD

**Issue by Phoenix-DH** [SeydX/homebridge-fritz-platform#35]
I have all devices in the homekit visible, but all are greyerd out and not updated.
In the homebridge log I find this:
[2019-5-22 09:35:16] [FritzPlatform] [INFO] Adding new accessory: FRITZ!Box 6490 Cable (kdg)
[2019-5-22 09:35:16] [FritzPlatform] [INFO] FRITZ!Box 6490 Cable (kdg): Successfully logged in!
[2019-5-22 09:35:17] [FritzPlatform] [INFO] Configuring accessory from cache: Rack
[2019-5-22 09:35:18] [FritzPlatform] [INFO] Configuring accessory from cache: Rack Temperature

Seems to be working for me ....

My config is:
        {
            "platform": "FritzPlatform",
            "devices": {
                "FRITZ!Box 6490 Cable (kdg)": {
                    "active": true,
                    "host": "XXX",
                    "port": 49000,
                    "username": "XXX",
                    "password": "XXX",
                    "type": "cable",
                    "master": true,
                    "mesh": false,
                    "readOnly": false,
                    "options": {
                        "reconnect": true,
                        "wifi2": [
                            false,
                            false
                        ],
                        "wifi5": [
                            false,
                            false
                        ],
                        "wifiGuest": [
                            false,
                            false
                        ],
                        "phoneBook": false,
                        "wps": [
                            false,
                            false
                        ],
                        "aw": [
                            false,
                            false
                        ],
                        "deflection": [
                            false,
                            false
                        ],
                        "led": [
                            false,
                            false
                        ],
                        "lock": [
                            false,
                            false
                        ]
                    }
                }
            },
            "smarthome": {
                "Rack": {
                    "active": true,
                    "ain": "XXX",
                    "tempSensor": true,
                    "devType": "switch"
                }
            },
            "broadband": {
                "active": true,
                "measureTime": 5
            },
            "callmonitor": {
                "active": false,
                "ip": "0.0.0.0",
                "port": 1012,
                "country": "",
                "incomingTo": [],
                "outgoingFrom": []
            },
            "presence": {
                "user": [
                    {
                        "active": false,
                        "name": "Test User",
                        "address": "0.0.0.0"
                    }
                ],
                "anyone": false,
                "offDelay": 90,
                "onDelay": 15
            },
            "wol": [
                {
                    "active": false,
                    "name": "Test Device",
                    "address": "00:00:00:00:00:00"
                }
            ],
            "alarm": {
                "active": false,
                "telNr": "",
                "duration": 30
            },
            "wakeup": {
                "active": false,
                "internNr": "",
                "duration": 30
            },
            "ringlock": {
                "active": false,
                "DECTphones": 1,
                "start": "11:00",
                "end": "22:00"
            },
            "extReboot": {
                "active": false,
                "cmdOn": "",
                "cmdOff": ""
            },
            "telegram": {
                "active": false,
                "token": "",
                "chatID": "",
                "presence": {
                    "in": "",
                    "out": "",
                    "anyoneIn": "",
                    "anyoneOut": ""
                },
                "callmonitor": {
                    "incoming": "",
                    "disconnected": ""
                },
                "alarm": {
                    "activated": "",
                    "deactivated": ""
                },
                "extReboot": {
                    "start": "",
                    "finish": ""
                }
            },
            "delay": 60,
            "OnDelay": 15,
            "polling": 5,
            "timeout": 5,
            "clearCache": false,
            "debug": true,
            "disableAutoSearch": false,
            "disableAutoConfig": false
        },

I have in addition to that the plugin homebridge-fritz-eve installed and a FritzBox with 7.01 and am not able to update.

With using the debug I get:
2019-05-22T07:47:17.811Z FritzPlatform Rack Temperature: No device with AIN: 087610136610 found or not intialized yet!
2019-05-22T07:47:22.811Z FritzPlatform Rack: No device with AIN: XXX found or not intialized yet!

The number is correct....

It seems that there is for me a problem connecting to the box correct.

**Comment by SeydX** [comment]
@Phoenix-DH 

does anything show up in home app?

**Comment by Phoenix-DH** [comment]
Yes, all are available, but greyed out and no values.

**Comment by bernd70** [comment]
Any news here? I have exactly the same issue after replacing my Fritzbox. All devices are fine except my DECT switch.

**Comment by ma2rco** [comment]
I have the same issue.
What i am seeing is that my Fritz!Box with release 7.12 is bringing up the "OK" for the TR064 request at the first time. But when the initialization of the smarthome devices is beginng, i can't see any "OK" Message. My Fritz!Repeater device is always bringing these messages. Without knowing the TR064 Protocol this ist like "Request" and "Reply" and i don't see these replies.

Aug 04 19:39:33 raspberrypi homebridge[6863]: 2019-08-04T18:39:33.950Z FritzPlatformTR064 [TR064 Debug] FRITZ!Box 7590 api request 1: get /upnp/control/deviceinfo
Aug 04 19:39:34 raspberrypi homebridge[6863]: 2019-08-04T18:39:34.036Z FritzPlatformTR064 [TR064 Debug] FRITZ!Box 7590 api request 1: Ok (authenticated)
Aug 04 19:39:34 raspberrypi homebridge[6863]: 2019-08-04T18:39:34.090Z FritzPlatform Master device successfully confirmed
Aug 04 19:39:34 raspberrypi homebridge[6863]: 2019-08-04T18:39:34.092Z FritzPlatform Initializing smarthome list
Aug 04 19:39:34 raspberrypi homebridge[6863]: 2019-08-04T18:39:34.097Z FritzPlatformTR064 [TR064 Debug] FRITZ!Box 7590 api request 1: get /upnp/control/deviceconfig
Aug 04 19:39:35 raspberrypi homebridge[6863]: 2019-08-04T18:39:35.103Z FritzPlatform Device initialization finished
Aug 04 19:39:35 raspberrypi homebridge[6863]: [8/4/2019, 7:39:35 PM] [FritzPlatform] [INFO] Configuring accessory from cache: FRITZ!Box 7590

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed/added in v5 (coming soon)
