### ISSUE TITLE
Probleme mit Presence und FB 6490 Cable

### ISSUE THREAD

**Issue by nexusle** [SeydX/homebridge-fritz-platform#39]
Hallo,

ich habe 3 iPhones bei mir als Presence Sensoren eingerichtet. Nun gibt es in der Fritzbox das Problem, dass WLAN-Geräte, die sich gar nicht am Router befinden, trotzdem noch als verbunden angezeigt werden. Das lässt natürlich das Plugin fälschlicherweise annehmen, dass das Gerät noch im Haus präsent ist. 

Kann hier weitere Abfrage in Form eines Ping eingebaut werden? Denn anpingen kann man das Gerät auf seine IP nicht mehr, auch wenn es die Fritzbox noch als verbunden anzeigt.

**Comment by SeydX** [comment]
wurde hinzugefügt. v4.1.0 ist online
