### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by skyguidedrs** [SeydX/homebridge-fritz-platform#4]
I get the following error:

[2018-8-9 16:32:47] [FritzBox] [ERROR] An error occured by initializing device, trying again...
[2018-8-9 16:32:47] [FritzBox] [ERROR] {
     "errno": "ECONNRESET",
     "code": "ECONNRESET",
     "syscall": "read"
 }

Probably, I've done something wrong. :-) I'm rather new to this.

My platforms section in config.json:
    "platforms": [
        {
            "platform": "FritzPlatform",
            "name": "FritzBox",
            "host": "192.168.77.1",
            "port": 444,
            "type": "cable",
            "timeout": 5,
            "username": "pi",
            "password": "test",
            "polling": 5
        }
    ]

**Comment by mchl-btlr** [comment]
I guess you have to use port 49000. Make sure you have enabled TR064 as described in the docs.

**Comment by SeydX** [comment]
can u try with v2.8 pls
