### ISSUE TITLE
PhoneBook config Eintrag bleibt nicht bestehen

### ISSUE THREAD

**Issue by nexusle** [SeydX/homebridge-fritz-platform#40]
Hallo nochmal,

der phoneBook-Config-Eintrag bleibt nicht bestehen. Ist das gewollt? (FB 6490 KDG)

Ich bilde mir ein, dass das mal funktionierte. Zumindest hatte ich irgendwann schon mal im Log "phonebook..." Einträge gesehen.

**Comment by Nastras** [comment]
https://forum.smartapfel.de/forum/thread/1658-homebridge-fritz-platform/?postID=59890#post59890

**Comment by SeydX** [comment]
sollte gefixt sein mit v4.1.0

**Comment by Nastras** [comment]
Bei mir läuft es wieder 👍

**Comment by nexusle** [comment]
Bei mir auch 👍🏼
