### ISSUE TITLE
Getting more and more a mess

### ISSUE THREAD

**Issue by BerkTam** [SeydX/homebridge-fritz-platform#41]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BerkTam** [comment]
This is getting more and more a mess. 

Before it worked so perfect and I dont know why always changing running systems?

**Comment by SeydX** [comment]
@BerkTam 

i dont understand, what is the problem?
