### ISSUE TITLE
Config Issue

### ISSUE THREAD

**Issue by Berlinologe86** [SeydX/homebridge-fritz-platform#43]
Hallo irgendwie will das plugin nicht mehr seit einem neuen update von der platform und ich bekomme die autoconfig Methode nicht hin und die alternativen bekomme ich in meine config.json nicht integriert. wenn ich meine alte config die funktioniert hat einfüge ändert er sie jedesmal wieder in diese hier 

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "platform": "Hue",
            "users": {
                "XXXXXXXX": "XXXXXXXX"
            },
            "lights": true,
            "hosts": "192.168.5.8"
        },
        {
            "platform": "Logi Circle Controls",
            "name": "Logi Circle Controls",
            "email": "XXXXXXXX",
            "password": "XXXXXXXX",
            "accessories": [
                {
                    "deviceId": "XXXXXXXX",
                    "name": "Wohnzimmer Camera",
                    "camera": {
                        "name": "Camera",
                        "disabled": false
                    },
                    "led": {
                        "name": "LED",
                        "disabled": true
                    },
                    "privacyMode": {
                        "name": "Privat Modus",
                        "disabled": false
                    },
                    "recording": {
                        "name": "Aufzeichnung",
                        "disabled": true
                    },
                    "nightVisionMode": {
                        "name": "Night Vision",
                        "disabled": true
                    },
                    "nightVisionIR": {
                        "name": "Night IR",
                        "disabled": true
                    }
                }
            ]
        },
        {
            "platform": "FritzPlatform",
            "devices": {},
            "smarthome": {
                "Test Contact Sensor": {
                    "active": false,
                    "ain": "01234567890",
                    "devType": "contact"
                },
                "Test Thermostat Device": {
                    "active": false,
                    "ain": "01234567890",
                    "heatValue": 5,
                    "coolValue": 5,
                    "windowSensor": false,
                    "devType": "thermostat"
                },
                "Test Outlet Device": {
                    "active": false,
                    "ain": "01234567890",
                    "tempSensor": false,
                    "devType": "switch"
                }
            },
            "callmonitor": {
                "active": false,
                "ip": "0.0.0.0",
                "port": 1012,
                "country": "",
                "incomingTo": [],
                "outgoingFrom": []
            },
            "presence": {
                "user": [
                    {
                        "active": false,
                        "name": "Test User",
                        "address": "0.0.0.0"
                    }
                ],
                "anyone": false,
                "offDelay": 90,
                "onDelay": 15,
                "ping": false
            },
            "wol": [
                {
                    "active": false,
                    "name": "Test Device",
                    "address": "00:00:00:00:00:00"
                }
            ],
            "phoneBook": {
                "active": false,
                "blacklists": []
            },
            "alarm": {
                "active": false,
                "telNr": "",
                "duration": 30
            },
            "wakeup": {
                "active": false,
                "internNr": "",
                "duration": 30
            },
            "ringlock": {
                "active": false,
                "DECTphones": 1,
                "start": "11:00",
                "end": "22:00"
            },
            "broadband": {
                "active": false,
                "measureTime": 5
            },
            "extReboot": {
                "active": false,
                "cmdOn": "",
                "cmdOff": ""
            },
            "telegram": {
                "active": false,
                "token": "",
                "chatID": "",
                "presence": {
                    "in": "",
                    "out": "",
                    "anyoneIn": "",
                    "anyoneOut": ""
                },
                "callmonitor": {
                    "incoming": "",
                    "disconnected": ""
                },
                "alarm": {
                    "activated": "",
                    "deactivated": ""
                },
                "extReboot": {
                    "start": "",
                    "finish": ""
                }
            },
            "polling": 10,
            "timeout": 10,
            "clearCache": false,
            "debug": false,
            "disableAutoSearch": false,
            "disableAutoConfig": false
        },
        {
            "platform": "MiLight",
            "name": "MiLight",
            "bridges": [
                {
                    "ip_address": "192.168.5.12",
                    "version": "v6",
                    "lights": {
                        "rgbw": [
                            null,
                            "Flur Licht",
                            null,
                            null
                        ],
                        "bridge": [
                            null
                        ]
                    },
                    "repeat": 1,
                    "delay": 50
                }
            ]
        },
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "c",
            "sudo": true,
            "log": {
                "method": "systemd",
                "service": "homebridge"
            },
            "platform": "config"
        }
    ],
    "accessories": [
        {
            "accessory": "RaspberryPiTemperature",
            "name": "RaspberryPi CPU Temperature"
        },
        {
            "timeout": 5000,
            "mac": "XXXXXXXX",
            "version": 6,
            "secure": false,
            "disabled": [],
            "password": "XXXXXXXX",
            "pollingInterval": 240,
            "accessory": "Synology",
            "doPolling": true,
            "ip": "192.168.5.9",
            "account": "XXXXXXXX",
            "name": "Server",
            "port": "5000"
        },
        {
            "ip": "192.168.5.2",
            "accessory": "lgtv-2012",
            "max_volume": 15,
            "on_command": "MUTE",
            "min_volume": 2,
            "pairingKey": "XXXXXXXX",
            "name": "TV"
        },
        {
            "accessory": "marantz-volume",
            "name": "Denon X4300H",
            "host": "192.168.5.7:8080"
        }
    ],
    "id": "config"
}

Homebridge:    Version 0.4.50
Node:        node.js v10.16.0
Fritz Platform:    4.1.0

ich hoffe ihr könnt mir helfen am 10.6 hatte alles noch funktioniert

**Comment by SeydX** [comment]
mach mal disableAutoSearch auf true und disableAutoSearch auch auf true und anschließend alte config einfügen und neustarten

**Comment by Berlinologe86** [comment]
cool super dank dir:) hab mich irgendwie zu doof angestellt :) jetzt läuft es wieder bestens :)klasse plugin :)
