### ISSUE TITLE
incomingTo In callmonitor seems not to work

### ISSUE THREAD

**Issue by 0rangeX** [SeydX/homebridge-fritz-platform#45]
**Describe the bug**
I would like to limit the callmonitor to certain numbers only, but it is always triggered even on numbers not included in incomingTo.
Is there a certain format of the numbers expected? Only the number, including city prefix, including country prefix with 00 or +?
Any hints appreciated!

**Comment by 0rangeX** [comment]
I enabled debug mode. If I add the city prefix and it is registered / ignored correctly according to the log, however the call monitor incoming sensor triggers even if the log says it did not match.
[FritzPlatform] [INFO] Callmonitor Incoming: Incoming to nr not matched.
Can you please verify and fix, @SeydX ? Thank you very much!

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed/added in v5 (coming soon)
