### ISSUE TITLE
Versions upgrade

### ISSUE THREAD

**Issue by BerkTam** [SeydX/homebridge-fritz-platform#46]
Hello, 

question: why you cannot just keep the previous versions alive if there are significant changes on any new version?

For example for me and some others the V3.x worked very well and with V4.x there has been so many issues that I am really thinking to remove the plugin fully. 
To be honest, it is really a great plugin and thanks for your effort but if the plugin or newer version are raising more issues than bringing solutions  it will not be helpful for anyone. 

Currently I think the best work was with V2.x and V3.x but
V4.x is really a pain. 

Just something to think about. 

Thx

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SeydX** [comment]
Why this version is pain for you? What is the problem?

**Comment by BerkTam** [comment]
Hello, 
thanks for the quick response. 

Because I cannot get it up and running. It brings always an issue at startup and says "An Error occured while checking config."

Even when trying your advice at "First start…" it is not working as it doesnt get the accessories collected.
On my other HomeBridge I have still the old version of the FritzPlatform and when starting this one it starts immediately. So the issue is not related to my Fritz configuration. 

Thx

**Comment by BerkTam** [comment]
ok, where can find the the log-file?

thx

**Comment by BerkTam** [comment]
This is solved and it works now. 
I would suggest to mention in the FritzPlatform setup that it would be better to remove any other plugins in the config.json file when starting the Autosearch. 
And there are also some typo mistakes in the sample config.json file. 

I have something on my wish-list and I know it should be actually go to Pull-requests but mentioning it here:  
In Version 2 I liked that the Presence switch showed a history of being present or absent. Could you please be so kind and turn this feature on in this version?
Would be really great as I was using that permanently and really missing this feature?

Thx
