### ISSUE TITLE
issue with 3490

### ISSUE THREAD

**Issue by MaurizioB84** [SeydX/homebridge-fritz-platform#47]
**Describe the bug**
Incompatibility with 3490, not found tr64desc.xml

**To Reproduce**
1. Go to configure with the following "config.yaml"
"            "platform": "FritzPlatform",
            "disableAutoSearch": true,
            "devices": {
                "FritzBox router": {
                    "active": true,
                    "host": "192.168.2.1",
                    "port": 80,
                    "username": "username",
                    "password": "pwd",
                    "type": "cable",
                    "master": false,
                    "mesh": false,
                    "readOnly": false,
                    "options": {
                        "reconnect": false,
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            false
                        ],
                        "wps": [
                            true,
                            false
                        ]
                    }
                }
            },
            "smarthome": {},
            "callmonitor": {},
            "presence": {},
            "wol": [],
            "phoneBook": {},
            "alarm": {},
            "wakeup": {},
            "ringlock": {},
            "broadband": {},
            "extReboot": {},
            "telegram": {},
            "polling": 10,
            "timeout": 10,
            "clearCache": false,
            "debug": true,
            "disableAutoConfig": false
        },"

**Expected behavior**
works

**Desktop (please complete the following information):**
 - OS: Raspbian

**Additional context**
log of error:
ug 31 16:41:41 raspberrypi homebridge[8050]: 2019-07-31T14:41:41.378Z FritzPlatform Found following devices:
lug 31 16:41:41 raspberrypi homebridge[8050]: 2019-07-31T14:41:41.412Z FritzPlatform [ { name: 'FritzBox router',
lug 31 16:41:41 raspberrypi homebridge[8050]:     address: '192.168.2.1',
lug 31 16:41:41 raspberrypi homebridge[8050]:     port: 80,
lug 31 16:41:41 raspberrypi homebridge[8050]:     location: 'http://192.168.2.1:80/tr64desc.xml',
lug 31 16:41:41 raspberrypi homebridge[8050]:     serial: 'FB-19216xxx' } ]
lug 31 16:41:41 raspberrypi homebridge[8050]: [2019-7-31 4:41:41 PM] [FritzPlatform] [INFO] Initializing config...
lug 31 16:41:43 raspberrypi homebridge[8050]: [2019-7-31 4:41:43 PM] Homebridge is running on port 51826.
lug 31 16:41:43 raspberrypi homebridge[8050]: 2019-07-31T14:41:43.980Z FritzPlatform Initializing extra accessories...
lug 31 16:41:44 raspberrypi homebridge[8050]: 2019-07-31T14:41:44.015Z FritzPlatform Initializing extras...
lug 31 16:41:44 raspberrypi homebridge[8050]: 2019-07-31T14:41:44.023Z FritzPlatform Initializing telegram...
lug 31 16:41:44 raspberrypi homebridge[8050]: 2019-07-31T14:41:44.029Z FritzPlatform Initializing callmonitor...
lug 31 16:41:44 raspberrypi homebridge[8050]: [2019-7-31 4:41:44 PM] [FritzPlatform] [INFO] Auto config generator disabled.
lug 31 16:41:44 raspberrypi homebridge[8050]: [2019-7-31 4:41:44 PM] [FritzPlatform] [INFO] Found 1 active devices...
lug 31 16:41:44 raspberrypi homebridge[8050]: 2019-07-31T14:41:44.066Z FritzPlatform Checking master device...
lug 31 16:41:47 raspberrypi homebridge[8050]: [2019-7-31 4:41:47 PM] [FritzPlatform] [ERROR] An error occured while checking config!
lug 31 16:41:47 raspberrypi homebridge[8050]: 2019-07-31T14:41:47.077Z FritzPlatform { status: 404,
lug 31 16:41:47 raspberrypi homebridge[8050]:   message: 'Not Found',
lug 31 16:41:47 raspberrypi homebridge[8050]:   config:
lug 31 16:41:47 raspberrypi homebridge[8050]:    { url: 'http://192.168.2.1:80/tr64desc.xml',
lug 31 16:41:47 raspberrypi homebridge[8050]:      headers:
lug 31 16:41:47 raspberrypi homebridge[8050]:       { Accept: 'application/json, text/plain, */*',
lug 31 16:41:47 raspberrypi homebridge[8050]:         'User-Agent': 'axios/0.19.0' },
lug 31 16:41:47 raspberrypi homebridge[8050]:      transformRequest: [ [Function: transformRequest] ],
lug 31 16:41:47 raspberrypi homebridge[8050]:      transformResponse: [ [Function: transformResponse] ],
lug 31 16:41:47 raspberrypi homebridge[8050]:      timeout: 0,
lug 31 16:41:47 raspberrypi homebridge[8050]:      adapter: [Function: httpAdapter],
lug 31 16:41:47 raspberrypi homebridge[8050]:      xsrfCookieName: 'XSRF-TOKEN',
lug 31 16:41:47 raspberrypi homebridge[8050]:      xsrfHeaderName: 'X-XSRF-TOKEN',
lug 31 16:41:47 raspberrypi homebridge[8050]:      maxContentLength: -1,
lug 31 16:41:47 raspberrypi homebridge[8050]:      validateStatus: [Function: validateStatus],
lug 31 16:41:47 raspberrypi homebridge[8050]:      method: 'get',
lug 31 16:41:47 raspberrypi homebridge[8050]:      data: undefined },
lug 31 16:41:47 raspberrypi homebridge[8050]:   data:
lug 31 16:41:47 raspberrypi homebridge[8050]:    '<!DOCTYPE html>\n<html>\n<head>\n<meta http-equiv=content-type content="text/html; charset=utf-8" />\n<meta http-equiv="Cache-Control" content="private, no-transform" />\n<meta http-equiv="X-UA-Compatible" content="IE=edge" />\n<meta name="format-detection" content="telephone=no" />\n<meta http-equiv="x-rim-auto-match" content="none" />\n<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui" />\n<meta name="mobile-web-app-capable" content="yes" />\n<meta name="apple-mobile-web-app-capable" content="yes" />\n<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />\n<meta http-equiv="cleartype" content="on">\n<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />\n<link rel="apple-touch-icon" href="/css/default/images/kopfbalken_links.png" />\n<link rel="apple-touch-startup-image" href="/css/default/images/kopfbalken_links.png">\n<link rel="stylesheet" type="text/css" href="/css/rd/singleside_old.css"/>\n<title>FRITZ!Box</title>\n</head>\n<body>\n<div id="main_page_all">\n<header class="" name="" id="blueBarBox">\n<div class="blue_bar_titel" name="" id="blueBarTitel">FRITZ!Box</div>\n</header>\n<div id="page_content_no_menu_box">\n<div class="area_box">\n<div class="blue_bar_back" >\n<div><h2>FRITZ!Box</h2></div>\n</div>\n<div class="page_content">\n<p>Non è stato trovato l\'URL. È in corso l\'inoltro alla pagina iniziale del FRITZ!Box.</p>\n<p>Se non venite inoltrati automaticamente alla pagina iniziale del FRITZ!Box, cliccate <a href="/">qui</a>.</p>\n<br>\n</div>\n</div>\n</div>\n</div>\n<script>\nwindow.setTimeout(function () {\nwindow.location.href = "/";\n}, 10000);\n</script>\n</body>\n</html>\n' }

**Comment by MaurizioB84** [comment]
I forgot to say, the configuration on Fritz I think it's right, UPnP is enable and access via tr064 is enabled

**Comment by SeydX** [comment]
Could u try Version 5 Beta ?

https://github.com/SeydX/homebridge-fritz-platform/issues/92

I recommend u to use it with Config UI X to adjust the settings

**Comment by SeydX** [comment]
the port u set in the config is wrong

```
lug 31 16:41:47 raspberrypi homebridge[8050]: { url: 'http://192.168.2.1:80/tr64desc.xml',
```

change it to 49000 and it should work
