### ISSUE TITLE
Plugin runs only with deactivated firewall and open ports

### ISSUE THREAD

**Issue by ChristianKlee** [SeydX/homebridge-fritz-platform#48]
Hello,
my Homebridge runs on a Synology NAS. This plugin only works after deactivating the Synology Firewall. I could open some ports on the NAS but I couldn't figure out witch port (range).
Do you know what port has to be opened? If it helps, I'am using a FritzBox 7490.

**Comment by SeydX** [comment]
The plugin uses following ports: 80, 49000, 49433
