### ISSUE TITLE
Options couldn't be activated

### ISSUE THREAD

**Issue by nexusle** [SeydX/homebridge-fritz-platform#49]
Hey,

I setted up a new HomeBridge Server. After enabling all devices in config, all switches for "options" are not visible.

"options": {
            "wifi2": [
              true,
              true
            ],
            "wifi5": [
              true,
              true
],

These switches should enable it, right?? If so, then this doesn't work :-(

**Comment by nexusle** [comment]
Found the problem... Fritzbox wasn't set to active *facepalm*

**Comment by giannimp** [comment]
> Found the problem... Fritzbox wasn't set to active _facepalm_

Help me please, My homekit no show switch option
Thank you
