### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by RienduPre** [SeydX/homebridge-fritz-platform#5]
Hi,

I get this error 

Aug 31 10:37:26 homebridge homebridge[18129]: [2018-8-31 10:37:26] [FritzBox] [INFO] Incoming call from:  to 0314567890
Aug 31 10:37:27 homebridge homebridge[18129]: HAP Warning: Characteristic undefined not in required or optional characteristics for service 67bc5512-9024-45e5-a0ef-6302b7785bef. Adding anyway.
Aug 31 10:37:27 homebridge homebridge[18129]: ^ For: UV Sensor
Aug 31 10:37:37 homebridge homebridge[18129]: [2018-8-31 10:37:37] [FritzBox] [INFO] Call disconnected
Aug 31 10:37:45 homebridge homebridge[18129]: [2018-8-31 10:37:45] [FritzBox] [ERROR] FritzBoxAn error occured by getting device state!
Aug 31 10:37:45 homebridge homebridge[18129]: [2018-8-31 10:37:45] [FritzBox] [ERROR] {
Aug 31 10:37:45 homebridge homebridge[18129]:     "response": "OK",
Aug 31 10:37:45 homebridge homebridge[18129]:     "responseCode": 200,
Aug 31 10:37:45 homebridge homebridge[18129]:     "tr064": "Auth. failed",
Aug 31 10:37:45 homebridge homebridge[18129]:     "tr064code": "503",
Aug 31 10:37:45 homebridge homebridge[18129]:     "fault": "UPnPError",
Aug 31 10:37:45 homebridge homebridge[18129]:     "faultcode": "s:Client",
Aug 31 10:37:45 homebridge homebridge[18129]:     "serviceType": "urn:dslforum-org:service:WANPPPConnection:1",
Aug 31 10:37:45 homebridge homebridge[18129]:     "action": "GetStatusInfo"
Aug 31 10:37:45 homebridge homebridge[18129]: }

I don't know which authentication is failing. the call monitor does work

See config.json part.
 {
            "platform": "FritzPlatform",
            "name": "FritzBox",
            "host": "192.123.4.5",
            "port": 49000,
            "type": "dsl",
            "timeout": 5,
            "username": "user",
            "password": "pasword!",
            "polling": 10,
            "callmonitor": {
                "disable": false,
                "ip": "192.123.4.5",
                "port": 1012,
                "telegram": false,
                "token": "TOKENHERE",
                "chatID": "CHATIDHERE",
                "messages": {
                    "incoming": "Incoming call from @ to %",
                    "disconnected": "Incoming call from @ was disconnected!"
                },
                "presence": {
                    "anyoneSensor": true,
                    "delay": 30,
                    "type": "motion",
                    "telegram": false,
                    "token": "TOKENHERE",
                    "chatID": "CHATIDHERE",
                    "messages": {
                        "sensorOn": "Welcome at home @",
                        "sensorOff": "Bye bye @",
                        "anyoneOn": "Prsence detected at home!",
                        "anyoneOff": "No one at home!"
                    },
                    "devices": {
                        "Peter": "00:11:22:33:44.55",
                        "Rien": "192.123.4.6"
                    }
                }
            }
        },

Any clues?

**Comment by SeydX** [comment]
can u try with v2.8 pls
