### ISSUE TITLE
Improvement: Don't show fritzboxes as toggle in reading mode

### ISSUE THREAD

**Issue by lepatrick** [SeydX/homebridge-fritz-platform#50]
Hey SeydX,

thanks for your great work. I control my three fritz boxes with your great plugin. In the beginning I reboot some boxes, when tuning all lights off... For now I'm in read only mode. Is there a way, which don't show the toggles in ro-mode in Homekit?

Would be a small but great imporvement.

Best regards,
patrick

**Comment by Jemeins** [comment]
I agree with lepatrick´s wish!

**Comment by SeydX** [comment]
Added in v5 (coming soon)
