### ISSUE TITLE
Download/Upload/Ping seems not correct Fritz!Box 6590 Cable

### ISSUE THREAD

**Issue by iGodPhil** [SeydX/homebridge-fritz-platform#54]
Into the EVE App I can see my Download & Upload Speed and the ping but everythin isn't correct. Into EVE my Download Speed is 46 MBit/s but the my real Speed is 426 MBit/s. The same with the other two options.

But the the Powerline adapter 1260E works also fine with your plugin. Maybe it's important for your wiki.

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed/added in v5 (coming soon)
