### ISSUE TITLE
Telegram notifications for outgoing calls?

### ISSUE THREAD

**Issue by abbanatic** [SeydX/homebridge-fritz-platform#57]
Hi,

In https://github.com/SeydX/homebridge-fritz-platform/issues/19, a user describes the problem with the outgoing number in Telegram notifications for outgoing calls.

I wonder, how can I enable Telegram notifications for outgoing calls? I didn't find any clue in the documentation.

Is this feature really implemented yet? An if not, can you please be so kind to enable outgoing call notifications as well?

Thanks,
Thomas

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed/added in v5 (coming soon)
