### ISSUE TITLE
Errors in the log

### ISSUE THREAD

**Issue by vzlgdu** [SeydX/homebridge-fritz-platform#58]
Hi, I'm receiving the following messages:

[FritzPlatform] [ERROR] Host List: An error occured while getting hosts list endpoint!
[FritzPlatform] [ERROR] FRITZ!Box 7490: An error occured while getting state of device!
[FritzPlatform] [ERROR] Smarthome List: An error occured while generating smarthome list!

as conseguence the presence featurre doesn't work.
Can you help me?
Thanks

HB version 0.4.50
HB Vritz Platform version  4.1.0

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed/added in v5 (coming soon)
