### ISSUE TITLE
Callmonitor - different behaviors for different numbers/lines

### ISSUE THREAD

**Issue by Holydevil66** [SeydX/homebridge-fritz-platform#6]
The call monitor-function would be great for auto-pause/mute tv on incoming calls or other actions/automations. But as we have several handsets with different numbers, I'd like to have selective actions for the different numbers/lines for automation like mute the tv in the living room when incoming call on line 1 / living room, telegram for incoming calls on line 2 when away, ...

**Comment by SeydX** [comment]
At the moment there are no further plans for the call monitor. but i can add it to my todo list for a further version

**Comment by SeydX** [comment]
Added new option in v3.0.3 for specific incoming/outgoing nr
