### ISSUE TITLE
Upgrade node version

### ISSUE THREAD

**Issue by ChrWi** [SeydX/homebridge-fritz-platform#61]
I did a node update on my pi. From all my modules, only the fritz-platform did not like this by highlighting:

`Plugin /usr/local/lib/node_modules/homebridge-fritz-platform requires Node version of ^10.15.3 which does not satisfy the current Node version of v12.14.0. You may need to upgrade your installation of Node.`

It still works, therefore it is a feature request and not an issue for me.

Thanks!

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed/added in v5 (coming soon)
