### ISSUE TITLE
Thermostats (DECT301) unwanted setpoint change when heat/cool set change

### ISSUE THREAD

**Issue by appliko** [SeydX/homebridge-fritz-platform#62]

**Comment by appliko** [comment]
Hi,
Regarding thermostats, I don‘t understand why the setpoint is set to XX degrees plus or minus the current temperature.
Any way to avoid it ? If I set the offsets to 0 it seems not working at all

**Comment by BKrnk1337** [comment]
I have the same problem and dont understand why I should set a + or - value. Dont make sense in my mind. I hope @SeydX will reply to this.

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed/added in v5 (coming soon)
