### ISSUE TITLE
Presence is not updating

### ISSUE THREAD

**Issue by Peaches2018** [SeydX/homebridge-fritz-platform#63]
Hi,

I see all users and devises I have set up in the config.json but there are not updating the presence. They are always on "triggered"

Any idea?

**Comment by MasterofKungfu9999** [comment]
Same issue here. It only works with the ping method. 

Please help

**Comment by Hussamfhaily** [comment]
Have the same problem.

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed/added in v5 (coming soon)
