### ISSUE TITLE
Fehler: Found 0 active devices...

### ISSUE THREAD

**Issue by alex20081989** [SeydX/homebridge-fritz-platform#66]
Hey, habe heute versucht das Plugin einzurichten. Die Einstellungen in der Fritz!Box habe ich vorher vorgenommen. Leider wird kein aktives Gerät gefunden.

Hier meine config:
{
    "platform": "FritzPlatform",
    "devices": {
        "FRITZ!Box 6490": {
            "active": true,
            "host": "192.168.178.1",
            "port": 49000,
            "username": "xxx",
            "password": "xxx",
            "type": "cable",
            "master": true,
            "mesh": false,
            "readOnly": false,
            "debug": true,
            "options": {
                "wifi2": [
                    true,
                    false
                ],
                "wifi5": [
                    true,
                    false
                ],
                "wifiGuest": [
                    true,
                    false
                ],
                "reconnect": true,
                "wps": [
                    true,
                    false
                ],
                "aw": [
                    true,
                    false
                ],
                "deflection": [
                    true,
                    false
                ],
                "led": [
                    true,
                    false
                ],
                "lock": [
                    true,
                    false
                ]
            }
        }
    }
}

Hier die Fehlermeldung:
[Homebridge] [2/5/2020, 18:59:29] [FritzPlatform] [INFO] Initializing config...
[Homebridge] [2/5/2020, 18:59:29] [FritzPlatform] [INFO] Found 0 active devices...
[Homebridge] [2/5/2020, 18:59:29] [FritzPlatform] [INFO] Please check your config.json and activate the device(s) you want to see in HomeKit.
[Homebridge] [2/5/2020, 18:59:29] [FritzPlatform] [INFO] Please also set up username, password, type and master for your 'device(s)' and restart homebridge!

Hoffe mir kann jemand bei dem Problem helfen.

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed/added in v5 (coming soon)
