### ISSUE TITLE
Fritz DECT 200 Temperatur Zero degrees

### ISSUE THREAD

**Issue by sTsJoch** [SeydX/homebridge-fritz-platform#68]
I use your homebridge-fritz-platform in HOOBS and i can use my Fritz DECT 200 as a switch in Homekit. Very good!

But - the Temperature is shown as 0 Degrees in HOOBS and in Homekit. In the MyFritz App the temperature is shown perfectly.

What do i make wrong? What do i have to change that i can get the Temoerature in Homekit?
![screenshot](https://user-images.githubusercontent.com/60797778/74150181-a67f5200-4c09-11ea-855c-d66de459e64e.jpg)

My settings:

{
    "platform": "FritzPlatform",
    "devices": {
        "FRITZ!Box 6490 Cable (kdg)": {
            "active": true,
            "host": "192.168.178.1",
            "port": 49000,
            "username": "admin",
            "password": "xxxxxxxxxxx",
            "type": "cable",
            "master": true,
            "mesh": false,
            "readOnly": true,
            "options": {
                "reconnect": false,
                "wifi2": [
                    false,
                    false
                ],
                "wifi5": [
                    false,
                    false
                ],
                "wifiGuest": [
                    false,
                    false
                ],
                "wps": [
                    false,
                    false
                ],
                "aw": [
                    false,
                    false
                ],
                "deflection": [
                    false,
                    false
                ],
                "led": [
                    false,
                    false
                ],
                "lock": [
                    false,
                    false
                ]
            }
        }
    },
    "smarthome": {
        "Deckenfluter Wohnzimmer": {
            "active": true,
            "ain": "087610092131",
            "tempSensor": true,
            "devType": "switch"
        }
    },
    "callmonitor": {
        "active": false,
        "ip": "0.0.0.0",
        "port": 1012
    },
    "presence": {
        "user": [
            {
                "active": false,
                "name": "Test User",
                "address": "0.0.0.0"
            }
        ],
        "anyone": false,
        "offDelay": 90,
        "onDelay": 15,
        "ping": false
    },
    "wol": [
        {
            "active": false,
            "name": "Test Device",
            "address": "00:00:00:00:00:00"
        }
    ],
    "phoneBook": {
        "active": false
    },
    "alarm": {
        "active": false,
        "duration": 30
    },
    "wakeup": {
        "active": false,
        "duration": 30
    },
    "ringlock": {
        "active": false,
        "DECTphones": 1,
        "start": "11:00",
        "end": "22:00"
    },
    "broadband": {
        "active": false,
        "measureTime": 5
    },
    "extReboot": {
        "active": false
    },
    "telegram": {
        "active": false
    },
    "polling": 10,
    "timeout": 10,
    "clearCache": false,
    "debug": false,
    "disableAutoSearch": false,
    "disableAutoConfig": true
}

**Comment by SeydX** [comment]
Fixed in v5 Beta 21
