### ISSUE TITLE
Reboot Toggle doesn't work/appear

### ISSUE THREAD

**Issue by Christian-CFP** [SeydX/homebridge-fritz-platform#70]
**Describe the bug**
Reboot Toggle doesn't work/appear

**Expected behavior**
To see a reboot toggle inside my Fritz!Box.

**Smartphone (please complete the following information):**
 - iPhone XS
 - iOS 13.4

**Additional context**
Using raspberry pi with HOOBS.

Config:
"platform": "FritzPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-fritz-platform"
            },
            "devices": {
                "FRITZ!Box 7590 (UI)": {
                    "active": true,
                    "host": "xxx",
                    "port": 49000,
                    "username": "xxx",
                    "password": "yyy",
                    "type": "dsl",
                    "master": true,
                    "mesh": true,
                    "readOnly": false,
                    "options": {
                        "reconnect": true,
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            false
                        ],
                        "wps": [
                            true,
                            false
                        ],
                        "aw": [
                            false,
                            false
                        ],
                        "deflection": [
                            false,
                            false
                        ],
                        "led": [
                            true,
                            false
                        ],
                        "lock": [
                            false,
                            false
                        ]
                    }
                },
                "FRITZ!WLAN Repeater 1750E": {
                    "active": true,
                    "host": "xxx",
                    "port": 49000,
                    "username": "xxx",
                    "password": "yyy",
                    "type": "repeater",
                    "readOnly": false,
                    "options": {
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            false
                        ],
                        "wps": [
                            true,
                            false
                        ],
                        "led": [
                            true,
                            false
                        ]
                    }
                }
            },
            "smarthome": {
                "Test Contact Sensor": {
                    "active": false,
                    "ain": "01234567890",
                    "devType": "contact"
                },
                "Test Outlet Device": {
                    "active": false,
                    "ain": "01234567890",
                    "tempSensor": false,
                    "devType": "switch"
                },
                "Test Thermostat Device": {
                    "active": false,
                    "ain": "01234567890",
                    "heatValue": 5,
                    "coolValue": 5,
                    "windowSensor": false,
                    "devType": "thermostat"
                }
            },
            "callmonitor": {
                "active": true,
                "ip": "xxx",
                "port": 1012,
                "country": "DE",
                "incomingTo": [
                    "xxx",
                    "yyy"
                ],
                "outgoingFrom": [
                    "xxx",
                    "yyy"
                ]
            },
            "presence": {
                "user": [
                    {
                        "address": "xxx",
                        "name": "yyy",
                        "active": true
                    },
                    {
                        "address": "xxx",
                        "name": "yyy",
                        "active": true
                    },
                    {
                        "address": "xxx",
                        "name": "yyy",
                        "active": true
                    },
                    {
                        "address": "xxx",
                        "name": "yyy",
                        "active": true
                    }
                ],
                "anyone": true,
                "offDelay": 90,
                "onDelay": 15,
                "ping": false
            },
            "wol": [
                {
                    "address": "00:00:00:00:00:00",
                    "name": "Test Device",
                    "active": false
                }
            ],
            "alarm": {
                "active": false,
                "telNr": "xxx",
                "duration": 30
            },
            "wakeup": {
                "active": false,
                "duration": 30
            },
            "ringlock": {
                "active": false,
                "DECTphones": 1,
                "start": "11:00",
                "end": "22:00"
            },
            "broadband": {
                "active": true,
                "measureTime": 5
            },
            "phoneBook": {
                "active": true,
                "blacklists": [
                    "Blacklist"
                ]
            },
            "extReboot": {
                "active": true,
                "cmdOn": "sh /home/hoobs/scripts/reboot-start.sh",
                "cmdOff": "sh /home/hoobs/scripts/reboot-finished.sh"
            },
            "telegram": {
                "active": true,
                "token": "xxx",
                "chatID": "yyy",
                "presence": {
                    "in": "@ ist Zuhause.",
                    "out": "@ hat das Haus verlassen.",
                    "anyoneIn": "Jemand ist Zuhause!",
                    "anyoneOut": "Es ist keiner mehr ist Zuhause!"
                },
                "callmonitor": {
                    "incoming": "@ ruft an!",
                    "disconnected": "Anruf mit @ wurde beendet!"
                },
                "alarm": {
                    "activated": "Alarm aktiviert! Rufe @!",
                    "deactivated": "Alarm deaktiviert!"
                },
                "extReboot": {
                    "start": "Netzwerk wird neugestartet!",
                    "finish": "Netzwerk Neustart abgeschlossen!"
                }
            },
            "polling": 5,
            "timeout": 10,
            "clearCache": false,
            "debug": false,
            "disableAutoSearch": false,
            "disableAutoConfig": false

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed in v5 (coming soon)
