### ISSUE TITLE
Problem with "options"

### ISSUE THREAD

**Issue by MasterofKungfu9999** [SeydX/homebridge-fritz-platform#71]
I have some problems with the "options" at "FRITZ!WLAN Repeater 1750E" and "FRITZ!Repeater oben".

There are no switches in "eve". With the "Fritz!Box" and the "FRITZ!Repeater 2400" it works fine and switches are shown. Can somebody help me? 

Below my configuration:

{
    "platform": "FritzPlatform",
    "devices": {
        "FRITZ!Box 7590": {
            "active": true,
            "host": "192.168.13.1",
            "port": 49000,
            "username": "xxxxxx",
            "password": "xxxxxx",
            "type": "dsl",
            "master": true,
            "mesh": true,
            "readOnly": false,
            "options": {
                "reconnect": true,
                "wifi2": [
                    true,
                    false
                ],
                "wifi5": [
                    true,
                    false
                ],
                "wifiGuest": [
                    true,
                    false
                ],
                "wps": [
                    true,
                    false
                ],
                "aw": [
                    true,
                    false
                ],
                "deflection": [
                    true,
                    false
                ],
                "led": [
                    true,
                    false
                ],
                "lock": [
                    true,
                    false
                ]
            }
        },
        "FRITZ!WLAN Repeater 1750E": {
            "active": true,
            "host": "192.168.13.23",
            "port": 49000,
            "username": "xxxxxxx",
            "password": "xxxxxxxxxx",
            "type": "repeater",
            "readOnly": false,
            "options": {
                "wifi2": [
                    true,
                    false
                ],
                "wifi5": [
                    true,
                    false
                ],
                "wifiGuest": [
                    true,
                    false
                ],
                "wps": [
                    true,
                    false
                ],
                "led": [
                    true,
                    false
                ]
            }
        },
        "FRITZ!Repeater oben": {
            "active": true,
            "host": "192.168.13.25",
            "port": 49000,
            "username": "xxxxx",
            "password": "xxxxxxx",
            "type": "repeater",
            "readOnly": false,
            "options": {
                "wifi2": [
                    true,
                    false
                ],
                "wifi5": [
                    true,
                    false
                ],
                "wifiGuest": [
                    true,
                    false
                ],
                "wps": [
                    true,
                    false
                ],
                "led": [
                    true,
                    false
                ]
            }
        },
        "FRITZ!Repeater 2400": {
            "active": true,
            "host": "192.168.13.54",
            "port": 49000,
            "username": "xxxx",
            "password": "xxxxx",
            "type": "repeater",
            "readOnly": false,
            "options": {
                "wifi2": [
                    true,
                    false
                ],
                "wifi5": [
                    true,
                    false
                ],
                "wifiGuest": [
                    true,
                    false
                ],
                "wps": [
                    true,
                    false
                ],
                "led": [
                    true,
                    false
                ]
            }
        }
    },
    "smarthome": {
        "Test Contact Sensor": {
            "active": false,
            "ain": "01234567890",
            "devType": "contact"
        },
        "Test Thermostat Device": {
            "active": false,
            "ain": "01234567890",
            "heatValue": 5,
            "coolValue": 5,
            "windowSensor": false,
            "devType": "thermostat"
        },
        "Test Outlet Device": {
            "active": false,
            "ain": "01234567890",
            "tempSensor": false,
            "devType": "switch"
        }
    },
    "callmonitor": {
        "active": false,
        "ip": "0.0.0.0",
        "port": 1012
    },
    "presence": {
        "user": [
            {
                "active": true,
                "name": "xxxxxxx",
                "address": "192.168.13.39"
            }
        ],
        "anyone": true,
        "offDelay": 10,
        "onDelay": 10,
        "ping": false
    },
    "wol": [
        {
            "active": false,
            "name": "Test Device",
            "address": "00:00:00:00:00:00"
        }
    ],
    "phoneBook": {
        "active": false
    },
    "alarm": {
        "active": false,
        "duration": 30
    },
    "wakeup": {
        "active": false,
        "duration": 30
    },
    "ringlock": {
        "active": false,
        "DECTphones": 1,
        "start": "11:00",
        "end": "22:00"
    },
    "broadband": {
        "active": false,
        "measureTime": 5
    },
    "extReboot": {
        "active": false
    },
    "telegram": {
        "active": false
    },
    "polling": 10,
    "timeout": 10,
    "clearCache": false,
    "debug": false,
    "disableAutoSearch": true,
    "disableAutoConfig": true
}

**Comment by BKrnk1337** [comment]
Can you describe your problem a bit more please. What do you mean with "eve"?

**Comment by MasterofKungfu9999** [comment]
the issue can be closed the fritz repeater shows up after restart.
