### ISSUE TITLE
Led control no longer possible

### ISSUE THREAD

**Issue by Nastras** [SeydX/homebridge-fritz-platform#72]
Hello, Seydx,

after updating to the current lab version of AVM it is no longer possible to control the LEDs of the Fritzbox and repeater.

The switch always keeps the position that is actually set. A change is not possible.

![F0ADDA43-66D4-44AF-92CE-E2B0910AE1A7](https://user-images.githubusercontent.com/27686185/77877396-f36cc580-7255-11ea-809c-edbc6897af76.jpeg)

**Comment by DurrM** [comment]
Hey there,

same here with FRITZ!WLAN Repeater 1750E. 
After the update to Fritz!OS 7.20 it's no longer possible to control the LEDs.

**Comment by Nastras** [comment]
Hello @SeydX,

i wanted to ask what is the chance that you will fix this bug soon?

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed/added in v5 (coming soon)
