### ISSUE TITLE
Nothing with Fritz DECT 200

### ISSUE THREAD

**Issue by cjk2** [SeydX/homebridge-fritz-platform#74]
Hello,
thank you very much for your PlugIn. However, I only use the switch of my Fritz DECT 200, but I can't switch it. Also the temperature display is simply at 0 degrees. Any idea? 
Thanks Chris

**Comment by ChrWi** [comment]
Please provide your configuration - on my side I am also only using the 200 w/o any issuse. Is your ain the correct one?

**Comment by SeydX** [comment]
Fixed in v5 Beta 21
