### ISSUE TITLE
Disable the "global" switch for FritzBox in Homekit?

### ISSUE THREAD

**Issue by harryslapalot** [SeydX/homebridge-fritz-platform#75]
Is there a way to disable the global switch for the FritzBox itself? I would mainly like to use the switch for the guest WLAN and want to avoid that kids or wife click on the FritzBox Button and thereby reboot the FritzBox.

**Comment by ChrWi** [comment]
If I am not wrong this is set with "readOnly": true (Device section)

**Comment by BKrnk1337** [comment]
> If I am not wrong this is set with "readOnly": true (Device section)

I think @ChrWi is right.

**Comment by SebSemmi** [comment]
I would like this too. It would be nice to disable the global switch, but keep the guest wifi switch as a separate tile.

**Comment by BKrnk1337** [comment]
> I would like this too. It would be nice to disable the global switch, but keep the guest wifi switch as a separate tile.

This is totally possible. Just set the following parameter `"readOnly":` to `true` In your Master device. All other Switches will be still able to clickx

**Comment by SeydX** [comment]
As mentioned above

"readOnly": true
