### ISSUE TITLE
Presence: Not all devices are checked

### ISSUE THREAD

**Issue by flobernd** [SeydX/homebridge-fritz-platform#8]
Hi there,

I tried out the presence feature (my main feature in this plugin), but sadly it does not work very well. It seems like only the first and the last device is updated correctly.

E.g.:
```javascript
    "presence": {
        "anyoneSensor": true,
        "delay": 30,
        "type": "motion",
        "devices": {
          "Handy 1": "MAC", // connected -> plugin shows connected -> correct
          "Handy 2": "MAC", // connected -> plugin shows DISCONNECTED -> BUG
          "Handy 3": "MAC", // disconnected-> plugin shows disconnected -> correct
          "Handy 4": "MAC", // connected -> plugin shows DISCONNECTED -> BUG
          "Handy 5": "MAC"  // disconnected-> plugin shows disconnected -> correct
        }
      }
```

On startup I get the message `[FritzBox] [INFO] Welcome at home Handy 1` and a few lines later it prints `[FritzBox] [WARN] Handy 5: Switching to no presence`. 
The status is correct for these two ones, but your plugin does not detect (or even check) the other devices (Handy 2 and 4 were connected to the network as well).

Edit: Works fine on version 2.6.4, just not with the latest one.

Best regards

**Comment by BerkTam** [comment]
same issue here with the latest version. It only detects 2 devices at the beginning and then drops them as well and afterwards I do not get any notification anymore from Telegram

**Comment by henkhb** [comment]
Same here.

**Comment by stereu** [comment]
Same here, i think the iteration is not working correctly. Only the first device is getting recognized correctly.

**Comment by michaelzoellner** [comment]
Same here.

**Comment by SeydX** [comment]
can u try with v2.8.0 pls?

**Comment by henkhb** [comment]
Works again.  Thanks for the Update!

**Comment by michaelzoellner** [comment]
Yes, v2.8.0 seems to have solved the issue. Thanks a lot!
