### ISSUE TITLE
No show switch wifi in homekit

### ISSUE THREAD

**Issue by giannimp** [SeydX/homebridge-fritz-platform#82]
I have fritzbox 7590 firmware beta:
![image](https://user-images.githubusercontent.com/45820952/81505931-2c876380-92f3-11ea-8a1e-df0a951db391.png)
In Homekit no show swtich option , in 7590 and in repeater no beta firmware:
{
    "platform": "FritzPlatform",
    "devices": {
        "Fritzbox7590": {
            "active": false,
            "host": "192.168.2.1",
            "port": 49000,
            "username": "Giovanni",
            "password": "xxxxxxxxx",
            "type": "cable",
            "master": true,
            "mesh": true,
            "readOnly": false,
            "options": {
                "reconnect": false,
                "wifi2": [
                    true,
                    false
                ],
                "wifi5": [
                    true,
                    false
                ],
                "wifiGuest": [
                    true,
                    false
                ],
                "wps": [
                    false,
                    false
                ],
                "aw": [
                    false,
                    false
                ],
                "deflection": [
                    false,
                    false
                ],
                "led": [
                    false,
                    false
                ],
                "lock": [
                    true,
                    false
                ]
            }
        },
        "FRITZ!WLAN Repeater 1160": {
            "active": false,
            "host": "192.168.2.55",
            "port": 49000,
            "username": "Giovanni",
            "password": "xxxxxxxxxx",
            "master": false,
            "mesh": true,
            "readOnly": false,
            "options": {
                "wifi2": [
                    true,
                    false
                ],
                "wifi5": [
                    true,
                    false
                ],
                "wifiGuest": [
                    true,
                    false
                ],
                "led": [
                    false,
                    false
                ],
                "lock": [
                    true,
                    false
                ]
            }
        }
    },
    "smarthome": {
        "Test Contact Sensor": {
            "active": false,
            "ain": "01234567890",
            "devType": "contact"
        },
        "Camera Letto": {
            "active": true,
            "ain": "119610841736",
            "heatValue": 5,
            "coolValue": 5,
            "windowSensor": false,
            "devType": "thermostat"
        },
        "Termostato Ciro": {
            "active": true,
            "ain": "099950167767",
            "heatValue": 5,
            "coolValue": 5,
            "windowSensor": false,
            "devType": "thermostat"
        },
        "Test Outlet Device": {
            "active": false,
            "ain": "01234567890",
            "tempSensor": false,
            "devType": "switch"
        }
    },
    "callmonitor": {
        "active": false,
        "ip": "0.0.0.0",
        "port": 1012
    },
    "presence": {
        "user": [
            {
                "active": true,
                "name": "Iphone Giovanni",
                "address": "192.168.2.45"
            },
            {
                "active": true,
                "name": "iPhone di Maria Luisa",
                "address": "192.168.2.46"
            },
            {
                "active": true,
                "name": "iPhone di Ciro",
                "address": "192.168.2.61"
            }
        ],
        "anyone": true,
        "offDelay": 90,
        "onDelay": 15,
        "ping": false
    },
    "wol": [
        {
            "active": false,
            "name": "Test Device",
            "address": "00:00:00:00:00:00"
        }
    ],
    "phoneBook": {
        "active": true
    },
    "alarm": {
        "active": false,
        "duration": 30
    },
    "wakeup": {
        "active": false,
        "duration": 30
    },
    "ringlock": {
        "active": true,
        "DECTphones": 1,
        "start": "11:00",
        "end": "22:00"
    },
    "broadband": {
        "active": false,
        "measureTime": 5
    },
    "extReboot": {
        "active": false
    },
    "telegram": {
        "active": false
    },
    "polling": 10,
    "timeout": 10,
    "clearCache": false,
    "debug": false,
    "disableAutoSearch": false,
    "disableAutoConfig": false
}

**Comment by marcusklebrowski** [comment]
"disableAutoSearch": true,  <—- false
"disableAutoConfig": true   <—- false 

Try  this

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed in v5 (coming soon)
