### ISSUE TITLE
Engine dependencies in package.json

### ISSUE THREAD

**Issue by m-arx** [SeydX/homebridge-fritz-platform#83]
**Describe the bug**
Engine dependencies are set to specific node and homebridge (10.15.3 and 0.4.49) versions.

**To Reproduce**
package.json Line 49..52:

"engines": {                                                        
    "homebridge": "^0.4.49",                                          
    "node": "^v10.15.3"                                               
  },  

**Expected behavior**
Plugin seems to work with homebridge 1.1.0 and node 12.16.3 - may be change the existing ones to minimum version?

**Comment by udovic2100** [comment]
See pull request #77. @SeydX needs to accept the changes.

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed in v5 (coming soon)
