### ISSUE TITLE
Hide the switch for rebooting the Fritzbox

### ISSUE THREAD

**Issue by mvoigt1971** [SeydX/homebridge-fritz-platform#86]
**Is your feature request related to a problem? Please describe.**
The switch for the Fritzbox reboot is very dangerous. It is very easy to press the switch without purpose. 

**Describe the solution you'd like**
It should be possible to hide the switch to reboot the Fritzbox with a configuration preference like the other switches.

**Describe alternatives you've considered**
There is no need for this switch. It could be deleted from the code.

**Comment by SeydX** [comment]
You can set „readOnly“ to true in config.json to deactivate the reboot switch functionality

**Comment by Trackhe** [comment]
But can you add in the next time a hidde funktion? Please

**Comment by Jemeins** [comment]
I also have no use of the button. A way to hide it would be great!

**Comment by SeydX** [comment]
https://github.com/SeydX/homebridge-fritz-platform/issues/50
