### ISSUE TITLE
Feature Request: Support for Fritz!DECT 500 Lights

### ISSUE THREAD

**Issue by EpsilonAlpha** [SeydX/homebridge-fritz-platform#89]
Like the Subject said: Hope we can add support for Fritz!DECT 500 Lights 😃

**Comment by computergott** [comment]
+1

**Comment by SeydX** [comment]
I would love to, but unfortunately I have no "SmartHome" devices for the FritzBox to implement it :/

**Comment by EpsilonAlpha** [comment]
Can I provide information for you to implement it? :)

**Comment by SeydX** [comment]
Added in v5.0.0-beta.24

**Comment by SeydX** [comment]
@EpsilonAlpha 

DECT 500 is fully supported now (also color adjustment through homekit)

**Comment by EpsilonAlpha** [comment]
Thank you 🙏
