### ISSUE TITLE
FritzPlatform - Version 5 Beta

### ISSUE THREAD

**Issue by SeydX** [SeydX/homebridge-fritz-platform#92]
Hey guys,

i am currently working on the 5th version of the plugin and have already fixed many of the bugs that you have encountered. There are also some new features.

## Changelog (2020-11-06)

- Completely rewritten
- New: Homebridge (latest/beta) Support
- New: Config UI X Integration
- New: Polling with additional functions (exclude accessories)
- New: Possibility to display all 'Extras' like Wifi, Alarm, Led etc etc as Characteristic or as a separate switch in Apple Home
- New: Network Watch
- New: Configurable Callmonitor names
- New: Group Callmonitor sensors
- New: DECT station
- New: Ability to hide devices (router)
- New: Additional ping for presence
- New: Ability to change accessory typ for presence and anyone sensor, with FakeGato support
- New: Smarthome devices with FakeGato Support
- New: Smarthome Outlet Accessory with Fakegato for powermeter
- New: Smarthome Window Accessory with Fakegato for devices with built in windowOpen function
- New: Support for SmartHome Lights (only on/off and brightness)
- Removed: Broadband for compatibility reasons

## Beta Test

If you want to test the version you can use the following command:

``sudo npm i -g --unsafe-perm homebridge-fritz-platform@beta``

**Attention:** The new version is not compatible with version < 5! Due to the Config UI X integration I had to change the config.json! See also **TODO**

## TODO
- [ ] SmartHome: Lightbulbs  with color functionality

## Debugging & Bugs & Enhancements

Please enable "**Debug**" under Configuration before testing the beta version. If you have any bugs, suggestions for improvement or other ideas, you can write it here.

## Config
- [Example Config](https://github.com/SeydX/homebridge-fritz-platform/blob/beta/example/example-config.json)

Have fun testing,

**SeydX**

**Comment by MirkoKas** [comment]
Great to hear yo are working on v5. Is there also an minimal config example?

**Comment by SeydX** [comment]
@MirkoKas 

i recommend to use Config UI X. FritzPlatform Config is perfectly fitted into it so it is very easy to adjust

**Comment by Trackhe** [comment]
"SmartHome devices are not yet integrated" hab gelesen das es schwer für Dich ist da du das Produkt ja nicht testen kannst.
Was heißt das zb für mich? Da ich meine Heizungen über die FB steuere. Geld um dir mal eben ein Termostat zu kaufen hab ich leider auch nicht.
Kann aber sagen das die steuerung über die alte version des Plugins noch ging. nur durch die ganzen errors. kam es dann bei allen geräten zu warte zeiten usw.

Mein Angebot zu chatten und zu helfen beim Coden steht noch.

**Comment by SeydX** [comment]
@Trackhe 

Ich meinte mit der Aussage nicht das mir jemand die Geräte kaufen soll ^^ aber Danke

übers Chatten wird das leider schwer und aufwendig für mich zu debuggen.

Ja in der 4. Version hat es zwar funktioniert, aber die Implementation ist so nicht richtig weswegen ich alles neu schreiben. Zu der Zeit hatte mir jemand die Geräte geliehen damit ich es implementieren kann. Habe jetzt AVM geschrieben, evtl. geben Sie Testgeräte raus damit ich es implementieren kann. Warte noch auf Antwort.

lg

**Comment by Trackhe** [comment]
Wäre cool aber da bin ich tatsächlich ziehmlich pessimistisch. Aber mann kann ja auch zb über teamspeak oder Discord reden. und Über teamviewer zb arbeiten. Zumindest in dem fall mit denn Heizungen.

**Comment by SeydX** [comment]
@Trackhe 

wenn ich die Basis erstmal implementiert habe, komme ich aufjedenfall auf dich zurück zum weiteren debuggen (falls in der Zukunft Fehler auftreten)

lg

**Comment by CM-UH** [comment]
Hi,
toll das du dieses Plugin weiter vorantreibst, da warte ich schon lange drauf.
Ich hatte die V5.7 gester getestet lief für mich super!
Heute auf dem Produktiv Raspi installiert V5.8 dann kommt dieses log:

> Oct 31 12:11:15 raspberrypi homebridge[28877]: [2020-10-31 12:11:15] TypeError [ERR_INVALID_URL]: Invalid URL: http://192.168.2.2:undefined
Oct 31 12:11:15 raspberrypi homebridge[28877]:     at onParseError (internal/url.js:256:9)
Oct 31 12:11:15 raspberrypi homebridge[28877]:     at new URL (internal/url.js:332:5)
Oct 31 12:11:15 raspberrypi homebridge[28877]:     at new Fritzbox (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/src/lib/fritzbox.ts:86:16)
Oct 31 12:11:15 raspberrypi homebridge[28877]:     at /usr/local/lib/node_modules/homebridge-fritz-platform/src/platform.js:72:38
Oct 31 12:11:15 raspberrypi homebridge[28877]:     at Array.map (<anonymous>)
Oct 31 12:11:15 raspberrypi homebridge[28877]:     at new FritzPlatform (/usr/local/lib/node_modules/homebridge-fritz-platform/src/platform.js:69:25)
Oct 31 12:11:15 raspberrypi homebridge[28877]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:395:40
Oct 31 12:11:15 raspberrypi homebridge[28877]:     at Array.forEach (<anonymous>)
Oct 31 12:11:15 raspberrypi homebridge[28877]:     at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
Oct 31 12:11:15 raspberrypi homebridge[28877]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
Oct 31 12:11:15 raspberrypi homebridge[28877]: [2020-10-31 12:11:15] Got SIGTERM, shutting down Homebridge...

**Comment by SeydX** [comment]
@CM-UH 

im config port eingegeben?

**Comment by nexusle** [comment]
> @Trackhe
> 
> Ich meinte mit der Aussage nicht das mir jemand die Geräte kaufen soll ^^ aber Danke
> 
> übers Chatten wird das leider schwer und aufwendig für mich zu debuggen.
> 
> Ja in der 4. Version hat es zwar funktioniert, aber die Implementation ist so nicht richtig weswegen ich alles neu schreiben. Zu der Zeit hatte mir jemand die Geräte geliehen damit ich es implementieren kann. Habe jetzt AVM geschrieben, evtl. geben Sie Testgeräte raus damit ich es implementieren kann. Warte noch auf Antwort.
> 
> lg

Ich kann Dir eine Steckdose leihen. Da hängt sonst die Poolpumpe dran, alsowird sie im Moment nicht benötigt. Gib mir kurz Beschrid.

**Comment by CM-UH** [comment]
Hast Recht bei V5.8 muss man den Port explizit angeben -> funktioniert!
Mir ist aber aufgefallen im Log der Fritzbox wird das PowerLan ständif ein und ausgeschalten, seit ich das Plugin nutze:

> 31.10.20
12:32:40
[e8:df:70:0d:58:a8] Powerline ist an und verbunden.
31.10.20
12:32:37
[e8:df:70:0d:58:a8] Powerline ist an. Es ist kein Adapter verbunden.
31.10.20
12:32:36
[e8:df:70:0d:58:a8] Die Powerline-Funktion ist ausgeschaltet.
31.10.20
12:30:38
[e8:df:70:0d:58:a8] Powerline ist an und verbunden.
31.10.20
12:30:35
[e8:df:70:0d:58:a8] Powerline ist an. Es ist kein Adapter verbunden.
31.10.20
12:30:34
[e8:df:70:0d:58:a8] Die Powerline-Funktion ist ausgeschaltet.

**Comment by SeydX** [comment]
@CM-UH 

Ich habe selber 3 PowerLans im Einsatz und bei mir ist nichts dergleichen. Seltsam. Ist es wirklich auf das Plugin zurückzuführen? Mal probiert ob die Meldungen auch ohne das Plugin kommen? Kann mir nicht vorstellen das das Plugin was damit zu tun hat, da es die PowerLans garnicht triggern kann.

**Comment by SeydX** [comment]
Das mit Port habe ich bereits gefixt und kommt dann in der nächsten Version, da muss man es nicht explizit setzen dann

**Comment by CM-UH** [comment]
@SeydX 
Das scheint seit dem Update der Fritzbox 7,21 zu sein, Sorry daran hatte ich nicht mehr gedacht

**Comment by SeydX** [comment]
Ich habe soebend eine Antwort von AVM erhalten und Sie werden das Projekt tatsächlich mit einem SmartHome Set unterstützen.

Liebe Grüße

**Comment by Zer0x00** [comment]
I'm getting the following error with Beta 13:
```
[05/11/2020, 15:20:14] [Sonos] error: TypeError: Cannot read property 'send' of undefined
    at routerService.change (/usr/lib/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:1594:20)
    at On.emit (events.js:327:22)
    at On.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at On.Characteristic._this.updateValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:700:12)
    at get (/usr/lib/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:240:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.poll (/usr/lib/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:1637:15)
```

On the stable version of this plugin there was a warning, see https://github.com/ebaauw/homebridge-lib/issues/28
However this seems to affect multiple plugins: https://github.com/ebaauw/homebridge-hue/issues/629#issuecomment-592588385

**Comment by SeydX** [comment]
@Zer0x00 

thx, i have fixed the error with

``TypeError: Cannot read property 'send' of undefined``

does the error with http-proxy also occure on the beta version?

**Comment by Zer0x00** [comment]
@SeydX 

Thank you! No, the warning with http-proxy didn't appear for me on beta 13.
Whereby I have to say that I'm using the beta for a few minutes right now.

Will inform you if I see any further errors / warnings.

**Comment by SeydX** [comment]
@Zer0x00 

v5.0.0-beta.16 is online

**Comment by SeydX** [comment]
v5.0.0-beta.20 is online with SmartHome support (atm only contact sensor, thermostat and switches)

**Comment by nexusle** [comment]
> v5.0.0-beta.20 is online with SmartHome support (atm only contact sensor, thermostat and switches)

Couldn't install this version from Homebridge UI. Still on beta16

**Comment by SeydX** [comment]
v5.0.0-beta.24 is online

- Added support for SmartHome Lights eg FritzDECT 500 Light

All those who have SmartHome lamps should please test this function. Because I do not have SmartHome lamps I could not test it.

**Comment by Zer0x00** [comment]
My logfile currently looks like this:
```
[08/11/2020, 21:49:21] [FritzPlatform] iPhone 2.4GHz: Occupancy state changed to DETECTED
[08/11/2020, 21:49:21] [FritzPlatform] iPhone 2.4GHz: Wait 30s before switching state!
[08/11/2020, 21:50:11] [FritzPlatform] iPhone 2.4GHz: Occupancy state changed to NOT DETECTED
[08/11/2020, 21:50:11] [FritzPlatform] iPhone 2.4GHz: Wait 90s before switching state!
[08/11/2020, 21:51:03] [FritzPlatform] iPhone 2.4GHz: Occupancy state switched back to DETECTED
[08/11/2020, 21:51:35] [FritzPlatform] iPhone 2.4GHz: Occupancy state changed to NOT DETECTED
[08/11/2020, 21:51:35] [FritzPlatform] iPhone 2.4GHz: Wait 90s before switching state!
[08/11/2020, 21:53:25] [FritzPlatform] iPhone 2.4GHz: Occupancy state changed to DETECTED
[08/11/2020, 21:53:25] [FritzPlatform] iPhone 2.4GHz: Wait 30s before switching state!
[08/11/2020, 21:54:26] [FritzPlatform] iPhone 2.4GHz: Occupancy state changed to NOT DETECTED
[08/11/2020, 21:54:26] [FritzPlatform] iPhone 2.4GHz: Wait 90s before switching state!
[08/11/2020, 21:55:35] [FritzPlatform] iPhone 2.4GHz: Occupancy state switched back to DETECTED
[08/11/2020, 21:56:10] [FritzPlatform] iPhone 2.4GHz: Occupancy state changed to NOT DETECTED
[08/11/2020, 21:56:10] [FritzPlatform] iPhone 2.4GHz: Wait 90s before switching state!
[08/11/2020, 21:58:09] [FritzPlatform] iPhone 2.4GHz: Occupancy state changed to DETECTED
[08/11/2020, 21:58:09] [FritzPlatform] iPhone 2.4GHz: Wait 30s before switching state!
[08/11/2020, 21:59:40] [FritzPlatform] iPhone 2.4GHz: Occupancy state changed to NOT DETECTED
[08/11/2020, 21:59:40] [FritzPlatform] iPhone 2.4GHz: Wait 90s before switching state!
[08/11/2020, 21:59:55] [FritzPlatform] iPhone 2.4GHz: Occupancy state switched back to DETECTED
```

Is there a chance that you could integrate one more parameter to the config.json that the user can define the timeout value before changing to the 'NOT DETECTED' state?

**Comment by SeydX** [comment]
@Zer0x00 

which version? and can u post your config please? only the presence part

**Comment by Zer0x00** [comment]
@SeydX 

I'm on v5.0.0-beta.30.

```json
            "presence": [
                {
                    "name": "iPhone 2.4GHz",
                    "address": "<MAC 1>",
                    "accType": "occupancy",
                    "ping": true
                },
                {
                    "name": "iPhone 5GHz",
                    "address": "<MAC 2>",
                    "accType": "occupancy",
                    "ping": true
                },
                {
                    "name": "iPhone 2 2.4GHz",
                    "address": "<MAC 3>",
                    "accType": "occupancy",
                    "ping": true
                },
                {
                    "name": "iPhone 2 5GHz",
                    "address": "<MAC 4>",
                    "accType": "occupancy",
                    "ping": true
                }
            ]
```

**Comment by SeydX** [comment]
@Zer0x00 

do you have issues without "ping" enabled?

But yes, you can adjust the timeout for DETECTED and NOT DETECTED

look at here: [Example Config](https://github.com/SeydX/homebridge-fritz-platform/blob/89e885b2c6041d1f63d3b5c954acc93aa46f9797/example/example-config.json#L183)

"onDelay" means the thimeout before switching to DETECTED
"offDelay" means the timeout before switching to NOT DETECTED

"ping" is only a additional feature for people where the default presence function (without ping) doesnt works properly. You can also adjust a threshold time for ping, look here [Example Config](https://github.com/SeydX/homebridge-fritz-platform/blob/89e885b2c6041d1f63d3b5c954acc93aa46f9797/example/example-config.json#L93)

**Comment by Zer0x00** [comment]
@SeydX 

Didn't test it before with ping on false but a short test seems like it's doing the job well! 👍

**Comment by SeydX** [comment]
Closing this issue. V5.0.0 is online

Thanks alö!
