### ISSUE TITLE
Smarthome accessoires are displayed as icons with a house, not as a switch

### ISSUE THREAD

**Issue by nexusle** [SeydX/homebridge-fritz-platform#95]
Hey,

I switched today to beta5. The config isn't migrated to the new version so I had to reconfigure the addon. Not that thing...

After I setup my 3 smarthome devices (DECT) I see these devices with a house-icon in homekit and not as a switch.

My config (without the AIN):

"smarthome": [
                {
                    "name": "Server",
                    "ain": "xxxxxxxxxxxx",
                    "accType": "switch"
                },
                {
                    "name": "Rasensprenger",
                    "ain": "xxxxxxxxxxxx",
                    "accType": "switch"
                },
                {
                    "name": "Pool",
                    "ain": "xxxxxxxxxxxx",
                    "accType": "switch"
                }
            ],

**Comment by SeydX** [comment]
Please read the pinned issue for v5

https://github.com/SeydX/homebridge-fritz-platform/issues/92

**Smarthome devices are not implemented yet**
