### ISSUE TITLE
V5 Cant get it to run

### ISSUE THREAD

**Issue by Christian-CFP** [SeydX/homebridge-fritz-platform#97]
Hi, I deleted the older version and reinstalled the newer one.

Error messages:
10.11.2020, 07:41:02 [11/9/2020, 11:41:02 PM] The dynamic platform FritzPlatform from the plugin homebridge-fritz-platform seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!
10.11.2020, 07:41:03 [FritzPlatform] FRITZBox 7590 (UI) Wifi 2ghz: Configuring accessory...
10.11.2020, 07:41:03 [FritzPlatform] FRITZBox 7590 (UI) Wifi 2ghz: Adding Switch service
10.11.2020, 07:41:03 (node:1848) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: d052aa1a-69ee-4a4e-b293-acc6a66c1f06
10.11.2020, 07:41:03 at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:288:27)
10.11.2020, 07:41:03 at Bridge.Accessory._this.addBridgedAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:313:23)
10.11.2020, 07:41:03 at Server.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:472:21)
10.11.2020, 07:41:03 at HomebridgeAPI.emit (events.js:314:20)
10.11.2020, 07:41:03 at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/api.js:131:14)
10.11.2020, 07:41:03 at FritzPlatform.didFinishLaunching (/home/hoobs/.hoobs/node_modules/homebridge-fritz-platform/src/platform.js:645:18)
10.11.2020, 07:41:03 (node:1848) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
10.11.2020, 07:41:03 (node:1848) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

10.11.2020, 07:54:42 [FritzPlatform] FRITZBox 7590 (UI): An error occured during getting state (router)
10.11.2020, 07:54:42 [FritzPlatform] Error: Invalid response: 401:Unauthorized
    at Request._callback (/home/hoobs/.hoobs/node_modules/@seydx/fritzbox/dist/lib/request.js:18:28)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

My config:
{
            "name": "FritzPlatform",
            "debug": true,
            "devices": [
                {
                    "name": "FRITZBox 7590 (UI)",
                    "host": "192.168.100.254",
                    "port": 49000,
                    "username": "xxx",
                    "password": "xxx",
                    "manufacturer": "Fritz Box",
                    "model": "7590 (UI)",
                    "serialNumber": "xxxx.xxx.xxx.xxx",
                    "master": true,
                    "ssl": true,
                    "tr064": true,
                    "igd": true,
                    "readOnly": false,
                    "hide": true,
                    "connection": "dsl",
                    "options": {
                        "wifi_2ghz": "switch",
                        "wifi_5ghz": "switch",
                        "wifi_guest": "switch",
                        "wps": "characteristic",
                        "aw": "characteristic",
                        "led": "switch",
                        "lock": "switch",
                        "dect": "switch"
                    }
                },
                {
                    "name": "FRITZWLAN Repeater 1750E",
                    "host": "192.168.100.253",
                    "port": 49000,
                    "username": "xxx",
                    "password": "xxx",
                    "manufacturer": "Fritz Box",
                    "model": "Repeater 1750E",
                    "serialNumber": "xxxx.xxx.xxx.xxx",
                    "readOnly": false,
                    "connection": "repeater",
                    "hide": false,
                    "ssl": true,
                    "tr064": true,
                    "igd": true,
                    "options": {
                        "led": "switch",
                        "lock": "characteristic"
                    }
                },
                {
                    "name": "FRITZRepeater 1200",
                    "host": "192.168.100.252",
                    "port": 49000,
                    "username": "xxx",
                    "password": "xxx",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "manufacturer": "Fritz Box",
                    "model": "Repeater 1200",
                    "serialNumber": "xxxx.xxx.xxx.xxx",
                    "readOnly": false,
                    "oldFW": true,
                    "connection": "repeater",
                    "hide": false,
                    "options": {
                        "led": "switch",
                        "lock": "characteristic"
                    }
                }
            ],
            "presence": [
                {
                    "name": "xxx",
                    "address": "xxx",
                    "accType": "occupancy",
                    "ping": true,
                    "threshold": 15
                },
                {
                    "name": "xxx",
                    "address": "xxx",
                    "accType": "occupancy",
                    "ping": true,
                    "threshold": 15
                },
                {
                    "name": "xxx",
                    "address": "xxx",
                    "accType": "occupancy",
                    "ping": true,
                    "threshold": 15
                },
                {
                    "name": "xxx",
                    "address": "xxx",
                    "accType": "occupancy",
                    "ping": true,
                    "threshold": 15
                }
            ],
            "callmonitor": {
                "active": true,
                "group": true,
                "ip": "192.168.100.254",
                "port": 1012,
                "incomingTo": [
                    "Xxx",
                    "Xxx"
                ],
                "outgoingFrom": [
                    "Xxx",
                    "Xxx"
                ]
            },
            "extras": {
                "alarm": {
                    "active": false,
                    "duration": 30,
                    "telNr": "xxx",
                    "accType": "switch"
                },
                "wakeup": {
                    "active": false,
                    "duration": 30,
                    "internNr": "**620",
                    "accType": "characteristic"
                },
                "ringlock": {
                    "active": false,
                    "DECTphones": 1,
                    "start": "11:00",
                    "end": "22:00",
                    "accType": "characteristic"
                },
                "phoneBook": {
                    "active": true,
                    "duration": 30,
                    "accType": "characteristic",
                    "blacklists": [
                        "Blacklist"
                    ]
                }
            },
            "options": {
                "presence": {
                    "anyone": true,
                    "onDelay": 20,
                    "offDelay": 90
                },
                "reboot": {
                    "on": "/home/hoobs/scripts/reboot-start.sh",
                    "off": "/home/hoobs/scripts/reboot-finished.s"
                },
                "polling": {
                    "timer": 10,
                    "exclude": [
                        "router",
                        "extra"
                    ]
                }
            },
            "telegram": {
                "active": false,
                "token": "xxx",
                "chatID": "xxx",
                "messages": {
                    "presence": {
                        "user_in": "Welcome at home @",
                        "user_out": "Bye Bye @",
                        "anyone_in": "Someone is at home!",
                        "anyone_out": "Nobody at home!"
                    },
                    "callmonitor": {
                        "incoming": "Incoming call from @",
                        "outgoing": "Outgoing call to @",
                        "disconnected": "Call with @ disconnected"
                    },
                    "alarm": {
                        "activated": "Alarm activated",
                        "deactivated": "Alarm deactivated"
                    },
                    "reboot": {
                        "start": "@: Offline!",
                        "finish": "@: Online!"
                    },
                    "network": {
                        "on": "@ is in network!",
                        "off": "@ not in network!"
                    }
                }
            },
            "platform": "FritzPlatform"
        },

**Comment by Christian-CFP** [comment]
Somehow I managed by changing devicenames different times to get them into HK but nothing seems to work:

10.11.2020, 10:07:21 [FritzPlatform] Hosts: An error occured during polling state (hosts)
10.11.2020, 10:07:21 [FritzPlatform] Error: Invalid response: 401:Unauthorized
    at Request._callback (/home/hoobs/.hoobs/node_modules/@seydx/fritzbox/dist/lib/request.js:18:28)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by Christian-CFP** [comment]
EDIT: 1750E and 1200 does work... ? ... But the 7590 does not. Shown as switch "off".

**Comment by Christian-CFP** [comment]
No:

10.11.2020, 10:14:25 [FritzPlatform] Hosts: Could not process the request during polling state (hosts)
10.11.2020, 10:14:35 [FritzPlatform] Hosts: Could not process the request during polling state (hosts)
10.11.2020, 10:14:45 [FritzPlatform] Hosts: Could not process the request during polling state (hosts)
10.11.2020, 10:14:55 [FritzPlatform] Hosts: Could not process the request during polling state (hosts)
10.11.2020, 10:14:59 [FritzPlatform] FRITZ!Repeater 1750E: Device seems to be offline (router)
10.11.2020, 10:14:59 [FritzPlatform] FRITZ!Repeater 1200: Device seems to be offline (router)
10.11.2020, 10:14:59 [FritzPlatform] FRITZ!Box 7590 Wifi guest: Could not process the request during getting state (wifi_guest)
10.11.2020, 10:14:59 [FritzPlatform] FRITZ!Box 7590 Wifi 5ghz: Could not process the request during getting state (wifi_5ghz)
10.11.2020, 10:14:59 [FritzPlatform] FRITZ!Box 7590 Wifi 2ghz: Could not process the request during getting state (wifi_2ghz)
10.11.2020, 10:14:59 [FritzPlatform] FRITZ!Box 7590 Wps: Could not process the request during getting state (wps)
10.11.2020, 10:14:59 [FritzPlatform] FRITZ!Box 7590: Could not process the request during getting state (router)
10.11.2020, 10:15:05 [FritzPlatform] Hosts: Could not process the request during polling state (hosts)
10.11.2020, 10:15:15 [FritzPlatform] Hosts: Could not process the request during polling state (hosts)
10.11.2020, 10:15:25 [FritzPlatform] Hosts: Could not process the request during polling state (hosts)
10.11.2020, 10:15:35 [FritzPlatform] Hosts: Could not process the request during polling state (hosts)
10.11.2020, 10:15:45 [FritzPlatform] Hosts: Could not process the request during polling state (hosts)
10.11.2020, 10:15:55 [FritzPlatform] Hosts: Could not process the request during polling state (hosts)
10.11.2020, 10:16:05 [FritzPlatform] Hosts: Could not process the request during polling state (hosts)
10.11.2020, 10:16:15 [FritzPlatform] Hosts: Could not process the request during polling state (hosts)
10.11.2020, 10:16:25 [FritzPlatform] Hosts: An error occured during polling state (hosts)
10.11.2020, 10:16:25 [FritzPlatform] Error: Invalid response: 401:Unauthorized
    at Request._callback (/home/hoobs/.hoobs/node_modules/@seydx/fritzbox/dist/lib/request.js:18:28)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
10.11.2020, 10:16:35 [FritzPlatform] Hosts: An error occured during polling state (hosts)
10.11.2020, 10:16:35 [FritzPlatform] Error: Invalid response: 401:Unauthorized
    at Request._callback (/home/hoobs/.hoobs/node_modules/@seydx/fritzbox/dist/lib/request.js:18:28)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
10.11.2020, 10:16:45 [FritzPlatform] Hosts: Could not process the request during polling state (hosts)

**Comment by SeydX** [comment]
Check your log... the given user in config is unauthorized

Do you have any special chars in your username/password??

**Comment by Christian-CFP** [comment]
Usernasme and PWD are correct. And jes some chars but they worked in the v4.

**Comment by SeydX** [comment]
Try with a simpler password pls without any special chars

For now the plugin can not login with special chars, will try to fix it in a later version

**Comment by Christian-CFP** [comment]
chars PWD: */$

**Comment by SeydX** [comment]
Try a password with letter and numbers only

**Comment by Christian-CFP** [comment]
Ok, changes it, but this happend, now I have to change the device names back and forth until it gets it right...:

10.11.2020, 10:30:48 [FritzPlatform] Callmonitor connection established with 192.168.100.254:1012
10.11.2020, 10:30:48 [FritzPlatform] FRITZ!Box 7590: Configuring accessory...
10.11.2020, 10:30:48 [FritzPlatform] FRITZ!Box 7590: Adding Switch service
10.11.2020, 10:30:48 [FritzPlatform] FRITZ!Box 7590: Adding DECT characteristic
10.11.2020, 10:30:48 [FritzPlatform] FRITZ!Box 7590: Adding AnsweringMachine characteristic
10.11.2020, 10:30:48 [FritzPlatform] FRITZ!Box 7590: Adding Deflection characteristic
10.11.2020, 10:30:48 [FritzPlatform] FRITZ!Box 7590: Adding DeviceLED characteristic
10.11.2020, 10:30:48 [FritzPlatform] FRITZ!Box 7590: Adding DeviceLock characteristic
10.11.2020, 10:30:48 [FritzPlatform] FRITZ!Box 7590: Adding PhoneBook characteristic
10.11.2020, 10:30:48 (node:4422) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 8ab25b5e-8843-4e7c-b921-309c45dec7e0
10.11.2020, 10:30:48 at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:288:27)
10.11.2020, 10:30:48 at Bridge.Accessory._this.addBridgedAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:313:23)
10.11.2020, 10:30:48 at Server.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:472:21)
10.11.2020, 10:30:48 at HomebridgeAPI.emit (events.js:314:20)
10.11.2020, 10:30:48 at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/api.js:131:14)
10.11.2020, 10:30:48 at FritzPlatform.didFinishLaunching (/home/hoobs/.hoobs/node_modules/homebridge-fritz-platform/src/platform.js:645:18)
10.11.2020, 10:30:48 (node:4422) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
10.11.2020, 10:30:48 (node:4422) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
10.11.2020, 10:30:48 [FritzPlatform] FRITZ!Box 7590: Removing accessory...

**Comment by SeydX** [comment]
It seems that the first error you got

```
[11/9/2020, 11:41:02 PM] The dynamic platform FritzPlatform from the plugin homebridge-fritz-platform seems to be configured multiple times in your config.json. 
```

Has done something wrong with your cache. Remove the fritzplatzform from your config pls. Restart homebridge and wait till all devices gone from homekit. 

Than put it again into your config and restart homebridge

**Comment by Christian-CFP** [comment]
Now the repeater seems to be offline:


10.11.2020, 10:44:47 [FritzPlatform] FRITZ!Repeater 1750E: Device seems to be offline (router)
10.11.2020, 10:44:47 [FritzPlatform] FRITZ!Repeater 1200: Device seems to be offline (router)

**Comment by Christian-CFP** [comment]
Shall I set igd to false on them?

**Comment by SeydX** [comment]
> Shall I set igd to false on them?

Yes

**Comment by Christian-CFP** [comment]
Ok, that does the trick but everytime I start HB, all the accessoires will be removed.
Isnt there a clearcache: false option anymore?

**Comment by SeydX** [comment]
Can u post your config pls

**Comment by Christian-CFP** [comment]
{
            "platform": "FritzPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-fritz-platform"
            },
            "name": "FritzPlatform",
            "debug": true,
            "devices": [
                {
                    "name": "Fritz!Box 7590",
                    "host": "192.168.100.254",
                    "port": 49000,
                    "username": "xxxx",
                    "password": "xxxx",
                    "manufacturer": "AVM",
                    "model": "Fritz!Box 7590",
                    "serialNumber": "xxxx",
                    "master": true,
                    "ssl": true,
                    "tr064": true,
                    "igd": true,
                    "readOnly": false,
                    "hide": false,
                    "connection": "dsl",
                    "options": {
                        "deflection": "characteristic",
                        "wifi_2ghz": "switch",
                        "wifi_5ghz": "switch",
                        "wifi_guest": "switch",
                        "wps": "switch",
                        "aw": "characteristic",
                        "led": "characteristic",
                        "lock": "characteristic",
                        "dect": "characteristic"
                    }
                },
                {
                    "name": "Repeater 1750E",
                    "host": "192.168.100.253",
                    "port": 49000,
                    "username": "xxxx",
                    "password": "xxxx",
                    "manufacturer": "AVM",
                    "model": "FRITZ!WLAN Repeater 1750E",
                    "serialNumber": "xxxx",
                    "readOnly": false,
                    "connection": "repeater",
                    "hide": false,
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "options": {
                        "wifi_2ghz": "characteristic",
                        "wifi_5ghz": "characteristic",
                        "wifi_guest": "characteristic",
                        "wps": "characteristic",
                        "led": "characteristic",
                        "lock": "characteristic"
                    }
                },
                {
                    "name": "Repeater 1200",
                    "host": "192.168.100.252",
                    "port": 49000,
                    "username": "xxxx",
                    "password": "xxxx",
                    "manufacturer": "AVM",
                    "model": "FRITZ!Repeater 1200",
                    "serialNumber": "xxxx",
                    "readOnly": false,
                    "connection": "repeater",
                    "hide": false,
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "options": {
                        "wifi_2ghz": "characteristic",
                        "wifi_5ghz": "characteristic",
                        "wifi_guest": "characteristic",
                        "wps": "characteristic",
                        "led": "characteristic",
                        "lock": "characteristic"
                    }
                }
            ],
            "presence": [
                {
                    "name": "xxxx",
                    "address": "xxxx",
                    "accType": "occupancy",
                    "ping": false,
                    "threshold": 15
                },
                {
                    "name": "xxxx",
                    "address": "xxxx",
                    "accType": "occupancy",
                    "ping": false,
                    "threshold": 15
                },
                {
                    "name": "xxxx",
                    "address": "xxxx",
                    "accType": "occupancy",
                    "ping": false,
                    "threshold": 15
                },
                {
                    "name": "xxxx",
                    "address": "xxxx",
                    "accType": "occupancy",
                    "ping": false,
                    "threshold": 15
                }
            ],
            "callmonitor": {
                "active": true,
                "group": true,
                "ip": "192.168.100.254",
                "port": 1012,
                "incomingTo": [
                    "xxxx",
                    "xxxx"
                ],
                "outgoingFrom": [
                    "xxxx",
                    "xxxx"
                ]
            },
            "extras": {
                "alarm": {
                    "active": false,
                    "duration": 30,
                    "telNr": "xxxx",
                    "accType": "switch"
                },
                "wakeup": {
                    "active": false,
                    "duration": 30,
                    "internNr": "**620",
                    "accType": "characteristic"
                },
                "ringlock": {
                    "active": false,
                    "DECTphones": 1,
                    "start": "11:00",
                    "end": "22:00",
                    "accType": "characteristic"
                },
                "phoneBook": {
                    "active": true,
                    "duration": 30,
                    "accType": "characteristic",
                    "blacklists": [
                        "Blacklist"
                    ]
                }
            },
            "options": {
                "presence": {
                    "anyone": true,
                    "onDelay": 10,
                    "offDelay": 90,
                    "accType": "occupancy"
                },
                "reboot": {
                    "on": "/home/hoobs/scripts/reboot-start.sh",
                    "off": "/home/hoobs/scripts/reboot-finished.s"
                },
                "polling": {
                    "timer": 10,
                    "exclude": [
                        "router",
                        "extra"
                    ]
                }
            }
        },

**Comment by SeydX** [comment]
This should not happen. Homebridge seems not to cache the accessories. Did you try to delete the plugin from the config, restart Homebridge and add it back to the config?

**Comment by Christian-CFP** [comment]
That works. But I have to do it every time. Just now. It works, that the 5.0.2 update. All gone. Removing all devices.

**Comment by SeydX** [comment]
Works now?

**Comment by Christian-CFP** [comment]
Only until I restart the service:

10.11.2020, 11:23:36 [FritzPlatform] Fritz!Box 7590: Configuring accessory...
10.11.2020, 11:23:36 [FritzPlatform] Fritz!Box 7590: Adding Switch service
10.11.2020, 11:23:36 [FritzPlatform] Fritz!Box 7590: Adding DECT characteristic
10.11.2020, 11:23:36 [FritzPlatform] Fritz!Box 7590: Adding AnsweringMachine characteristic
10.11.2020, 11:23:36 [FritzPlatform] Fritz!Box 7590: Adding Deflection characteristic
10.11.2020, 11:23:36 [FritzPlatform] Fritz!Box 7590: Adding DeviceLED characteristic
10.11.2020, 11:23:36 [FritzPlatform] Fritz!Box 7590: Adding DeviceLock characteristic
10.11.2020, 11:23:36 [FritzPlatform] Fritz!Box 7590: Adding PhoneBook characteristic
10.11.2020, 11:23:36 (node:3795) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: ba7aa3b8-20dd-45cb-8d23-f4bfbf2eebaf
10.11.2020, 11:23:36 at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:288:27)
10.11.2020, 11:23:36 at Bridge.Accessory._this.addBridgedAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:313:23)
10.11.2020, 11:23:36 at Server.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:472:21)
10.11.2020, 11:23:36 at HomebridgeAPI.emit (events.js:314:20)
10.11.2020, 11:23:36 at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/api.js:131:14)
10.11.2020, 11:23:36 at FritzPlatform.didFinishLaunching (/home/hoobs/.hoobs/node_modules/homebridge-fritz-platform/src/platform.js:645:18)
10.11.2020, 11:23:36 (node:3795) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
10.11.2020, 11:23:36 (node:3795) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
10.11.2020, 11:23:36 [FritzPlatform] Fritz!Box 7590: Removing accessory...
10.11.2020, 11:23:36 [FritzPlatform] Fritz!Box 7590 Wifi 2ghz: Removing accessory...
10.11.2020, 11:23:36 [FritzPlatform] Fritz!Box 7590 Wifi 5ghz: Removing accessory...
10.11.2020, 11:23:36 [FritzPlatform] Fritz!Box 7590 Wifi guest: Removing accessory...
10.11.2020, 11:23:36 [FritzPlatform] Fritz!Box 7590 Wps: Removing accessory...
10.11.2020, 11:23:36 [FritzPlatform] Repeater 1750E: Removing accessory...
10.11.2020, 11:23:36 [FritzPlatform] Repeater 1200: Removing accessory...
10.11.2020, 11:23:36 [FritzPlatform] xxx: Removing accessory...
10.11.2020, 11:23:36 [FritzPlatform] xxx: Removing accessory...
10.11.2020, 11:23:36 [FritzPlatform] xxx: Removing accessory...
10.11.2020, 11:23:36 [FritzPlatform] xxx: Removing accessory...
10.11.2020, 11:23:36 [FritzPlatform] Anyone: Removing accessory...
10.11.2020, 11:23:36 [FritzPlatform] Callmonitor: Removing accessory...
10.11.2020, 11:23:36 [FritzPlatform] Callmonitor connection established with 192.168.100.254:1012

**Comment by SeydX** [comment]
Before you uninstall the old version of this plugin, do you removed it also from config and homekit?

It seems there is in issue with your cached accessories

**Comment by Christian-CFP** [comment]
If I delete it from HB the config will automaticaly be deleted. And as well from HK.
Than I restarted HB and installed the plugin. Add config. Thats it.

**Comment by Christian-CFP** [comment]
How can I delete the cached accessoires? Terminal?

**Comment by SeydX** [comment]
i dont know if it is possible to remove single accessories from cache with HOOBS

in config ui x there is a option therefore

![newdebug](https://user-images.githubusercontent.com/34152761/98662629-5c69ff00-2348-11eb-92bf-f52aa3f0eedf.JPG)

**Comment by Christian-CFP** [comment]
Wir können auch deutsch reden ;)
No hhobs does not have this option. I will search in Terminal.

**Comment by SeydX** [comment]
Das Problem ist das hier

`` Error: Cannot add a bridged Accessory with the same UUID``

Kannst du nochmal das Plugin aus dem config entfernen bitte, hb neustarten und warten bis alle Geräte weg sind (es dürfte keine Fehlermeldung im log erscheinen)

Anschließen das Plugin wieder in config einfügen aber alle Geräte mit verschiedenen Namen bitte

**Comment by Christian-CFP** [comment]
Ok, habe es noch mal komplett entfernt und neu installiert.
Jetzt scheint es auch nach dem restart des Services zu klappen. Danke.

PS: Gibt es eine reboot Funktion für die einzelnen Geräte? Habe keine gefunden.

**Comment by SeydX** [comment]
Was meinst du genau? wenn "readOnly" false ist dann lassen sich die Geräte auch rebooten

**Comment by Christian-CFP** [comment]
Sind readonly false. War mal in eve eine Reboot funktion (Schalter) ging aber nicht bei mir. Jetzt ist keine Reboot funktion zu sehen. Oder Strom aus? Aber dann kann ich nicht mehr auf das Gerät zugreifen.

**Comment by SeydX** [comment]
Diese reboot funktion ist direkt im switch jetzt integriert. Ist nicht mehr so sehbar.

**Comment by Christian-CFP** [comment]
Sehr cool!

**Comment by SeydX** [comment]
Dann schließe ich es mal :)

**Comment by Christian-CFP** [comment]
Ne frage bzgl. des Call Monitors. Wird der nicht mehr angezeigt? Früher war es in HK jetzt nicht mehr.

**Comment by SeydX** [comment]
Doch, wenn du es im config eingestellt und aktiviert hast dann wird er auch angezeigt, entweder einzeln (ankommende/ausgehende) oder gruppiert

**Comment by SeydX** [comment]
Siehe hier [Example Config Callmonitor](https://github.com/SeydX/homebridge-fritz-platform/blob/2e52eb8c8aafebcb866cb3d6c7d37c2e01ffbd24/example/example-config.json#L139)
