### ISSUE TITLE
Call Monitor & Phonebook

### ISSUE THREAD

**Issue by Christian-CFP** [SeydX/homebridge-fritz-platform#98]
Hier dann die Frage bzgl. des Call Monitors:
Früher war dieser auch in HK jetzt nicht mehr - beabsichtigt?

Und zum Phonebook gibt es folgende Fehlermeldung:
10.11.2020, 13:30:20 [FritzPlatform] Callmonitor: An error occured during reading phonebook!
10.11.2020, 13:30:20 [FritzPlatform] SyntaxError: /home/hoobs/.hoobs/etc/fritzbox/phonebook.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object._readFile (/home/hoobs/.hoobs/node_modules/jsonfile/index.js:25:16)
    at async Socket.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-fritz-platform/src/accessories/callmonitor/callmonitor.js:244:27)
10.11.2020, 13:30:20 [FritzPlatform] Callmonitor: An error occured during reading blackbook!
10.11.2020, 13:30:20 [FritzPlatform] SyntaxError: /home/hoobs/.hoobs/etc/fritzbox/blackbook.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object._readFile (/home/hoobs/.hoobs/node_modules/jsonfile/index.js:25:16)
    at async Socket.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-fritz-platform/src/accessories/callmonitor/callmonitor.js:274:27)

Config:
"callmonitor": {
                "active": true,
                "group": true,
                "ip": "192.168.100.254",
                "port": 1012,
                "incomingTo": [
                    "xxxx"
                ],
                "outgoingFrom": [
                    "xxxx"
                ]
            },
"extras": {
"phoneBook": {
                    "active": true,
                    "duration": 30,
                    "accType": "characteristic",
                    "blacklists": [
                        "Blacklist"
                    ]
                }
            },

**Comment by Christian-CFP** [comment]
PS: Call Monitor in HK gefunden ;)
Aer Phonebook givt fehler aus.

**Comment by SeydX** [comment]
sollte mit v5.0.3 gefixt sein

**Comment by Christian-CFP** [comment]
Ok, die Fehler tauchen im Log nicht mehr auf, jedoch die Zuordnung zum Phonebook auch nicht. Nur Nummer.

**Comment by SeydX** [comment]
@Christian-CFP 

Hast du denn überhaupt dein phonebook „generiert“ ?

Du musst dein phonebook schalter in apple home (wenn du es als switch eingestellt hast) oder in zb EVE (wenn du es als characteristic eingestellt hast) einschalten

So wird dein phonebook generiert, was das Plugin benötigt um die ankommende/ausgehenden Anrufen zu vergleichen.

Und nur wenn die Nr dort auftaucht wird auch der Name angezeigt

**Comment by Christian-CFP** [comment]
Ok, das manuelle Anstoßen war mir neu, aber nein geht noch nicht.
Dazu muss ich sagen, dass ich ein cloud Telefonbuch nutze. (das ging in der V4 auch). In dem Standard Telefonbuch ist nix drin.

**Comment by Christian-CFP** [comment]
Ok getestet. Er nimmt das standard Telefonbuch. Kann man das ändern?

**Comment by SeydX** [comment]
Hast du debug an im config für das Plugin?

Wenn ja, da müsste sowas stehen wie

``Found 2 phonebook(s). Fetching entries...``

Was steht bei dir genau?

Am besten den Log schicken von dem Moment an wo du phonebook einschaltest bis es sich selbst ausschaltet

Lg

**Comment by Christian-CFP** [comment]
Ok, er findet beide anscheinend aber er übernimmt es nicht:

10.11.2020, 15:18:49 [FritzPlatform] Fritz!Box 7590: Found 2 phonebook(s). Fetching entries...
10.11.2020, 15:18:49 [FritzPlatform] Fritz!Box 7590: Phone book [0] done.
10.11.2020, 15:18:50 [FritzPlatform] Fritz!Box 7590: Phone book [1] done.
10.11.2020, 15:18:50 [FritzPlatform] Fritz!Box 7590: Storing phonebook results to /home/hoobs/.hoobs/etc/fritzbox/phonebook.json
10.11.2020, 15:18:50 [FritzPlatform] Fritz!Box 7590: Done!

**Comment by SeydX** [comment]
@Christian-CFP 

Ich check das mal gleich

**Comment by Docjones** [comment]
```
[10/11/2020, 15:25:48] [FritzPlatform] Fritzbox PhoneBook: Getting state (phoneBook)...
[10/11/2020, 15:25:51] [FritzPlatform] Fritzbox PhoneBook: Getting state (phoneBook)...
[10/11/2020, 15:26:17] [FritzPlatform] Fritzbox PhoneBook: OFF not supported! (phoneBook)
[10/11/2020, 15:26:20] [FritzPlatform] Fritzbox PhoneBook: OFF not supported! (phoneBook)
[10/11/2020, 15:26:27] [FritzPlatform] Fritzbox PhoneBook: Getting state (phoneBook)...

```

Trotz Konfiguration und Einschalten des Switches via Eve bleibt die `phonebook.json` Datei im Verzeichniss `fritzbox` leer

Folgende config habe ich dafür:
```
                "phoneBook": {
                    "active": true,
                    "accType": "switch"
                }

```

`debug` ist `true` für das Plugin, mehr kommt da scheinbar nicht?

**Comment by SeydX** [comment]
@Docjones 

die Datei wird nicht erstellt weil das Plugin denkt das du den Schalter ‚ausschaltest‘ 

Der Schalter müsste ja sowieso ‚AUS‘ sein oder?

Wenn du den Schalter ‚EINschaltest‘ sollte dann eigtl auch die Datei erstellt werden

Lg

**Comment by Docjones** [comment]
Hi,

so wie ich das sehe, kommt "OFF not supported" genau dann, wenn man den (per default) EINgeschalteten Schalter auswählt (egal, ob HomeApp, Eve oder UI X). Man bekommt dann (richtigerweise) die Mecker, dass Das phonebook nicht ausgeschaltet werden kann. Eine Datei wird aber in keinem Fall erstellt.

Ich fürchte, bei mir hat es etwas mehr zerschossen - presence auf MAC-Adressebene funktioniert auch nicht, und ich sehe im LOG _nicht_, dass die Fritzbox in irgendeinerweise abgefragt wird. Nach dem Start sind die Phonebook Log Einträge das Einzige, was passiert :(

**Comment by Christian-CFP** [comment]
@SeydX 
Das lustige ist, in der /home/hoobs/.hoobs/etc/fritzbox/phonebook.json sind alle Kontakte drin... hmm

**Comment by SeydX** [comment]
@Christian-CFP 

Dann hat es funktioniert. Achte mal auf die Nummer und vergleich diese Nummer mal mit der Nummer des ankommenden Anrufs im Log

Wenn diese beiden Nummern nicht 1 zu 1 identisch sind zeigt er den Namen nicht

@Docjones 

Hast du debug an im config für das plugin?

https://github.com/SeydX/homebridge-fritz-platform/blob/3eff5e91ce9ae9f45b9d7a6fd0c74a68ad06e000/example/example-config.json#L14

**Comment by Docjones** [comment]
@SeydX yep.

**Comment by SeydX** [comment]
@Docjones 

Kannst du mal dein config.json posten bitte

**Comment by Docjones** [comment]
Na klar, hier bitteschön:

```
{
    "bridge": {
        "name": "Homebridge RXs",
        "username": "0E:97:B2:83:0E:55",
        "port": 51281,
        "pin": "121-40-872"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "FritzPlatform",
            "debug": true,
            "devices": [
                {
                    "name": "Fritzbox",
                    "host": "192.168.50.1",
                    "username": "xxxx",
                    "password": "xxxxx",
                    "ssl": true,
                    "tr064": true,
                    "igd": true,
                    "master": true,
                    "readOnly": true,
                    "connection": "cable"
                }
            ],
            "presence": [
                {
                    "name": "Marc",
                    "address": "D0:D2:B0:28:56:0F",
                    "accType": "occupancy"
                }
            ],
            "smarthome": [
                {
                    "accType": "false"
                }
            ],
            "callmonitor": {
                "active": true,
                "group": true,
                "ip": "192.168.50.1",
                "port": 1012,
                "incomingTo": [
                    "nnnn"
                ],
                "outgoingFrom": [
                    "nnnn"
                ]
            },
            "extras": {
                "alarm": {
                    "active": false
                },
                "wakeup": {
                    "active": false
                },
                "ringlock": {
                    "active": false
                },
                "phoneBook": {
                    "active": true,
                    "accType": "switch"
                }
            },
            "options": {
                "polling": {
                    "timer": 1
                }
            },
            "telegram": {
                "active": false
            },
            "platform": "FritzPlatform"
        }
    ],
    "id": "config"
}
```

**Comment by Christian-CFP** [comment]
Wie gesagt, war in der V4 alles super.
Ich glaube es ist die Vorwahl. Alle meine Nummern sind mit 0049... abgespeichert.
Wenn ich vom Handy aus anrufe wird mir nur die 0170... angezeigt ohne Vorwahl (0049).
Wenn ich diese ins Tel.B. ohne 0049 eintrage zeigt er mir den Namen an. Sobald die 0049 mit im Telefonbuch steht geht es nicht.

Also liegt es daran.

**Comment by Docjones** [comment]
@Christian-CFP das war bestimmt der alte config-Eintrag "country", der auf "DE" stehen musste

**Comment by SeydX** [comment]
@Christian-CFP 

Die Info habe ich benötigt. Jetzt weiss ich was ich fixen muss danke dir

**Comment by SeydX** [comment]
@Docjones 

Du hast den Polling timer auf 1? Setz den mal auf 15 bitte und versuch erneut

**Comment by Docjones** [comment]
O.o was ist das für ne Einheit?

**Comment by SeydX** [comment]
@Docjones 

Sekunden. Du sagst dem Plugin quasi das er jede sekunde pollen soll.

**Comment by Docjones** [comment]
-.- okay... dachte, das wären Minuten :)

Datei kommt trotzdem keine auf der Festplatte an, dafür kommt im Log jetzt folgender Eintrag (Identify Request):

```
[10/11/2020, 16:13:34] Homebridge v1.2.3 is running on port 51281.
[10/11/2020, 16:13:34] [FritzPlatform] Callmonitor connection established with 192.168.50.1:1012
[10/11/2020, 16:13:34] [FritzPlatform] Fritzbox: Polling state (router)...
[10/11/2020, 16:13:37] [FritzPlatform] Fritzbox PhoneBook: Getting state (phoneBook)...
[10/11/2020, 16:13:40] [FritzPlatform] Fritzbox PhoneBook: Getting state (phoneBook)...
[10/11/2020, 16:16:20] [FritzPlatform] Fritzbox PhoneBook: Getting state (phoneBook)...
[10/11/2020, 16:16:39] [FritzPlatform] Fritzbox PhoneBook: Identify requested.
```

**Comment by Docjones** [comment]
Ich glaube, da ist bei mir was im argen - ich habe ein neues Raspberry Image aufgespielt, Version der Homebridge auf v1.2.3 hochgezogen, _nur_ das Fritzbox-Plugin v5.0.3 installiert und es funktioniert immer noch nicht... 

- Presence -> Macadresse vom Handy hinterlegt - steht immer auf OFF, obwohl Fritzbox das Handy eingebucht hat
- Phonebook -> Schalter in eve ist da, wenn ich phonebook auf ON stelle, kommt "Fritz!Box: Getting state (phoneBook)...", aber kein phonebook.json im Plugin Verzeichniss
- Callmonitor funktioniert. löst aber keine Nummern auf

Insbesondere, da "presence" nicht funktioniert und das phonebook nicht abgeglichen werden kann, vermute ich, dass meine Fritzbox  rumbockt. Kann aber nirgends was finden... :(

**Comment by SeydX** [comment]
@Docjones 

Könntest du mir den kompletten Log AB restart mal schicken bitte

**Comment by Docjones** [comment]
https://www.dropbox.com/s/lmcdp8tojv0lf57/homebridge.log.txt?dl=0

**Comment by SeydX** [comment]
@Docjones 

Ist ab

```
[10/11/2020, 18:52:46] [FritzPlatform] Fritz!Box: Polling state (router)...
```

nichts mehr zu sehen? Es scheint als würde das Plugin beim abfragen ‚hängen‘

**Comment by SeydX** [comment]
@Christian-CFP 

Callmonitor/Phonebook habe ich gefixt. Wird mit der nächsten Version kommen

**Comment by Docjones** [comment]
@SeydX - das war das komplette log. Hat sich auch nicht mehr verändert seitdem

**Comment by SeydX** [comment]
@Christian-CFP 

Callmonitor/Phonebook sollte mit v5.0.4 gefixt sein

**Comment by SeydX** [comment]
@Docjones 

Hast der Benutzer auch alle Rechte? TR064 aktiv?

Siehe hier : https://github.com/SeydX/homebridge-fritz-platform/blob/master/docs/Installation.md

**Comment by Christian-CFP** [comment]
Also:
Outgoing Calls geht noch nicht.
Incomming: Geht wird erkannt, jedoch ist jetzt der ganze "Wust" an Telefonnummernmöglichkeiten in den Klammern enthalten. Nicht nur die Nr., die anruft, sondern alle Nr. die dem Kontakt hinterlegt sind.

BSP:
11.11.2020, 00:17:01 [FritzPlatform] Callmonitor: Incoming call from: Mir ( +49handy,0170handy,0049170handy,+4930gesch,030gesch,004930gesch ) to Privat

**Comment by SeydX** [comment]
@Christian-CFP 

Hab vor paar Minuten wieder ne neue Version hochgeladen was Outgoing calls fixen sollte. Wegen den ganzen nummern schaue ich nochmal nach

**Comment by SeydX** [comment]
@Christian-CFP 

v5.0.6 ist online und sollte das Problem nun endgültig beheben

**Comment by Christian-CFP** [comment]
Hoobs zeigt das Update sehr sehr verzögert an. Werde mir es morgen anschauen und Rückmeldung geben. 

Habe ich das richtig gelesen, dass die Chats jetzt beim PWD nun auch möglich sind?

**Comment by SeydX** [comment]
@Christian-CFP 

Meinst du specials chars im passwort? Jep ist möglich

**Comment by Christian-CFP** [comment]
@SeydX Danke für deine schnelle Hilfe. Funktioniert nun beides!
Kann geschlossen werden.

**Comment by Christian-CFP** [comment]
@SeydX Kurz als Anregung... (vielleicht)
Ich weis natürlich nicht, ob das umsetzbar ist, jedoch wäre es vielleicht besser?
HK unterstützt ja nun Türklingeln. Wäre es nicht eine Idee, den Callmonitor nicht als Kontaktsensor in HK darzustellen, sondern als Türklingel? So könnte man ja auch in HK, die Nr. eines Anrufers in die Mitteilung übertragen und anzeigen lassen. Plus, die HomePods würden auch konfiguriert werden können als "Klingel".

So aber nun war es das (hier ;) )

**Comment by SeydX** [comment]
@Christian-CFP 

Möglich ist alles, aber Türklingel würde nicht gehen oder kein Sinn machen weil eine Türklingel „programmierbare switch events hat“

![8BD81F7D-C733-47B7-9D93-642E384CFB64](https://user-images.githubusercontent.com/34152761/98799882-fcd72680-240f-11eb-8e45-244153a4a729.jpeg)

**Comment by SeydX** [comment]
@Docjones 

Falls du noch probleme hast öffne bitte ein issue
