### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by HBAPP1** [SeydX/homebridge-fritz-platform#99]
Thank you very much for your update, but I still need the latest instructions for an installation.

**Comment by SeydX** [comment]
Hey what u want to know exactly?

There is an [example config](https://github.com/SeydX/homebridge-fritz-platform/blob/master/example/example-config.json) to setup manually

btw. I prefer to use config ui x

the wiki section with information for all keys in config.json is currently in progress

**Comment by Jemeins** [comment]
Erst mal Danke für die Möglichkeit, dass die FritzBox in HomeKit jetzt ausgeblendet werden kann!
Besteht immer noch die Möglichkeit, dass das Plugin die FritzBox + Repeater beim ersten Start automatisch erkennt? Oder muss ich alles Manuell konfigurieren?

**Comment by SeydX** [comment]
Die Geräte müssen alle manuell in config.json integriert werden

**Comment by BKrnk1337** [comment]
Eventuell könnte man die FritzBox Seriennummer bzw. das Modell der FritzBox unter folgender URL auslesen:

http://fritz.box/jason_boxinfo.xml

**Comment by SeydX** [comment]
@BKrnk1337 

Das lesen der Seriennummer etc ist kein Problem, aber eine zusätzliche Anfrage die getätigt werden muss. Je mehr Anfragen, desto mehr Probleme können auftreten. Deswegen habe ich mich dazu entschieden solche Sachen in die config zu lagern und es dem User zu überlassen :)
